### ISSUE TITLE
How to configure orbot on Android Studio

### ISSUE THREAD

**Issue by abozanona** [guardianproject/orbot#100]
I'm trying to run orbot on Android Studio but It doesn't work for me.

In orbotservice.gradle I add

    externalNativeBuild {
        ndkBuild {
            path 'src/main/jni/Android.mk'
            path 'src/main/jni/Application.mk'
        }
    }

But when I run I get the error
    Couldn't load tun2socks from loader dalvik.system.PathClassLoader[dexPath=/data/app/org.torproject.android-8.apk,libraryPath=/data/app-lib/org.torproject.android-8]: findLibrary returned null

I'm really new to `ndk` so is there any documentation or guide on how to configure robot to run with android studio?
Please note that I'm not familiar with eclipse and I don't know how to link the files with the project.

**Comment by n8fr8** [comment]
We don't use the Android NDK built into Android Studio yet. We just use the command line "ndk-build" tools. We are working on updating this in the next major release, but for now, stick to the command line!
