### ISSUE TITLE
Start Orbot via always-on VPN without onboarding

### ISSUE THREAD

**Issue by t-m-w** [guardianproject/orbot#1007]
When Orbot is the always-on VPN, it should start automatically, even if it isn't set to start on boot.

https://github.com/guardianproject/orbot/pull/828 was merged into v16_maintenance, but it doesn't appear to have been ported to v17 yet.

Just wanted to get this issue in while I'm thinking about it.

**Comment by bitmold** [comment]
Thank you for this, I'm sorry I fell off the face of the Earth last spring, I'm glad your patch got merged into v16 and I'm happy to have tested it and merged in your new patch into 17
