### ISSUE TITLE
Orbot is leaking ICMP traffic on Android 

### ISSUE THREAD

**Issue by ihateprogramming88** [guardianproject/orbot#1008]
**Describe the Bug**
After testing with termux and orbot, it has been established that ICMP  traffic is being leaked with Orbot 
**To Reproduce**
Install Termux, establish the vpn tunnel on orbot and run ping google.com on Termux. 

for UDP nc -vz -u 8.8.8.8 443
possibly leaking UDP?

![image](https://github.com/guardianproject/orbot/assets/121917762/ca45f88e-34c6-43c4-8f0c-042abbe6e9b5)

![image](https://github.com/guardianproject/orbot/assets/121917762/51c1b08f-ebe8-46ac-9511-f58ca3f950f7)
![image](https://github.com/guardianproject/orbot/assets/121917762/35664db1-c365-4eea-987a-44cb0dcb9767)

- Device: Pixel 8 Pro
- OS: GrapheneOS Android 14
- Version: Orbot for Android 17.1.1 BETA 2 (tor 0.4.7.8)

**Comment by Woman-at-arms** [comment]
I can reproduce this issue using ping in Termux.

I have Orbot configured as a VPN, connected, and the Android VPN kill switch is enabled for the VPN.

Orbot appears to be leaking ICMP traffic through the VPN.

**Comment by Woman-at-arms** [comment]
Uh oh.

It ALSO leaks UDP.

You can confirm this with `nc -vz -u 8.8.8.8 443`.

**Comment by Woman-at-arms** [comment]
Seems like the netcat test might not be accurate :/

**Comment by Ufyfughx** [comment]
@n8fr8 and @bitmold and @meenbeese pleese take a look

**Comment by n8fr8** [comment]
Yes we are.

**Comment by n8fr8** [comment]
https://mullvad.net/en/help/configure-connectivity-checks-on-android/

**Comment by n8fr8** [comment]
Is it also possible when you run ping in termux, it actually using Android's Private DNS feature which provides dns-over-tls? https://www.makeuseof.com/android-private-dns-everything-you-need-to-know/

**Comment by n8fr8** [comment]
for testing: https://github.com/guardianproject/orbot/releases/tag/17.1.1-BETA-3-tor-0.4.8.7

**Comment by trinity-1686a** [comment]
Have you confirmed there is a leak, for instance by running tcpdump on your wifi access point?
When I reproduce the experiment, I get the same results, but nothings leak to the access point. Additionally, if I try pinging IPs that shouldn't answer (172.16.1.1, private network, or 203.0.113.1, ["provided for use in documentation"](https://datatracker.ietf.org/doc/html/rfc5737#section-3)), they answer, with ~1ms latency and a ttl of 64.
So far, I think some component of Orbot is just replying itself to every icmp echo request/ping it sees
