### ISSUE TITLE
[Question] Where can I view Cure53 full audit

### ISSUE THREAD

**Issue by ghost** [guardianproject/orbot#1009]
Where can I view Cure53 full audit?

**Comment by n8fr8** [comment]
We are updating the Orbot.app website and will post it there. 
[ORB-01-report.pdf](https://github.com/guardianproject/orbot/files/13250020/ORB-01-report.pdf)
[Pentest-Report Orbot Android Mobile App 05.2023 - Guardian Project Mitigation Plan.pdf](https://github.com/guardianproject/orbot/files/13250021/Pentest-Report.Orbot.Android.Mobile.App.05.2023.-.Guardian.Project.Mitigation.Plan.pdf)

I've also attached the results here. Any high or critical issues were fixed and released back in May 2023 as part of the v17 product line.
