### ISSUE TITLE
[Question] Is “hosted onion services” secure?

### ISSUE THREAD

**Issue by Hulk667i** [guardianproject/orbot#1017]
Hi!

If I will host small html static website, is it secure? It is not darknet site, I just don’t want to pay for domain name.

I am going to create on domain on .onion and than put in QR code something like [domain].onion.to to make it accessible from clearnet

**Comment by n8fr8** [comment]
The security provide is the same as hosting an onion site using the tor daemon on a desktop. It is the same code and capability. You just need to run a local web server app on your Android device.

More info here: https://community.torproject.org/onion-services/setup/
