### ISSUE TITLE
C compiler cannot create executables

### ISSUE THREAD

**Issue by abozanona** [guardianproject/orbot#102]
When I run the command `make -C external` I get this error

Initializing Automake:
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for arm-linux-androideabi-strip... no
checking for strip... strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether ln -s works... yes
checking for style of include used by make... GNU
checking for arm-linux-androideabi-gcc... /opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/opt/android-ndk/platforms/android-16/arch-arm
checking whether the C compiler works... no
configure: error: in `/home/meqdad/Desktop/Orbot/external/xz':
configure: error: C compiler cannot create executables
See `config.log' for more details
Makefile:200: recipe for target 'xz/Makefile' failed
make: *** [xz/Makefile] Error 77
make: Leaving directory '/home/meqdad/Desktop/Orbot/external'

![image](https://user-images.githubusercontent.com/12738028/33238846-7276fac6-d29e-11e7-99f0-ed70f23802ca.png)

**Comment by goapunk** [comment]
Could you maybe post the contenct of the config.log ? 
What OS are you on? Did you use the ndk shown in the image ? I think Orbot still uses the ndk 10e. Could you retry it with this one ?
