### ISSUE TITLE
if 0.4.8.9 is "stable," where are the compiled binaries for Android???

### ISSUE THREAD

**Issue by githubw0** [guardianproject/orbot#1023]
I'm running 0.4.8.7 on Android 13 and it is spuriously stopping/crashing ever since the godawful security alert notice that urged upgrade to 0.4.8.8. coincidence or correlation? until then, 0.4.8.7 wasn't nearly as cantankerous.

i don't compile orbot on my own. i trust guardian project to compile clean/safe binaries. BUT WHERE ARE THEY???

PLEASE, COMPILE BINARIES & POST. PLEASE....

**Comment by n8fr8** [comment]
We haven't built or released them yet, but when we do, they will be up here:
https://github.com/guardianproject/gpmaven/tree/master/info/guardianproject/tor-android/0.4.8.7

The AAR file is a JAR/ZIP file that contains all of the architecture shared libraries we compile using this project: https://github.com/guardianproject/tor-android/

We'll have it out soon.

**Comment by githubw0** [comment]
i found torLib2so 0.4.8.9 in armv8 from torproject, but no apk installer.

i also found working apk for torbrowser Android 13.0.4 for armv8, but no way to intstall orbot 0.4.8.9 as standalone from it.

why is there delay/reluctance to release apk-s for orbot 0.4.8.9? 0.4.8.7 has suddenly become completely unreliable on Android, with dozens of spurious crashes per day.

0.4.8.9 has been out n all torbrowsers since 20-21nov2023. that's also the date on torLib.so.
