### ISSUE TITLE
[UI issues] Some UI fixes proposal

### ISSUE THREAD

**Issue by ghost** [guardianproject/orbot#1034]
Hi!

Here is what I found confusing in your UI.

1. No translation of this text. No string on Weblate also.
[Screenshot](https://github.com/guardianproject/orbot/assets/152715214/c6ea3964-6cbd-43d6-9fa7-433bf05cdcdb)

2. Please move this a little down. It looks very cluttered now (I marked with empty box where it better be):
[Screenshot 2](https://github.com/guardianproject/orbot/assets/152715214/35d411d2-a05a-4f5b-91f4-898fc965ab48)

3. Too huge “Copy log” button. It is overlapping text. Can you make it a little bit tinier?
[Screenshot 3](https://github.com/guardianproject/orbot/assets/152715214/42d873e4-5a40-4587-bb0e-062984667deb)

I hope you will find this useful. Thank you!

**Comment by Gydrhjj** [comment]
@n8fr8 and @bitmold please take a look
