### ISSUE TITLE
Webtunnel Bridges does not work

### ISSUE THREAD

**Issue by YuryKomar** [guardianproject/orbot#1088]
In the Tor Browser I use the following Webtunneel Bridge
***
webtunnel [2001:db8:9443:367a:3276:1e74:91c3:7a5a]:443 54BF1146B161573185FBA0299B0DC3A8F7D08080 url=https://d3pyjtpvxs6z0u.cloudfront.net/Exei6xoh1aev8fiethee ver=0.0.1
***

But in Orbot this Bridge does not work, infinite connections without success...

Why this webtunnel? I have the only option to use this Bridge to pass through firewall, but only in Tor Browser, same on PC and Android, But I need whole device to have connected, means to provide internet to another apps as well...

**Comment by n8fr8** [comment]
WebTunnel is not yet supported in Orbot

**Comment by 117649** [comment]
> WebTunnel is not yet supported in Orbot

Very bad orbot is unusable at my location without webtunnel

**Comment by YuryKomar** [comment]
> > WebTunnel is not yet supported in Orbot
> 
> Very bad orbot is unusable at my location without webtunnel

I have same problem. Only Webtunnel can help to break the firewall

**Comment by yverry** [comment]
The IPv6 ( [2001:db8:9443:367a:3276:1e74:91c3:7a5a]:443 ) is an addr reserved for documentation
```
inet6num:     2001:db8:0:0:0:0:0:0/32
organisation: IPv6 Address Prefix Reserved for Documentation
status:       RESERVED
```

**Comment by bitmold** [comment]
Hey, we're working to implement webtunnel in Orbot right now. But as of yet, there are no releases that even have webtunnel (broken or not) it so I'm closing this issue.

**Comment by Davidasx** [comment]
> Hey, we're working to implement webtunnel in Orbot right now. But as of yet, there are no releases that even have webtunnel (broken or not) it so I'm closing this issue.

It is failing for me even now.
Isnt it true that Tor browser itself uses orbot? If so, why doesnt Orbot support webtunnel?

**Comment by n8fr8** [comment]
Yes, it is still failing because we don't have support for it. I will let you know when it is done.

Tor Browser forked (copied) Orbot service code into its own codebase, and maintains it separately now from Orbot. They added Webtunnel support, but that code isn't the same as used in Orbot.

We will have this done soon. Thanks!
