### ISSUE TITLE
[Feature Request] Shut down Orbot when unused

### ISSUE THREAD

**Issue by kaikli** [guardianproject/orbot#1090]
**Is your feature request related to a problem? Please describe.**
Since the last update from fdroid (`17.0.0-RC-1-tor.0.4.7.11` -> `17.2.1-RC-1-tor-tor-0.4.8.7`) Orbot drains my battery very fast probably because orbot does not crash so often anymore :).

Maybe in combination with the existing feature to allow other apps to start orbot in the backgroud, it would be nice to shut it down when unused after a specific amount of time.

**Describe the Solution You'd Like**
Add a option to shut down orbot after a amount of time if no connections where made. For this activity check connections to keep the circuit alive and snowflake should be ignored.

Also add a option to start orbot and temporary disable the previous timeout when connected to a power supply for example to allow snowflake to run when connected to a power supply.

**Comment by n8fr8** [comment]
The Tor daemon in Orbot will go to sleep automatically when not in use.

If you have any Snowflake feature enabled, that may be the cause of the battery drain. I would disable and compare.

There is also the hard full exit option in the settings menu.

**Comment by kaikli** [comment]
> The Tor daemon in Orbot will go to sleep automatically when not in use. If you have any Snowflake feature enabled, that may be the cause of the battery drain. I would disable and compare. There is also the hard full exit option in the settings menu.

> Your battery usage may be related to issue #1091

After disabling the Snowflake feature and reconfiguring an app that probably kept Orbot alive the battery consumption is back to normal.
I will watch the behavior further.

**Comment by kaikli** [comment]
This problem only occurs with activated Kindness Mode, but even when the "Only on Charging" option is enabled.

Because this problem probably relates to #1091 I will close this feature request.
