### ISSUE TITLE
[BUG] System WiFi failure after installing Orbot 16.6.3-RC-1-tor.0.4.7.10

### ISSUE THREAD

**Issue by paboum** [guardianproject/orbot#1095]
**Describe the Bug**
I suspect Orbot is messing with my system WiFi "CaptivePortal" service which causes most other apps not to be able to use clearnet at all (see logs below).

**To Reproduce**
1. Buy a new phone, install updates
2. Install Orbot
3. Not run Orbot at all
4. WiFi starts yielding "Connected, no internet" warnings which force me to restart WiFi every few minutes.

**Expected Behavior**
No interference between Orbot and system WiFi.

**What Custom Configuration Do You Use?**
None at all.

**Screenshots**

**Smartphone (please complete the following information):**
- Device: Pixel 8 Pro
- OS: Android 14
- Version: UQ1A.240205.004

**Android Logs (Advanced)**
```
02-25 20:22:37.480  1000  1516  5190 W ActivityManager: Foreground service started from background can not have location/camera/microphone access: service org.torproject.android/.service.OrbotService
02-25 20:22:37.483  1000  1516  5190 W ActivityManager: Starting FGS with type dataSync code=4 callerApp=ProcessRecord{64fc87 14965:org.torproject.android/u0a322} targetSDK=31 requiredPermissions=all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_DATA_SYNC] 
02-25 20:22:37.492  1073  2206 13032 D NetworkMonitor/190: PROBE_FALLBACK http://www.google.com/gen_204 Probe failed with exception java.net.SocketTimeoutException: failed to connect to www.google.com/172.16.204.133 (port 80) from /192.168.100.116 (port 55804) after 10000ms
02-25 20:22:37.494  1073  2206 13032 D NetworkMonitor/190: isCaptivePortal: isSuccessful()=false isPortal()=false RedirectUrl=null isPartialConnectivity()=false Time=13020ms
02-25 20:22:37.497  1000  1516  1945 D ConnectivityService: [190 WIFI] validation failed
```

**Additional Context**
After I ran Orbot, granted it permissions and set autorun off, the issue seems to have stopped. I will monitor this and update if relevant.

**Comment by n8fr8** [comment]
If Orbot is deactivated and the VPN is not on, there is no way for it to block your connection. 

Please try our latest v17 release canddiate that you can download from here:
https://github.com/guardianproject/orbot/releases/tag/17.2.1-RC-1-tor-0.4.8.7

or through Google Play Open Testing.

**Comment by paboum** [comment]
It may also be the case that my openwrt device is DNS-hijacking the traffic, but I can't see how is that possible and why doesn't affect other devices.

Since the issue reoccurred after I uninstalled Orbot, guess we can close this one for now.
