### ISSUE TITLE
[BUG] android/spy. Agent. Dfm malware 

### ISSUE THREAD

**Issue by 1anonyy** [guardianproject/orbot#1107]
My antivirus picked up a problem, I've had this app installed for a year. See picture. 

Please advise 
![Screenshot_20240312_210110_ESET Mobile Security](https://github.com/guardianproject/orbot/assets/19263684/c7f9aa8d-ec3d-4b82-8c2f-dca9cf3290f0)

**Comment by n8fr8** [comment]
It is a false positive from the antivirus maker. 

However, if you want to be sure you have the authentic release signed by us, you can download the latest direct APK from here: https://github.com/guardianproject/orbot/releases/download/17.2.1-RC-1-tor-0.4.8.7/Orbot-17.2.1-RC-1-tor-0.4.8.7-fullperm-arm64-v8a-release.apk

**Comment by 1anonyy** [comment]
It's from play store. Not anywhere else
