### ISSUE TITLE
Does not connect after first disconnect

### ISSUE THREAD

**Issue by gidoBOSSftw5731** [guardianproject/orbot#111]
After i connect then disconnect I cannot reconnect. the notification says so, the onion is yellow, and apps set to use it don't. wiping cache has no affect.

**Comment by n8fr8** [comment]
We've released Orbot 16.3.1 with many important fixes. please test!

**Comment by gidoBOSSftw5731** [comment]
Currently, when trying to connect initially the process freezes after adding the control port. I also dont remember what this error was or what device I was testing it on. I support this project, but do not know about this particular issue.

**Comment by n8fr8** [comment]
We've continued to address this issues in a few different ways, and it really should be fixed now.

https://github.com/guardianproject/orbot/releases/tag/16.3.3-RC-1-tor-0.4.3.6

**Comment by gidoBOSSftw5731** [comment]
It sounds like orphaned processes were the problem, but they've now been resolved, thanks for the work!
