### ISSUE TITLE
TOR won't start...

### ISSUE THREAD

**Issue by itsnotlevel1** [guardianproject/orbot#1146]
The last version of orbot I was on worked fine You hit the onion it turns green everything's good. This version I've noticed only in the last few months it could have been happening the whole time I'm not always have it turned on. I start orbot and it's the purple button that says start VPN I tap the purple button it does nothing I go to help connect and I ask Tor which connected to use I pick that and I hit connect nothing happens takes me back to the main screen with the purple button that says start VPN nothing happens it doesn't start which is new and I don't know how long ago its new. 

Pixel 6A, Android, newest orbot RC

**Comment by meenbeese** [comment]
This reproduces on Android 14, right? I have seen some issues on the master branch with Android 14 on the emulator.

**Comment by itsnotlevel1** [comment]
About a week after I posted the issue my battery was giving issues on my Pixel 6A... I did a full factory reset it fixed the battery issues and it looks like it fixed orbot too. Sorry.

Paul

Sent from Proton Mail Android

-------- Original Message --------

**Comment by meenbeese** [comment]
Glad to hear that it resolved your issues with Orbot. Please feel free to add any bugs you experience here or close the issue if not.

**Comment by itsnotlevel1** [comment]
Factory reset fixed my battery issues and orbot not working. Thanks
