### ISSUE TITLE
[BUG] Not listing all installed applications

### ISSUE THREAD

**Issue by mdziczkowski** [guardianproject/orbot#1148]
**Describe the Bug**
Orbot doesn't list all installed applications on the phone

**To Reproduce**
1. Go to "Select apllications"
2. Compare the installed applications with the ones listed here

3. See that some applications aren't listed here

**Expected Behavior**
All applucations should be listed hete and be selectable

**Smartphone (please complete the following information):**
- Device: Oppo Reno5 5G
- OS: Android 13

**Comment by bitmold** [comment]
It only lists applications that have the `INTERNET` permission. It also doesn't list some applications that use Tor in their own way such as Tor Browser. Unless you have an app installed that doesn't meet this criteria and it is still unlisted then that is, in fact, a bug.

**Comment by mdziczkowski** [comment]
Hello. Just from curriosity, why is TorBrowser excluded from showing up on the list?

Connecting additionally thru Orbot could give an additional layer of connection privacy, aspecially a backup connection in case that the other has dome kind issues (for example becones suddenly interrupted)
