### ISSUE TITLE
why orbot is not routing its own traffic through its vpn ?

### ISSUE THREAD

**Issue by saadullah2216** [guardianproject/orbot#1150]
**Bug**
Orbot is not allowing its traffic through Vpn and Tor. Other apps like chrome are working fine when i check tor connctivity using https://check.torproject.org/ it is showing connected but when i check tor connectivity inside orbot using webview it shows me tor is not connected.

**To Reproduce**
1. Go to 'OrbotVpnManager class'
2. Go to 'doLollipopAppRouting' method
3. Remove this line of code 'builder.addDisallowedApplication(mService.getPackageName());'
4. Vpn is running tor is unable to connect.
5. If tor is connected some how i am unable to use vpn+tor in Orbot.

**Expected Behavior**
Orbot must allow its traffic through Vpn and tor.

**What Custom Configuration Do You Use?**
I removed this line of code 
"builder.addDisallowedApplication(mService.getPackageName());"
so that vpn service allow its own traffic as well.

but the problem i am facing is tor is not able to connect and i am unable to use tor within orbot.

**Smartphone**
- Device: [Pixel 6]
- OS: [Android 14]
- Version: [ v17.1 RC 2]

**Comment by n8fr8** [comment]
Why are you removing that line of code? That is the key line of code that allows Tor to connect outside of the VPN. Tor must have direct access to the internet. We have no separate VPN server - the VPN itself goes through Tor on the local device.

**Comment by saadullah2216** [comment]
@n8fr8 actually i want to capture my webview traffic with orbot vpn and then forward it to tor.

My webview is within orbot app.please help me how How can i do it ?

One way is to use proxy with in webview but i dont want to use it.

**Comment by n8fr8** [comment]
Ah okay, that is a good idea to use the VPN to capture it, but I see why you are trying to remove your app from the disallowlist now.

So you are creating a fork of Orbot with a WebView built-in?

**Comment by saadullah2216** [comment]
@n8fr8 yes exactly i am creating a fork of Orbot with a WebView built-in. please guide me how can i capture webview traffic and pass it to tor.
