### ISSUE TITLE
TextSecure/SMSSecure MMS messages can't be sent &/or received while Orbot is on, even with them unchecked.

### ISSUE THREAD

**Issue by herbsmn** [guardianproject/orbot#12]
I use SMSSecure along with Orbot. I use the most recent version of Orbot from F-Droid, which is dated December 20th, 2014.

When I receive and/or try to send MMS messages on SMSSecure while Orbot is running, I get a connection error. I have Orbot set to Torify most all of my apps, but I leave SMSSecure unchecked. Even with SMSSecure uncheck, MMS messages still don't work, so I have to turn Orbot completely off in order to send or receive MMS messages.

I didn't want to file a bug with SMSSecure just to have them say that it needs to be fixed upstream, so I checked out TextSecure's closed issues and found that @Diapolo had the same problem with TextSecure + Orbot that I am having with SMSSecure + Orbot so I posted in the closed Issue asking for them to reopen it, but @moxie0 said that it is Orbot's problem, not TextSecure's problem. https://github.com/WhisperSystems/TextSecure/issues/1950#issuecomment-118436891

Anyways, I'm CCing @BastienLQ & @pR0Ps from SMSSecure on this too just in case they have some ideas on how to fix this.

Hopefully someone can help me figure out how to fix this bug and who's software is causing the problem.

**Comment by n8fr8** [comment]
It isn't Orbot's problem really, it is more how MMS is architected and deployed.

That said, you should be able to exclude apps from Orbot's transparent proxying. Perhaps start with no apps transproxied, and then just choose your browser, and add apps one at a time until MMS stops working. It may be that SMSSecure relies upon some Android subsystem to send MMS, and that is being transproxied.

**Comment by herbsmn** [comment]
I did as you said and checked 'Transparent Proxying' and then hit 'Select Apps' and then 'Proxy None' then 'Close'. I then long pressed on the Orbot button to turn Orbot off and back on to save the changes I had made. After doing this, MMS messages on SMSsecure still don't work and Threema can't send or receive any messages at all. The only way that I can use Orbot and still have functioning MMS in SMSsecure and functioning Threema messages is to turn off Transparent Proxying completely, which is unfortunate because I'd like to transproxy some apps through Tor without losing SMSsecure and Threema functionality. My best guess here is that some Android subsystem is being transproxied even though zero apps have been checked in 'Select Apps - Choose Apps to Route Through Tor'. Please let me know if I can provide you with any more information.

**Comment by herbsmn** [comment]
Also, I don't have TextSecure on my phone anymore so I can't confirm that TextSecure MMS stops working when 'Transparent Proxying' is on and zero apps are checked in 'Select Apps', but I would assume that it doesn't work either.
