### ISSUE TITLE
String Equality Checks

### ISSUE THREAD

**Issue by sisbell** [guardianproject/orbot#140]
In various places in code, string equality checks are using '==' rather than equals(). For example, in OrbotMainActivity, we see
     torStatus == TorServiceConstants.STATUS_OFF

This generally works due to string pool optimizations, which means the strings are referring to the same object. However, '==' checks are not guaranteed to work on all platforms and devices, leading to subtle bugs. 

I see a number of incorrect checks in OrbotMainActivity but this problem may be more general within the code base.

**Comment by bitmold** [comment]
Perhaps they shouldn't be Strings at all. Things in TorConstats, such as the STATUS_ Strings could be refactored to an enum type or some other form of primitive constants

**Comment by n8fr8** [comment]
Agreed!

**Comment by bitmold** [comment]
They should be refactored to integers or something of the sort that's not an enum. Passing enums into Android Intents is feasible but awkward/easy to screw up.
