### ISSUE TITLE
problem when i connect using bridge

### ISSUE THREAD

**Issue by HanamiEria** [guardianproject/orbot#144]
# cannot connect to Tor using  bridge.
I have tested on several android phone and I found Orbot  cannot connect to Tor using  bridge.
But the former version has not problem in using bridge. 
**the log in Orbot is as follows:**
pluggable transport 'obfs4', but we can't find a pluggable transport proxy supporting 'obfs4'. This can happen if you haven't provided a ClientTransportPlugin line, or if your pluggable transport proxy stopped running. 
WARN: Problem bootstrapping. Stuck at 5%: Connecting to directory server. (Can't connect to bridge; PT_MISSING; count 1; recommendation warn; host

**Comment by shadyshrif** [comment]
I think this is same issue  #147
