### ISSUE TITLE
Could not launch managed proxy executable 

### ISSUE THREAD

**Issue by molaeiali** [guardianproject/orbot#147]
Get this error on Orbot-16.0.0-RC-2-multi-SDK16-Android4.1andUp On Android 4.1.1 API 16 Samsung Galaxy S2 when using any type of bridge

WARN: Could not launch managed proxy executable at '/data/data/org.torproject.android/app_bin/obfs4proxy' ('Exec format error').

**Comment by n8fr8** [comment]
There is a new beta release build to try:
https://github.com/n8fr8/orbot/releases/tag/16.0.2-BETA-3

the "armeabi-v7a" APK should work for most people, or just get the "universal" one if you aren't sure.

**Comment by gentleni** [comment]
@molaeiali Did you solve the problem?

**Comment by molaeiali** [comment]
Sorry for answaring late
I installd universal version, no, the problem is still here
![screenshot-2018-05-21-13-33-37](https://user-images.githubusercontent.com/12999682/40299527-b928a496-5cfb-11e8-8599-968db2315079.png)

**Comment by shadyshrif** [comment]
I have same issue with emulator 2.7 QVGA API 23 using the Orbot-16.0.2-BETA-3-fullperm-universal-release.apk

**Comment by shadyshrif** [comment]
Any  news?

**Comment by n8fr8** [comment]
This release should have solved the problem:
https://github.com/guardianproject/orbot/releases/tag/16.1.2-RC-1-tor-0.4.0.4-rc

We have another update coming soon.

**Comment by shadyshrif** [comment]
Yes I can confirm it is fixed now. please try to close it.
