### ISSUE TITLE
Feedback on a language setting BUG

### ISSUE THREAD

**Issue by YXG1994** [guardianproject/orbot#153]
Google Translate

Orbot version: 16.0.2-RC-1
Phone Model:samsung note4 sm-n9100
System Version: Android 4.4.4

BUG Description: After setting it as Chinese, the software interface is still English, and it is normal to modify other languages. Can the next version be fixed? Looking forward for your reply, thank you

**Comment by YXG1994** [comment]
How can no one reply to the answer?

**Comment by n8fr8** [comment]
We are working on it. The last two weeks I have had a lot of travel and meetings, so please be patient.

**Comment by goapunk** [comment]
Looks like this happens not only for Chinese but for any language sometimes. Simply setting the language again until it changed works.

**Comment by bitmold** [comment]
This was probably related to #300
