### ISSUE TITLE
Issue with Android 8 killing Orbot when on background

### ISSUE THREAD

**Issue by smalltimebloke** [guardianproject/orbot#154]
Maybe we can introduce a minor feature enabling the app to be more resilient against unnecessary killing of the app when on background.

**Comment by n8fr8** [comment]
Yes, there are some ways to do that. Will work on it for next release.

(We already do use the permanent foreground notification as part of htis)

**Comment by abshda** [comment]
@n8fr8 I've noticed the tor session running via Termux is much more resilient than when one is running on Orbot. I think @Gedsh may have come up with a solution too with Invizible Pro.

**Comment by n8fr8** [comment]
We've released Orbot 16.3.1 with many important fixes. We don't see the app being killed now, but also resume/restarts are much more reliable.

**Comment by smalltimebloke1** [comment]
@n8fr8 I'm on Android 10 now. Seems much better already.
