### ISSUE TITLE
Orbot VPN stops working when another VPN connects.

### ISSUE THREAD

**Issue by kykeon** [guardianproject/orbot#170]
Imagine the following scenario:

Apps A, B and C configured for Orbot VPN, enforced by AfWall+.
Apps D and E configured for OpenVPN VPN.

The moment I connect OpenVPN, AfWall+ shows toasters for blocked packets for apps A B and C. Checking the apps themselves, indeed there is no connectivity.

OpenVPN apps work fine.

Going into system settings and then VPN, both Orbot and OpenVPN show, but only OpenVPN shows up as connected.

This might be an [android limitation](https://android.stackexchange.com/questions/87306/how-to-connect-to-multiple-vpn-in-android) and nothing to do with Orbot though?

p.s: #151 is not a problem here as this device is on nougat.

**Comment by bitmold** [comment]
As you linked under "android limitation" this is a rule that is enforced by android's [`VpnService`](https://developer.android.com/reference/android/net/VpnService):

> Letting applications intercept packets raises huge security concerns. A VPN application can easily break the network. Besides, two of them may conflict with each other. The system takes several actions to address these issues. Here are some key points:
> - User action is required the first time an application creates a VPN connection.
> - **There can be only one VPN connection running at the same time. The existing interface is deactivated when a new one is created.**
> -  A system-managed notification is shown during the lifetime of a VPN coection.
>  - A system-managed dialog gives the information of the current VPN connection. It also provides a button to disconnect.
> - The network is restored automatically when the file descriptor is closed. It also covers the cases when a VPN application is crashed or killed by the system.

So things actually seem to be behaving how they were built for better or worse :)
