### ISSUE TITLE
Orbot breaks when bridge list is on

### ISSUE THREAD

**Issue by nenionoda** [guardianproject/orbot#178]

**Comment by nenionoda** [comment]
Thanks for the response.
the issue remains with obfs4 too -- just tested it.
by the way, the issue is very evasive, occurring only when the bridges are copied directly from gmail into orbot.
taking a look at the logs, the issue looks like to be an "invalid" character right after the starting "obfs4" in bridges.
for example, with the bridges below,
obfs4 45.79.202.225:9443 98174F2EB3F9DC2DC86F8ACFF22B2D779657454E cert=0oiBm/ucuMFKk/RIH9CufPUkXhXTp13xJgujXDHC1wgnZPJSTFnXyoLFVeFWNuy86HZ1AQ iat-mode=0 obfs4 172.82.152.48:40321 58A092F9E37CA215D0DDD74BD8D17490D9D5FA08 cert=u2x/qTecNkWpiuGBtnqJxmC9C+Wmgq/XvATFz1joZ3RNfH/gj+nqSFkVuVQkwU+SXncpbg iat-mode=0 obfs4 38.229.33.147:56251 D6B9B3D27EF5D4B1D78D31C97FBE37B29B2ED32C cert=DVVz5OyOYnJCq6FIDs4bE3umc/7yNJbF3IkCNeP5WDXQ8dGbCT3wlJFTC9y4KPeGTc7NYw iat-mode=1
which I have directly copied over into orbot from my gmail, the log is like as follows below
![0](https://user-images.githubusercontent.com/20277028/48227332-40c56a00-e3b7-11e8-85ce-8cd839754c45.png)
![1](https://user-images.githubusercontent.com/20277028/48227326-373c0200-e3b7-11e8-8272-fb0879d9482a.jpg)
could I ask you please try it out on your device too? ah, and for the record I am on orbot 16.0.2-rc-1

**Comment by bitmold** [comment]
Closing because this ticket is inactive and seems like a duplicate of #289
