### ISSUE TITLE
Orbot crashes

### ISSUE THREAD

**Issue by guest652** [guardianproject/orbot#180]
There is a problem with Orbot on Android 5.1.1. When I try to backup hidden service application stops and it is impossible to save private keys. Can you fix this? The same version works well on newer Android (7.0). I tried older Orbot version and it does not work too, archive with keys is not saved (Android 5.1.1). My current version of Orbot is 16.0.5-RC-1. It would be good to have an opportunity to add private keys in Orbot settings to avoid such problem in the future.

**Comment by bitmold** [comment]
I believe this crash was fixed earlier this year, but I'll test on a 5.1.1 just to be safe.............

**Comment by bitmold** [comment]
This is crashing on API 29. This is like due to the 29+ introduction of [scoped storage](https://developer.android.com/training/data-storage#scoped-storage). Reworking this now...
