### ISSUE TITLE
How Debug Logs? [Need Help LineageOS]

### ISSUE THREAD

**Issue by hasanalizxc** [guardianproject/orbot#183]
Dear Orbot Family,

Hope you are fine. I am using LineageOS 7.1 and installed Orbot. I need to use with bridges and wrote them to bridge field. When i started, it stucks at "Starting". I need to view logs but i don't know how can i do. Then i searched some and found i have to enable Debug Logs and enabled. I saw there is a message "must use with adb or Logcat". I really don't know how can i use these. Also my phone is rooted.

Could you please help me about this issue?

Thanks in advance..

**Comment by bitmold** [comment]
Closing because this account is deleted although here is some documentation on using Logcat https://developer.android.com/studio/debug/am-logcat
