### ISSUE TITLE
startForeground crash

### ISSUE THREAD

**Issue by n8fr8** [guardianproject/orbot#184]
This is causing a large amount of crashes

Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{6c2304c u0 org.torproject.android/.service.TorService}

(no location available)

**Comment by n8fr8** [comment]
Fixed by 2c59c8489bc6302f2417448d8fad519b3c0a423b

**Comment by bitmold** [comment]
I think this can be closed
