### ISSUE TITLE
Ensure that system is unhooked from Orbot once Orbot is turned off

### ISSUE THREAD

**Issue by leafcutterant** [guardianproject/orbot#187]
Follow-up to my previous issue #186:

I propose ensuring that if VPN mode *is* enabled for the system, make sure the system is unhooked from Orbot once Orbot is turned off. (This can be checked in the system VPN settings. In my experience, The system was still hooked into Orbot after its shutdown, resulting in not being able to connect to he internet.)

**Comment by bitmold** [comment]
This was fixed in release 16.3 https://github.com/guardianproject/orbot/releases/tag/16.3.0-RC-1-tor-0.4.2.7
