### ISSUE TITLE
Integrate Firewall's all features and functions from 'Netguard'

### ISSUE THREAD

**Issue by DI555** [guardianproject/orbot#191]
Please, Integrate Firewall's all features and functions from 'Netguard'! 
f-droid.org/packages/eu.faircode.netguard/

The goals:
1. We get the list of all appps, even system apps , even hidden ones !!!
2. Full controll of all apps on device!
3. Due to unpossibility to have more than one vpn/firewall app on android , implementing Netguard's features would be the best choice!

**Comment by corkia1** [comment]
Orbot's VPN mode isn't trustwhorthy because you can't be sure Orbot is blocking `system` apps (it doesn't let user to decide)

NetGuard + orbot is still the answer.

**Comment by bitmold** [comment]
Closing because duplicate of #312
 
I intend to implement this feature in the not too distant future
