### ISSUE TITLE
System shows I'm connected to Orbot even when I'm not

### ISSUE THREAD

**Issue by leafcutterant** [guardianproject/orbot#193]
Even after I turn off Orbot and exit it,

* I have the key icon in the statusbar,
* the pull-down tiles still have a line saying "Device connected to Orbot",
* the VPN setting says "Connected" under the Orbot item.

The notification should disappear and the VPN status should disconnect once I deliberately disconnect from Tor.

**Comment by bitmold** [comment]
Hi, sorry to take so long to get back to you ~ this issue has been fixed in version 16.3 - please reopen it if you are still experiencing this problem: https://github.com/guardianproject/orbot/releases/tag/16.3.0-RC-1-tor-0.4.2.7
