### ISSUE TITLE
Connect Problem

### ISSUE THREAD

**Issue by minutesinch** [guardianproject/orbot#195]
Hi
I have a problem with Tor, When First Time I was Setup Tor Without change anything(just add 127.0.0.1:9050 In Telegram proxies) and Turn Orbot On Next Time  Opening Orbot, dosent connect any more , i tried close and open agian and clear cache but dont work.

When i Clear Data of Orbot, Working Well and this problem happend every time i use Orbot.

Please fix it.

**Comment by n8fr8** [comment]
Have you tried using the Orbot VPN feature to select Telegram instead of setting the proxy?

**Comment by abdolfazel** [comment]
Go-to orbot settings then check Open Proxy on All Interfaces

**Comment by n8fr8** [comment]
New release: https://github.com/guardianproject/orbot/releases/tag/16.2.0-RC-1-tor-0.4.2.7
