### ISSUE TITLE
VPN mode not working

### ISSUE THREAD

**Issue by ingfabby** [guardianproject/orbot#205]
Unable to activate the VPN mode on devices running Oreo (8.1)

**Comment by n8fr8** [comment]
On Mon, Apr 15, 2019, at 7:24 PM, ingfabby wrote:
> Unable to activate the VPN mode on devices running Oreo (8.1)
> 

Can we get more detail on which kind of device and which version of Orbot?

VPN mode does work on our 8.1 testing devices.

Also, what does "not working" mean? Crashes when activated? Apps cant connect?

**Comment by ingfabby** [comment]
It fails to stay active and the device is a bq Aquaris X Pro.

**Comment by opnsrcr** [comment]
Not sure what @ingfabby means by "stay active" but in my case VPN Mode seems to not work at all. 

I select apps in `Tor-Enabled Apps` area and slide `VPN Mode` on. Upon checking if the IP of a browser (Klar, Chromium, etc...) is being torified the result is: NO. However, VPN *seems* to be running- I see the VPN icon in the topbar and under `Network & Internet -> VPN` options looks fine. I am using the following 

- Fairphone 2
- Lineage OS: 15.1
- Android: 8.1.0
- Orbot: 16.0.5-RC-2-tor-0.3.4.9

These are the exact steps I take which works fine with the same version of Orbot on a different device with Android 7.1.2. A bit confounded here.

**Comment by RealWalrus** [comment]
I am having the same problem.
I am using a Fairphone 2 just as @opnsrcr but i am running Lineage 16.0.
I have tried multiple versions of orbot and none seem to work; the only thing i was actually able to accomplish was to correctly run the VPN mode inside a work profile (normally it would just give up the connection after 120 seconds)and that's it. Even tho all the applications (inside the work profile) seem to be filtred through the VPN i am unable to mask my IP address.
I first thought it was a problem with the VPN config in LOS but other VPNs work flawlessly so i have no idea what is happening.

Please check it out.

**Comment by n8fr8** [comment]
New release: https://github.com/guardianproject/orbot/releases/tag/16.2.0-RC-1-tor-0.4.2.7
