### ISSUE TITLE
Orbot Crash When Change Langauge 

### ISSUE THREAD

**Issue by minutesinch** [guardianproject/orbot#207]
Hi
When i change language to Persian(Farsi) or another language tor start but when i try to go setting orbot crash i grab logcat maybe help.

 

Tor Language Exception
{
04-18 16:26:17.291 E/ActivityManager(19366): applyOptionsLocked: Unknown animationType=0
04-18 16:26:18.144 E/RecentsImpl(20145): Launching home request but recents is not visible
04-18 16:26:18.184 E/SemDvfsHintManager(19366):  mHintTimeout : 500
04-18 16:26:20.359 E/epmd    (237): Only canonical path can be handled..
04-18 16:26:20.361 E/epmd    (237): Only canonical path can be handled..
04-18 16:26:21.048 E/ActivityManager(19366): applyOptionsLocked: pendingOptions.getStartX()=88pendingOptions.getStartY()=672
04-18 16:26:21.397 E/Zygote  (2485): v2
04-18 16:26:21.402 E/Zygote  (2485): accessInfo : 0
04-18 16:26:28.402 E/AndroidRuntime(2485): FATAL EXCEPTION: main
04-18 16:26:28.402 E/AndroidRuntime(2485): Process: org.torproject.android, PID: 2485
04-18 16:26:28.402 E/AndroidRuntime(2485): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.torproject.android/org.torproject.android.settings.SettingsPreferences}: android.view.InflateException: Binary XML file line #5: Error inflating class im.delight.android.languages.LanguagePreference
04-18 16:26:28.402 E/AndroidRuntime(2485): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)
04-18 16:26:28.402 E/AndroidRuntime(2485): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
04-18 16:26:28.402 E/AndroidRuntime(2485): 	at android.app.ActivityThread.-wrap14(ActivityThread.java)
04-18 16:26:28.402 E/AndroidRuntime(2485): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
04-18 16:26:28.402 E/AndroidRuntime(2485): 	at android.os.Handler.dispatchMessage(Handler.java)
04-18 16:26:28.402 E/AndroidRuntime(2485): 	at android.os.Looper.loop(Looper.java)
04-18 16:26:28.402 E/AndroidRuntime(2485): 	at android.app.ActivityThread.main(ActivityThread.java)
04-18 16:26:28.402 E/AndroidRuntime(2485): 	at java.lang.reflect.Method.invoke(Native Method)
04-18 16:26:28.402 E/AndroidRuntime(2485): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
04-18 16:26:28.402 E/AndroidRuntime(2485): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
04-18 16:26:28.402 E/AndroidRuntime(2485): Caused by: android.view.InflateException: Binary XML file line #5: Error inflating class im.delight.android.languages.LanguagePreference
04-18 16:26:28.402 E/AndroidRuntime(2485): 	at android.preference.GenericInflater.createItemFromTag(GenericInflater.java)
04-18 16:26:28.402 E/AndroidRuntime(2485): 	at android.preference.GenericInflater.rInflate(GenericInflater.java)
04-18 16:26:28.402 E/AndroidRuntime(2485): 	at android.preference.GenericInflater.rInflate(GenericInflater.java)
04-18 16:26:28.402 E/AndroidRuntime(2485): 	at android.preference.GenericInflater.inflate(GenericInflater.java)
04-18 16:26:28.402 E/AndroidRuntime(2485): 	at android.preference.GenericInflater.inflate(GenericInflater.java)
04-18 16:26:28.402 E/AndroidRuntime(2485): 	at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java)
04-18 16:26:28.402 E/AndroidRuntime(2485): 	at android.preference.PreferenceActivity.addPreferencesFromResource(PreferenceActivity.java)
04-18 16:26:28.402 E/AndroidRuntime(2485): 	at org.torproject.android.settings.SettingsPreferences.onCreate(SettingsPreferences.java:27)
04-18 16:26:28.402 E/AndroidRuntime(2485): 	at android.app.Activity.performCreate(Activity.java)
04-18 16:26:28.402 E/AndroidRuntime(2485): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java)
04-18 16:26:28.402 E/AndroidRuntime(2485): 	... 10 more
04-18 16:26:28.402 E/AndroidRuntime(2485): Caused by: java.lang.ClassNotFoundException: Didn't find class "im.delight.android.languages.LanguagePreference" on path: DexPathList[[zip file "/data/app/org.torproject.android-2/base.apk"],nativeLibraryDirectories=[/data/app/org.torproject.android-2/lib/arm, /data/app/org.torproject.android-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
04-18 16:26:28.402 E/AndroidRuntime(2485): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
04-18 16:26:28.402 E/AndroidRuntime(2485): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
04-18 16:26:28.402 E/AndroidRuntime(2485): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
04-18 16:26:28.402 E/AndroidRuntime(2485): 	at android.preference.GenericInflater.createItem(GenericInflater.java)
04-18 16:26:28.402 E/AndroidRuntime(2485): 	... 20 more
04-18 16:26:28.460 E/SemDvfsHintManager(19366):  mHintTimeout : 500
04-18 16:26:30.014 E/ActivityManager(19366): applyOptionsLocked: Unknown animationType=0
04-18 16:26:30.079 E/ViewRootImpl(19366): sendUserActionEvent() returned.
04-18 16:26:30.101 E/Zygote  (2730): v2
04-18 16:26:30.229 E/Zygote  (2730): accessInfo : 0
04-18 16:26:32.740 E/AndroidRuntime(2730): FATAL EXCEPTION: main
04-18 16:26:32.740 E/AndroidRuntime(2730): Process: org.torproject.android, PID: 2730
04-18 16:26:32.740 E/AndroidRuntime(2730): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.torproject.android/org.torproject.android.settings.SettingsPreferences}: android.view.InflateException: Binary XML file line #5: Error inflating class im.delight.android.languages.LanguagePreference
04-18 16:26:32.740 E/AndroidRuntime(2730): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)
04-18 16:26:32.740 E/AndroidRuntime(2730): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
04-18 16:26:32.740 E/AndroidRuntime(2730): 	at android.app.ActivityThread.-wrap14(ActivityThread.java)
04-18 16:26:32.740 E/AndroidRuntime(2730): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
04-18 16:26:32.740 E/AndroidRuntime(2730): 	at android.os.Handler.dispatchMessage(Handler.java)
04-18 16:26:32.740 E/AndroidRuntime(2730): 	at android.os.Looper.loop(Looper.java)
04-18 16:26:32.740 E/AndroidRuntime(2730): 	at android.app.ActivityThread.main(ActivityThread.java)
04-18 16:26:32.740 E/AndroidRuntime(2730): 	at java.lang.reflect.Method.invoke(Native Method)
04-18 16:26:32.740 E/AndroidRuntime(2730): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
04-18 16:26:32.740 E/AndroidRuntime(2730): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
04-18 16:26:32.740 E/AndroidRuntime(2730): Caused by: android.view.InflateException: Binary XML file line #5: Error inflating class im.delight.android.languages.LanguagePreference
04-18 16:26:32.740 E/AndroidRuntime(2730): 	at android.preference.GenericInflater.createItemFromTag(GenericInflater.java)
04-18 16:26:32.740 E/AndroidRuntime(2730): 	at android.preference.GenericInflater.rInflate(GenericInflater.java)
04-18 16:26:32.740 E/AndroidRuntime(2730): 	at android.preference.GenericInflater.rInflate(GenericInflater.java)
04-18 16:26:32.740 E/AndroidRuntime(2730): 	at android.preference.GenericInflater.inflate(GenericInflater.java)
04-18 16:26:32.740 E/AndroidRuntime(2730): 	at android.preference.GenericInflater.inflate(GenericInflater.java)
04-18 16:26:32.740 E/AndroidRuntime(2730): 	at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java)
04-18 16:26:32.740 E/AndroidRuntime(2730): 	at android.preference.PreferenceActivity.addPreferencesFromResource(PreferenceActivity.java)
04-18 16:26:32.740 E/AndroidRuntime(2730): 	at org.torproject.android.settings.SettingsPreferences.onCreate(SettingsPreferences.java:27)
04-18 16:26:32.740 E/AndroidRuntime(2730): 	at android.app.Activity.performCreate(Activity.java)
04-18 16:26:32.740 E/AndroidRuntime(2730): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java)
04-18 16:26:32.740 E/AndroidRuntime(2730): 	... 10 more
04-18 16:26:32.740 E/AndroidRuntime(2730): Caused by: java.lang.ClassNotFoundException: Didn't find class "im.delight.android.languages.LanguagePreference" on path: DexPathList[[zip file "/data/app/org.torproject.android-2/base.apk"],nativeLibraryDirectories=[/data/app/org.torproject.android-2/lib/arm, /data/app/org.torproject.android-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
04-18 16:26:32.740 E/AndroidRuntime(2730): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
04-18 16:26:32.740 E/AndroidRuntime(2730): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
04-18 16:26:32.740 E/AndroidRuntime(2730): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
04-18 16:26:32.740 E/AndroidRuntime(2730): 	at android.preference.GenericInflater.createItem(GenericInflater.java)
04-18 16:26:32.740 E/AndroidRuntime(2730): 	... 20 more
04-18 16:26:32.802 E/SemDvfsHintManager(19366):  mHintTimeout : 500
04-18 16:26:34.017 E/ViewRootImpl(19366): sendUserActionEvent() returned.
04-18 16:26:36.239 E/ActivityManager(19366): applyOptionsLocked: Unknown animationType=0
04-18 16:26:36.612 E/Watchdog(19366): !@Sync 32 [2019-04-18 16:26:36.611]
04-18 16:26:50.604 E/SKBD    (22575): wj isKeyboardLayoutOrCustomSymbolActivity: privateImeOptions is null
04-18 16:26:50.994 E/SKBD    (22575): [IIManager] IIfo InputConnection is slow! type : 2 tookTime : 240
04-18 16:26:51.094 E/SKBD    (22575): xh localeIndex is  -1
04-18 16:26:51.244 E/SKBD    (22575): ahi setCurrentInputModule mCurrentInputModule index: 10
04-18 16:26:51.339 E/SKBD    (22575): ahi setCurrentInputModule mCurrentInputModule index: 10
04-18 16:26:51.407 E/SKBD    (22575): ahi setCurrentInputModule mCurrentInputModule index: 10
04-18 16:26:51.677 E/EventStateReceiver(24205): mIsOpenIME:false  isOpenIME:true
04-18 16:26:51.697 E/AirMessagePosHelper(24205): mImeService is not binded!!
04-18 16:26:51.799 E/Zygote  (2788): v2
04-18 16:26:51.802 E/Zygote  (2788): accessInfo : 0
04-18 16:26:52.047 E/ContactsProvider_EventLog(22080): Flush buffer to file cnt : 1 size : 1Kb duration : 27ms lastUpdatedAfter : 60172 ms mFlush_time_threasold : 2000 mCurrentSize : 568
04-18 16:26:52.218 E/SKBD    (22575): [IIManager] IIfo InputConnection is slow! type : 1 tookTime : 201
04-18 16:26:52.263 E/ProxyStatusReceiver(2788): no this type!
04-18 16:26:53.843 E/SKBD    (22575): XT9Engine ET9KDB_TouchCancel : 104
04-18 16:26:53.938 E/SKBD    (22575): AbstractKeyboardView Dismiss keyPreviewView is null

}

**Comment by jahmadiiiii** [comment]
J510FN
Android 7.1.1

**Comment by bitmold** [comment]
@jahmadiiiii I'm looking into this crash right now as a part of #106 

This appears to be a crash specifically with Farsi and not other languages.

**Comment by bitmold** [comment]
the merged #223 closes this issue

**Comment by n8fr8** [comment]
https://github.com/guardianproject/orbot/releases/tag/16.1.2-RC-2-tor-0.4.1.5-rc
