### ISSUE TITLE
Orbot does not stop

### ISSUE THREAD

**Issue by ingfabby** [guardianproject/orbot#208]
Device Huawei nova 3i device
Android 9
Orbot still running event when I push the stop button on the background and cannot access to any website

**Comment by SkewedZeppelin** [comment]
Yes, the foreground notification seems to never go away. Running or not.
Was introduced in 2c59c8489bc6302f2417448d8fad519b3c0a423b ?

**Comment by n8fr8** [comment]
Possibly. There is the "Exit" option in the menu. Does that work?

**Comment by SkewedZeppelin** [comment]
Yes, hitting "Exit" does remove the notification. Until the system decides to start the service again.

**Comment by n8fr8** [comment]
New release: https://github.com/guardianproject/orbot/releases/tag/16.2.0-RC-1-tor-0.4.2.7

**Comment by SkewedZeppelin** [comment]
I actually recently noticed severe battery drain,
Testing on 16.2.0-RC-1
Orbot constantly spins at full load on one CPU core when Tor is not running and Orbot is in foreground, and 10% when in background.
Just `adb shell` and run top and you'll see it easy.

**Comment by n8fr8** [comment]
If you force stop the app, and then open it in a tor-off state, does this occur?

Or is it only after you start/stop, etc?

Is this when the VPN is activated?

**Comment by SkewedZeppelin** [comment]
Force stop
Clear app data
Open Orbot
Don't start Tor
Check top
See very high usage

**Comment by n8fr8** [comment]
Hmm.... there is no code running at that point. No idea why that would be. Will look into though!

**Comment by bitmold** [comment]
Notably `OrbotService` does a lot of configuration work when you open `OrbotMainActivity` and don't start tor. So there is at least that bootstrapping code running at that point, and it's possible that it launches some task that keeps running in the background.
