### ISSUE TITLE
two build listings in F-Droid?

### ISSUE THREAD

**Issue by opnsrcr** [guardianproject/orbot#215]
There seems to be *two* build listings in F-Droid / Guardian repo at present for the current build of Orbot. One supports architectures `armeabi, areabi-v7a, x86` while one is just `armeabi` is this a mistake or some sort?

<img src="https://user-images.githubusercontent.com/50571473/57606735-cba33f00-7569-11e9-83db-dc61db0e7b20.png" width="375">

And it seems that both end up being installed no matter which one is clicked `UPDATE`

**Comment by eighthave** [comment]
This seems to have resolved itself somehow, I don't know what caused the issue.
