### ISSUE TITLE
Execution failed for task ':orbotservice:mergeDebugJniLibFolders'.

### ISSUE THREAD

**Issue by mohtasham1988** [guardianproject/orbot#217]
Hi 
I Have Problem when I want to build project

_Execution failed for task ':orbotservice:mergeDebugJniLibFolders'._

**Comment by LongBuiDuc** [comment]
i too, i build on Windows, how can i fix it?

**Comment by n8fr8** [comment]
Not sure. Perhaps some idea here? https://stackoverflow.com/questions/54450398/how-to-fix-gradle-task-appmergedebugjnilibfolders-in-flutter-gradle-build-fo

**Comment by bitmold** [comment]
Closing this because #246 has been merged. In general we ought to update the BUILD file and can specify instructions for Linux/Windows/macOS as needed
