### ISSUE TITLE
Port 8091 reported open by port scanners

### ISSUE THREAD

**Issue by neremin** [guardianproject/orbot#220]
Orbot 16.0.5-RC-2-tor-0.3.4.9 with default configuration replies to port scanners on port 8091, which is PDSND's UDP port. This is not intended behaviour according to /data/data/org.torproject.android/app_bin/pdnsd.conf:

`global { perm_cache=0; cache_dir=/data/data/org.torproject.android/app_bin; server_port = 8091; server_ip = 0.0.0.0; query_method=udp_only; min_ttl=15m; max_ttl=1w; timeout=10; daemon=on; pid_file=/data/data/org.torproject.android/app_bin/pdnsd.pid; } server { label= upstream; ip = 127.0.0.1; port = 5400; uptest = none; } rr { name=localhost; reverse=on; a=127.0.0.1; owner=localhost; soa=localhost,root.localhost,42,86400,900,86400,86400; }`

**Comment by n8fr8** [comment]
Ii think because we bind to 0.0.0.0 this happens. However, it was meant to be only within the virtual VPN lan.

Is the scanner running on the device, or an external scanner?

**Comment by neremin** [comment]
It's an external scanner

**Comment by neremin** [comment]
Well, I tried to change 0.0.0.0 to 127.0.0.1 in pdnsd.conf, but orbot keeps reverting pdnsd.conf to it's original state during orbot VPN startup. So, it should be changed in the source code. Could you please make relevant changes to appear in the next build, as you seem to be one who updated related files recently?

**Comment by n8fr8** [comment]
fixed this here 9e54cd6e79fd8ed573f0871b9ecf2d16a7ce855c 
will be in next beta this week

**Comment by n8fr8** [comment]
https://github.com/guardianproject/orbot/commit/9e54cd6e79fd8ed573f0871b9ecf2d16a7ce855c

**Comment by neremin** [comment]
I just wonder, why you used 192.168.200.1 server IP instead of 127.0.0.1? Are the user apps forced to be connected to Orbot VPN to access this service? If so, it doesn't make any sense. Not every app in the system might need to access it, but for most of them would be nice to protect DNS queries from spoofing. May be it worth to change the address to 127.0.0.1 in this case?

**Comment by n8fr8** [comment]
PDNSD is only started and used for the VPN service. Otherwise, apps can access Tor's local DNS port.
