### ISSUE TITLE
orbot fails to bootstrap if switching from bridge to direct connection by swipping 'use bridges' button

### ISSUE THREAD

**Issue by muke101** [guardianproject/orbot#229]
I find if I connect to Tor with a bridge and then later swipe off the 'use bridges' button, upon restarting Tor the logs will say it can't parse the torrc file. If I go into the bridge settings and select a direct connect, then it will work fine, but surely disabling the 'use bridges' button should automatically set orbot to directly connect anyway. Low priority but would be helpful.

**Comment by bitmold** [comment]
Hi thanks for reporting this I'm gonna look into it tmrw:+)
