### ISSUE TITLE
No Working

### ISSUE THREAD

**Issue by minutesinch** [guardianproject/orbot#230]
Hi
Today i use Orbot but not connect any more, i tested with all bridge most of them not work and when "Tor Cloud bridge " Worked and after reached to 100% but there is no connection, also unlisted bridge have same issue and not connecting in IRAN and Stuck in 5%!
Last Months Orbot worked well!

I use Orbot 16.0.5-RC-2-tor-0.3.4.9
ISP: Iran Telecommunication Company PJS

See this log: 

- NOTICE: Bootstrapped 5%: Connecting to directory server 
- Starting Tor client… complete.
- WARN: Problem bootstrapping. Stuck at 5%: Connecting to directory server. (Connection refused; CONNECTREFUSED; count 10; recommendation warn; host 847B1F850344D7876491A54892F904934E4EB85D at 86.59.21.38:443)

**Comment by n8fr8** [comment]
This should fix the issue: https://github.com/guardianproject/orbot/releases/tag/16.1.2-RC-2-tor-0.4.1.5-rc

You may need to get custom bridges at https://bridges.torproject.org
