### ISSUE TITLE
Orbot RC VPN functionality not working

### ISSUE THREAD

**Issue by woshee** [guardianproject/orbot#235]
Hi I installed the latest RC 0.4.0.4 an the VPN functionality is not working for the selected apps. They are not able to connect. Other apps that can be configured to use Orbot don't have issues. I'm on Android 7.

**Comment by n1m1** [comment]
Hi,
same behavior here. The last Orbot BETA (16.1.0-BETA-5-tor-0.4.0.4-rc) is not working in VPN mode. I am on Android 9.

Cheers.

**Comment by n1m1** [comment]
Hi,
just to tell you that with the last RC (16.1 RC 1) the VPN mode seems to work fine. Thanks for the bug fixes and the improvements.

**Comment by n8fr8** [comment]
Great, and another RC2 is out now: https://github.com/guardianproject/orbot/releases/tag/16.1.2-RC-2-tor-0.4.1.5-rc
