### ISSUE TITLE
Upgrade to Gradle 5.x

### ISSUE THREAD

**Issue by sisbell** [guardianproject/orbot#237]
I'm unable to build with later versions of the JDK.  I get the following error

`Could not determine java version from '13'.`

I looks like we need to upgrade gradle version to 5.x for JDK versions 11+.

**Comment by eighthave** [comment]
FYI, an alternate way to solve this, which lets you use older gradle versions, is to set `JAVA_HOME` to the one included in Android Studio, which is still Java8, e.g.
```console
$ export JAVA_HOME=/opt/android-studio-3.3/jre
```
