### ISSUE TITLE
PDNSDInstaller is Not Needed

### ISSUE THREAD

**Issue by sisbell** [guardianproject/orbot#239]
We don't need an installer for the pdnsd library..

If we name If we build pdnsd as a shared library, it will automatically install on app installation. Modify the Android.mk file for the module:

include $(BUILD_SHARED_LIBRARY)

This generates libpdnsd.so

We can then get reference to file with

<pre>
File nativeDir = new File(service.getApplicationInfo().nativeLibraryDir);
filePdnsd = new File(nativeDir, "libpdnsd.so");
</pre>

Note: This same approach can be used for the tor.so library, eliminating the need for an installer.

**Comment by n8fr8** [comment]
Yup, this is what we do for the tor and PT binaries now. Just need to make the conversion for the other libraries.

If we build it as a shared library though, will it still be executable as a main() ? What I ultimately want to move to is proper execution as shared libraries, in the same process, such as what we do with Tor on iOS.

**Comment by n8fr8** [comment]
(The other solution here is to not use PDNSD at all anymore, and figure out why we can't just directly DNS resolution against the Tor DNS port for the VPN service)
