### ISSUE TITLE
could not bind to port  15.1rc1

### ISSUE THREAD

**Issue by c3ph3us** [guardianproject/orbot#24]
01-20 06:47:47.242 2611-2848/? D/Orbot: torrc.custom=ControlPortWriteToFile /data/data/org.torproject.android/app_bin/control.txt
                                        SOCKSPort 9050
                                        SafeSocks 0
                                        TestSocks 0
                                        WarnUnsafeSocks 1
                                        DisableNetwork 0
                                        Log debug syslog
                                        Log info syslog
                                        SafeLogging 0
                                        UseBridges 0
                                        GeoIPFile /data/data/org.torproject.android/app_bin/geoip
                                        GeoIPv6File /data/data/org.torproject.android/app_bin/geoip6
                                        EntryNodes {GB}{DE}
                                        ExitNodes {NL}
                                        StrictNodes 1
...
01-20 06:47:49.676 2611-2848/? D/Orbot: Tor (1): Jan 20 06:47:49.662 [notice] Tor v0.2.7.6 running on Linux with Libevent 2.0.22-stable, OpenSSL 1.0.1q and Zlib 1.2.8.
                                        Jan 20 06:47:49.662 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
                                        Jan 20 06:47:49.663 [notice] Read configuration file "/data/data/org.torproject.android/app_bin/torrc".
                                        Jan 20 06:47:49.663 [notice] Read configuration file "/data/data/org.torproject.android/app_bin/torrc.custom".
                                        Jan 20 06:47:49.673 [notice] Opening Socks listener on 127.0.0.1:9050
                                        Jan 20 06:47:49.673 [warn] Could not bind to 127.0.0.1:9050: Address already in use. Is Tor already running?
                                        Jan 20 06:47:49.673 [notice] Opening Control listener on 127.0.0.1:0
                                        Jan 20 06:47:49.673 [notice] Control listener listening on port 54035.
                                        Jan 20 06:47:49.673 [notice] Closing partially-constructed Control listener on 127.0.0.1:54035
                                        Jan 20 06:47:49.673 [warn] Failed to parse/validate config: Failed to bind one of the listener ports.
                                        Jan 20 06:47:49.674 [err] Reading config failed--see warnings above.

**Comment by n8fr8** [comment]
Is this on a Samsung device?

**Comment by c3ph3us** [comment]
hltexx on CM 13
