### ISSUE TITLE
Last release does not start

### ISSUE THREAD

**Issue by ingfabby** [guardianproject/orbot#243]
From GP support email:

Hello. The problem is the following: newest version of Orbot doesn't start
on my devices (both Android 8 and Android 4.3) at all! I use Orbot with
obfs4 proxy. Here is my log. Please correct this fail in future Orbot
releases! I cannot even start Orbot!
 Only old version (Orbot 16.0.5 tor 0.3.4.9)
working well.

**Comment by n8fr8** [comment]
This release should fix it: https://github.com/guardianproject/orbot/releases/tag/16.1.2-RC-2-tor-0.4.1.5-rc
