### ISSUE TITLE
Proxy is no longer working

### ISSUE THREAD

**Issue by ingfabby** [guardianproject/orbot#245]
From a user to the GP Support email:
" Lately it seems transparent proxification does not work.

My laptop on Linux Mint the latest version does not connect to the Internet, I can not bypass the operator’s restrictions on connecting other devices.

Previously, everything worked fine, but now the connected devices do not connect to the Internet through a proxy."

**Comment by n8fr8** [comment]
Transparent proxying hasn't been support on Orbot for years now. It requires root access, which we removed.

Also, not sure what their laptop has to do with Orbot on their Android device? Are they trying to use the hotspot with the Orbot VPN mode? That also doesn't work. They should instead run Tor Browser on their Linux Mint laptop.

**Comment by ingfabby** [comment]
I'll let him know.  Thanks
