### ISSUE TITLE
Orbot Max and Orbot Mini Have Identical VPNEnableActivity

### ISSUE THREAD

**Issue by bitmold** [guardianproject/orbot#253]
Instead of two separate but identical classes (100% identical, in fact) this Activity and others like it should be stored in a centralized place for both apps such that if it is modified for one app the changes are reflected in the other (if there is a need to have two separate implementations I'm sure we could create a base class or something and reuse most of the code)

**Comment by n8fr8** [comment]
Yeah not sure yet, and still figuring it out. That is why I kept both apps in one repo for now, while we figure out what is shared, and what diverges. Thoughts are welcome!
