### ISSUE TITLE
Default obfs4 bridges are offline

### ISSUE THREAD

**Issue by NullHypothesis** [guardianproject/orbot#258]
All obfs4 bridges in the following two files are offline as of June 12 2019:

* orbotservice/src/main/res/raw-fa/bridges.txt
* orbotservice/src/main/res/raw/bridges.txt 

I hear that in the long run, Orbot will use tor-android-service, which includes our up-to-date default bridges, but in the short run we should make sure that these bridges are kept in sync with our default bridges.

(This ticket was originally filed in Tor's bug tracker: https://bugs.torproject.org/30870)

**Comment by n8fr8** [comment]
Thanks, yeah, the plan was to use different bridges than what is shipped in TB and TBA. So, may need to request a separate private set of high capacity bridges for those in the know.

The raw-fa bridges in particular were given to us as "bridges for use for Iran" so disappointing they are offline. Was that a decision that was made?

**Comment by mpalmer** [comment]
I attempted to provide a set of obfs4 bridges to Orbot, however I'm not getting any response from @n8fr8 to the questions I need answered in order to set them up.

**Comment by n8fr8** [comment]
@mpalmer apologies. was on the road and occupied with a project launch. back at the inbox today!

**Comment by minutesinch** [comment]
> Thanks, yeah, the plan was to use different bridges than what is shipped in TB and TBA. So, may need to request a separate private set of high capacity bridges for those in the know.
> 
> The raw-fa bridges in particular were given to us as "bridges for use for Iran" so disappointing they are offline. Was that a decision that was made?

not only iran but affect china too

**Comment by n8fr8** [comment]
Latest release now has integrated bridge request functionality, just like in Tor Browser on the desktop and Onion Browser on iOS. Please give it a try!

New release: https://github.com/guardianproject/orbot/releases/tag/16.2.0-RC-1-tor-0.4.2.7

**Comment by xhdix** [comment]
Android 8.1
Mobile data: MCI (Mobile Telecommunication Company of Iran)
ADSL: TCI (Telecommunication Company of Iran) 


After a successful and temporary complete connection to MCI :
![image](https://user-images.githubusercontent.com/12384263/81450524-473ec880-918b-11ea-8f24-24b9248f942f.png)
In TCI, it was blocked from the beginning.

The Request bridge doesn't work in MCI, but it's good in TCI.
![image](https://user-images.githubusercontent.com/12384263/81451006-3a6ea480-918c-11ea-8b03-282c33178008.png)

Cloud servers sometimes work in MCI, but are good in TCI.
![image](https://user-images.githubusercontent.com/12384263/81451441-2f684400-918d-11ea-9c06-495fe2ec5666.png)

**Comment by xhdix** [comment]
Successful test in:
Mobile data: MCI (Mobile Telecommunication Company of Iran)
ADSL: TCI (Telecommunication Company of Iran)

![image](https://user-images.githubusercontent.com/12384263/92932714-f1866f80-f44d-11ea-80a0-2a551cfc2509.png)

![image](https://user-images.githubusercontent.com/12384263/92932533-b4ba7880-f44d-11ea-9702-17f71763d7a1.png)

![image](https://user-images.githubusercontent.com/12384263/92933753-52fb0e00-f44f-11ea-9b43-bb0da8add3ba.png)

![image](https://user-images.githubusercontent.com/12384263/92933575-1202f980-f44f-11ea-9911-506199816b8c.png)

![image](https://user-images.githubusercontent.com/12384263/92933596-19c29e00-f44f-11ea-96ee-e037e8dfff04.png)

Of course, the Tor blocking situation in Iran has changed a bit again.
https://metrics.torproject.org/userstats-relay-country.html?start=2020-01-13&end=2020-09-11&country=ir&events=off

I think this problem has been fixed properly. Thank you all very much! <3

**Comment by n8fr8** [comment]
Fantastic. Glad to see the MOAT feature working.
