### ISSUE TITLE
Orbot notification no longer shows upload and download

### ISSUE THREAD

**Issue by jhoc2000** [guardianproject/orbot#260]
I just upgraded to version 16.1.2-RC-2-tor-0.4.1.5-rc and the upload and download speeds are no longer shown in the notification. I have relied on this to see if Orbot is actually connecting to the network.

Could you please add this to the notification. The exit node would be nice as well. This was in the notification but disappeared some versions ago.

**Comment by n8fr8** [comment]
This was intentional as it was causing some instability in the app, as well as creating too much traffic to the back end services that torproject hosts to give info about the circuit and nodes.

We are looking into how we can reimplement aspects of it in a smarter way, and will keep you posted!

**Comment by jhoc2000** [comment]
I currently feel that Orbot is very unstable. I keep getting different messages such as, inactivity for so many seconds connections cut. 

I rely on the notification to see if Orbot is running and the easiest way to do that is to look at the the notifications to see if there was any upload and download traffic. Otherwise the notification is mostly useless because it shows old information.

I look forward to this issue being resolved.
