### ISSUE TITLE
Orbot fails to connect

### ISSUE THREAD

**Issue by jw243** [guardianproject/orbot#261]
On my device (Moto X4 running LineageOs 16) Orbot fails to connect. After a fresh install of Orbot, it works, but after a reboot of the phone, it does not connect anymore. It always hangs at the same point, see screenshot. This applies to Orbot 16.1.1 & 16.1.2.

![Screenshot_20190916-233358_Orbot 1](https://user-images.githubusercontent.com/13139555/64995271-0d0e7700-d8db-11e9-9973-b17c166d5afd.png)

**Comment by n8fr8** [comment]
Are you using Bridges? If so, custom ones or the built-in options?

**Comment by n8fr8** [comment]
Also, make sure to do a clean install of the latest 16.1.2 RC2: https://github.com/guardianproject/orbot/releases/tag/16.1.2-RC-2-tor-0.4.1.5-rc

**Comment by minutesinch** [comment]
Same issue for me and only meek bridge works some times.
After using another vpn and enabling orbot, works well.

**Comment by jw243** [comment]
I don't use bridges. I did a clean install of 16.1.2 at least three times. At first it works, but after a restart of the phone, the above happens. 

Version 16.1.0 seems to work.

**Comment by ithink314** [comment]
I saw very similar after orbot update from 16.1.1-Beta-2 to 16.1.2-RC on Galaxy Nexus with Omni Android 7.1.2 and f-droid. Except it hung a little sooner, at "adding control port event handler". Tried setting tor socks setting to 9051 as suggested in f-droid description, which had not been necessary previously, with no luck. Also do not use bridges. It took wipe and re-install of ROM and orbot to get (older) orbot working again.

**Comment by herotux** [comment]
I have same issue in samsung j5 prime with android 7

**Comment by JeremyRand** [comment]
> I saw very similar after orbot update from 16.1.1-Beta-2 to 16.1.2-RC on Galaxy Nexus with Omni Android 7.1.2 and f-droid. Except it hung a little sooner, at "adding control port event handler".

Orbot 16.1.2-RC-2 (installed via the Guardian Project F-Droid repo) also hangs at "adding control port event handler" for me on a Galaxy Note 2 (N7100) on Replicant 6.

> Tried setting tor socks setting to 9051 as suggested in f-droid description, which had not been necessary previously, with no luck.

I didn't try this.

> Also do not use bridges.

I don't use bridges either.

**Comment by crass** [comment]
I had the same issue with `16.1.2-RC-2` and can confirm that `16.1.1-Beta-2` does start up where the latest version fails.  However, `16.1.1-Beta-2` also fails to start when I have a hosted service enabled.  When I disable the hosted service, it starts up fine.

**Comment by 05nelsonm** [comment]
Same thing here. After fresh install it connects fine. After that Orbot does not connect.

Also Hosted Services seems broken as I'm seeing a notification stating "cannot read hidden service name".

**Comment by amuuza** [comment]
I had the same as @JeremyRand , a Replicant fixed by downgrading to 16.1.1.
It recently started to fail, I did not investigate why, but I tested the new 16.1.4-RC-1 and my Replicant connected again!

**Comment by ithink314** [comment]
Orbot 16.1.4-RC-1-tor-0.4.2.5-rc now works OK on both Replicant 6.0 and Omni 7.1.2, on Samsung Galaxy Nexus, after fresh installs (and manually giving storage permission).

However, on Omni 7.1.2, Torbrowser 68.7.0 from f-droid hangs at Starting Tor client... complete (in logs); displaying "Opened HTTP tunnel listener on 127.0.0.1:8218" but not reaching the "about:tor" display. 

On Replicant 6.0, Torbrowser 68.7 crashes after displaying blank screen for a second, then in task bar says Tor Browser Orbot is starting. Tapping that causes blank screen to display, crash (disappears from task bar), then re-appears in task bar.

**Comment by herotux** [comment]
Same problem on xiaomi mi 9 android 10

**Comment by n8fr8** [comment]
New release: https://github.com/guardianproject/orbot/releases/tag/16.2.0-RC-1-tor-0.4.2.7

**Comment by herotux** [comment]
fixed for me in xiaomi MI 9 miui 11 Android 10
