### ISSUE TITLE
Orbot 16.1.2-RC-tor-0.4.1.5-rc running on Android 10 is not starting automatically on boot.

### ISSUE THREAD

**Issue by n1m1** [guardianproject/orbot#263]
As per title.

In "Settings" -> "General" -> "Start Orbot on Boot" option is selected. However Orbot does not start on Boot. In order to run it I need to launch the app.

It has always worked fine on Android 9.

Cheers.

**Comment by 05nelsonm** [comment]
the past couple of updates have screwed it up. I downgraded to Orbot v16.1.0-RC-2-tor-0.4.0.4-rc for the time being

**Comment by patfla** [comment]
Orbot was connecting and working (for a while) but isn't again.  16.1.2-RC-2-tor-0.4.1.5-rc on Android 7.0.

How do I download/check-out/or/build an earlier version?  And if build, what build env is required?

**Comment by 05nelsonm** [comment]
In the FDroid App store, go to settings, repositories. Enable guardian project.

Search for orbot and scroll all the way down to versions. Install the one I listed above. Be sure you uninstalled it before rolling back.

After installing, click the 3 dots in the top right corner and select ignore updates.

**Comment by patfla** [comment]
Thanks - that worked.  The older 16.1.0 is able to establish a circuit where the newest version could not.

The newest version hung just after it spawned a Tor process.   I assume it was, at this point, trying to send out its first messages to the Tor network.  Looked into Settings and saw that there are a lot of values you can set and was wondering if one can give Tor network connectivity a helping hand by setting some of these?  Is there documentation on this somewhere?  That is, in theory, I could set some values here that would succeed in getting the newest version to connect and establish a circuit - possibly a matter of overriding non-working default values inside the latest version of the program.

**Comment by command32** [comment]
Clearing the data and cache seems to work the torrc can be customized
according to tor usage. Read the docs.

**Comment by n1m1** [comment]
Hello,
I am testing the new beta (16.1.3-BETA-1-tor-0.4.1.6-rc) on Android 10. Unfortunately the problem is still present. Orbot does not start automatically at boot. In order to run it I have to launch the app manually. After that, it just creates the circuit.

@05nelsonm @patfla : from your comments it is not clear if you are experiencing the same issue I am reporting here. Actually, it seems that in your case is the problem is different (namely Orbot is not starting at all, neither if you launch it manually). Is it correct? If the answer is yes, this is not the issue that I am trying to track here: can I kindly ask you to open another issue so that we can properly keep track of the different flaws affecting Orbot? However, I noticed that the title I gave to the issue was misleading and I changed it accordingly.

Cheers.

**Comment by patfla** [comment]
@n1m1   Hi - I don't need Orbot to run upon boot.

What wasn't working for me was that it wouldn't establish a circuit at all.  I backed up a couple of versions as recommended here - and it then did succeed in establishing circuits.  I didn't find where to turn off automatic updates (nothing appropriate under ... in the upper right) with the result that it automatically updated itself - except the new version continues to work and at this point, I've left well enough alone.

**Comment by n1m1** [comment]
> @n1m1 Hi - I don't need Orbot to run upon boot.
> 
> What wasn't working for me was that it wouldn't establish a circuit at all. 

OK, this means that you are experiencing a different problem from the the one I am trying to track here. Please, open another issue.

**Comment by n1m1** [comment]
Another small bit of information. 

As I stated in my first post Orbot 16.1.2-RC-tor-0.4.1.5-rc has always worked fine with Android 9. I have just made another attempt with an old Android 8.1 : the same Orbot release just works and automatically starts at boot without any problem.

Cheers.

**Comment by n1m1** [comment]
Apparently the problem seems to be fixed in Orbot 16.2.0-BETA-3 tor-0.4.2.7 . Orbot regularly starts in background now.
