### ISSUE TITLE
Reset Data button

### ISSUE THREAD

**Issue by ingfabby** [guardianproject/orbot#264]
From GP support email:

"Orbot on F-Droid I keep haveing to clear the apps data everytime for orbot to work. On this release. A orbot reset data button in the app would be nice."

**Comment by bitmold** [comment]
You shouldn't _have_ to clear the app's data for it to work. 

Do you know what version of Orbot are you using? 

What data/settings, if any, do you set after clearing the data and restarting Orbot?

**Comment by n8fr8** [comment]
New release: https://github.com/guardianproject/orbot/releases/tag/16.2.0-RC-1-tor-0.4.2.7

**Comment by bitmold** [comment]
Closing this because it pertains to other issues in Orbot + i don't think we should have a data kill switch as a work around ~as it stands now Android provides a way for users to erase all of an app's data anyway
