### ISSUE TITLE
Bug: crash on exit + suggestion

### ISSUE THREAD

**Issue by TheShadowRunner** [guardianproject/orbot#273]
Hello, using Orbot-16.1.2-RC-2-tor-0.4.1.5-rc-fullperm-arm64-v8a-release.apk on Android 7.1.1. 

The issue is that since the last 2 updates, Orbot crashes systematically a couple minutes after I exit the app (3 dots menu > Exit). 

The last version that doesn't crash on Exit is 16.0.5, on Android 7.1.1.

Let me know if you need any further infos. 

An unrelated suggestion: please add an option to "Automatically disable VPN mode on Exit". 
Thank you.

**Comment by n8fr8** [comment]
New release: https://github.com/guardianproject/orbot/releases/tag/16.2.0-RC-1-tor-0.4.2.7
