### ISSUE TITLE
few orbot/tor issues and related iptables (firewall) rc7

### ISSUE THREAD

**Issue by c3ph3us** [guardianproject/orbot#28]
i use orbot with afwall 

**APP > VPN (ORBOT) -> POLIPO -> TOR -> INTERNET ?**

1) set afwall to allow prefered apps traffic on vpn 
2) set afwall to allow orbot traffic on vpn and wifi ( desired connection to internet) 
3) set affwall to use system iptables
3) enable in orbot vpn 
4) set orbot to use system iptables
5) set no network sleep 
4) set allowed applications for orbot 

and i got some issues 

1) granting permission for app to allow vpn connection in orbot & firewall (applied only on reboot) 
see also:
https://github.com/ukanth/afwall/issues/491#issuecomment-176638267
https://github.com/ukanth/afwall/issues/491#issuecomment-177428405

2) orbot is not indicating network traffic but apps are working ( internet connection works) 
(circuits are closed  - no route and trafic is  shown in orbot notification also in logs (circuit closed))   

**seems like orbot is leaking connection see pic 3** 
**1) i can use all apps - those which are enabled in my iptbless (via afwall)** 
**2) my ip is not tor ip**
sugesstion  - orbot to ensure that tor service is working properly and connection to circuit is made / polipo is working correctly - before allow any  data on vpn !!!

![screenshot_20160131-092116 1](https://cloud.githubusercontent.com/assets/10565704/12701064/93983868-c7fc-11e5-927d-37bc0f6926b4.png)

![screenshot_20160131-092214 1](https://cloud.githubusercontent.com/assets/10565704/12701065/9994f044-c7fc-11e5-93c5-a175541d60ca.png)

![screenshot_20160131-093023 1](https://cloud.githubusercontent.com/assets/10565704/12701089/b125c11a-c7fd-11e5-8973-63644df49d76.png)

3) after some intensive use orbot/tor  behave weird as overloaded 

4)mixing bridges / nodes mode  (changing from one to other) results in overloading and weird behavior) 

5) when i start orbot (go to home-screen  with back button or home )  to other app and go back  to orbot its initializing itself  as  there was no start before ( polipo / new circuit  new listener etc ) 

6) how i can be sure that tor is working properly  (apps are using tor  and traffic is not leaking somehow - i mean not to check on orbot start but after some time of work with orbot/tor ) ?

7) orfox has build in polipo tor service ?(as i dont start orbot orfox is working) ? 
(does this not influencing orbot work  - closing opening ports and services ?)

8) in above setting scenario how i can be sure that traffic sends to polipo is going thru tor ? if some app didn't kill polipo and sets its own (as spoofing) 

9) what about doze mode for orbot / tor (how is(is it) handling it) ?

**Comment by CHEF-KOCH** [comment]
You posting this issue in the wrong issue tracker, this is the [source url](https://gitweb.torproject.org/orbot.git#) and [your report belongs in here](https://trac.torproject.org/).
