### ISSUE TITLE
Orbot fails to reconnect

### ISSUE THREAD

**Issue by ingfabby** [guardianproject/orbot#283]
Samsung Galaxy note 10
It used to work perfectly but now it fails to reconnect every time. I tried changing the port it needs as per the instructions on Google play store but it still doesn't connect.

**Comment by jhoc2000** [comment]
I'm having the same problem with LineageOS 17.1-20200405-NIGHTLY-beryllium and Orbot Version 16.1.4-RC-1-tor-0.4.2.5-rc.

**Comment by n8fr8** [comment]
https://github.com/guardianproject/orbot/releases/tag/16.2.0-RC-1-tor-0.4.2.7
