### ISSUE TITLE
VPN mode completely broken in Orbot 16.1.3-BETA-2-tor-0.4.1.6-rc on Android 10

### ISSUE THREAD

**Issue by n1m1** [guardianproject/orbot#288]
As per title.

I am running the last Orbot (16.1.3-BETA-2-tor-0.4.1.6-rc) on Android 10 (GrapheneOS). Unfortunately, **VPN mode seems to be completely broken** in this last release. Not only the traffic is not routed through Tor, but Orbot seems to be the culprit for DNS leaks on the local network.

These are the test that I have just run:

0. I have tried to use a regular browser in VPN mode and connect to check.torproject.org : the site says that I am not connected to Tor and it reveals my real IP.

1. In my local network I run Pi-Hole in order to manage DNS queries. Whatever app in VPN mode I run, it leaks every single DNS query. I can see the leaks in PI-Hole and dnsmasq logs. Even worst, this is not true only for "regular" domains but, unfortunately, for onion domains as well.

This is very unfortunate and, in my case, makes Orbot barely usable. The issue could be related to #262 .

However, apps regularly proxied through Orbot (localhost:8118) seems to work regularly.

Cheers and thanks for your work.

**Comment by n8fr8** [comment]
Graphene is a fork of Lineage which has a known bug with Orbot's VPN mode. We are working to try to solve it.

**Comment by purplesparkle** [comment]
Graphene is not a fork of Lineage, it's roots are in AOSP. Just for your info ;)

**Comment by n8fr8** [comment]
> Graphene is not a fork of Lineage, it's roots are in AOSP. Just for your info ;)

Apologies for the confusion.

**Comment by n1m1** [comment]
Apparently the problem seems to be fixed with release 16.2.0-BETA-3 tor-0.4.2.7. VPN mode is working properly and no more DNS leaks on LAN.
