### ISSUE TITLE
Cannot connect using obfs4 bridges (various Android versions)

### ISSUE THREAD

**Issue by sindastra** [guardianproject/orbot#290]
# Description

I tried different versions of orbot, both arm and arm64 and it seems custom obfs4 bridges stopped working in v16+ while v15 still works.

# What was tested

I even just tested the latest release (orbotMAX-16.1.3-BETA-2-tor-0.4.1.6-rc-fullperm*) from your GitHub releases page here for both arm and arm64 to see if it was resolved, but unfortunately not. This issue also affects the latest version on Google Play Store and F-Droid (16.1.2-RC-2).

I tested different versions, and every version I tried that was lower than v16 worked for me, while every version of v16 that I tested did not.

The latest known to work version with obfs4 bridge is: 15.5.1-RC-2-multi-SDK23

# Summary

The problem is basically, that while v15 works fine with obfs4 bridges, in v16 you get stuck at connecting (endlessly). You should note that in v16, vanilla bridges (no obfuscation) still works.

So somewhere, something was changed in v16 that made obfs4 bridges stop working.

**Comment by sindastra** [comment]
# Further Findings

I took apart the v15 and the v16 apk, and I noticed v15 includes the obfs4proxy binary while v16 does **not**.

In v15, this binary comes included with Orbot:

```
bin/obfs4proxy: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/, not stripped
```

### In v16 this binary is nowhere to find, however you can find obfs4proxy.so:

```
lib/arm64-v8a/obfs4proxy.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/, stripped
```

```
lib/armeabi-v7a/obfs4proxy.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/, stripped
```

Another thing that I notice is that the arm64 version comes with the same obfs4proxy.so as the normal arm version. Checksums match, too: SHA1 2541a68db820e825e40f8955baf9148113afbc49

I wonder if it would need an arm64 version of obfs4proxy.so and I also wonder if the torrc has been updated to point to this newly named file...

**Comment by sindastra** [comment]
# Problem possibly found: Android 10 compatibility

I now tried both the latest release (16.1.3-BETA-2) and the latest Google Play Store release (16.1.2-RC-2) on Android 9, and it works just fine with obfs4 bridges! So it might be that it doesn't work on my phone because it is running Android 10. :thinking:

Samsung Galaxy S10e with Android 10: obfs4 bridges do **not** work.

Samsung Galaxy Tab S5e with Android 9: obfs4 bridges work.

**Comment by minutesinch** [comment]
I have same problem and agree with your issue, obfs4 not work and only meek work me. 
Also stuck in obfs4.
Android 7.1.1 stock;Galaxy A8 2018

**Comment by goovich** [comment]
Yeap, seems like obfsproxy binaries have to be updated for Andoid 10 with "alignment is 4, needs to be at least 32 for ARM Bionic" from obfs4 pluggable transport.

**Comment by n8fr8** [comment]
obfs4 and meek are the same binary, all are compiled for 64-bit builds. We test on Android Q, so it must be something else. 

I do appreciate all the detail here, and this is a tricky problem we have been trying to solve for awhile. Glad to hear that 16.1.3-BETA-2 is improving things.

**Comment by sindastra** [comment]
I updated the title to be broader as it seems the real cause of this issue is not known. Orbot with obfs4 works for me everywhere except on my Android 10 device. But @n8fr8 said they test on Android 10. Another user @minutesinch reported issues, with yet another Samsung Galaxy phone but on Android 7. Perhaps a Samsung specific issue? Although it works fine on my Samsung tablet with Android 9. 🤔

**Comment by Kylvan** [comment]
Obfs4 doesn't work on my OnePlus Android 9.0

**Comment by goovich** [comment]
> I updated the title to be broader as it seems the real cause of this issue is not known. Orbot with obfs4 works for me everywhere except on my Android 10 device. But @n8fr8 said they test on Android 10. Another user @minutesinch reported issues, with yet another Samsung Galaxy phone but on Android 7. Perhaps a Samsung specific issue? Although it works fine on my Samsung tablet with Android 9. 🤔

No, it is not Samsung specific issue. I have same problesm on my Mi9T Pro after firmware update to andoid Q. With previous Android version I had no issues with orbit and obfsproxy.

**Comment by Zkdc** [comment]
> > I updated the title to be broader as it seems the real cause of this issue is not known. Orbot with obfs4 works for me everywhere except on my Android 10 device. But @n8fr8 said they test on Android 10. Another user @minutesinch reported issues, with yet another Samsung Galaxy phone but on Android 7. Perhaps a Samsung specific issue? Although it works fine on my Samsung tablet with Android 9. thinking
> 
> No, it is not Samsung specific issue. I have same problesm on my Mi9T Pro after firmware update to andoid Q. With previous Android version I had no issues with orbit and obfsproxy.

I have the same problem on my Mix2s. After upgrading to Android Q I can not use obfs4 or meek bridges with "alignment is 4, needs to be at least 32 for ARM Bionic" error in logs.I am using the latest fdroid version16.1.4-RC-tor-0.4.2.5-rc.

After searching this error I find it seems to be a golang issue.

https://github.com/shadowsocks/v2ray-plugin-android/issues/6
https://github.com/Catfriend1/syncthing-android/issues/370

**Comment by minutesinch** [comment]
@n8fr8 and @sindastra lets take a look, I see peoples reporting issue in android Q(10) and this issue even related android 7+ like my phone, also i think bridge go offline so please test and fix it.
meek bridge some times work with errors  but obfs4 always return error.

**Comment by n8fr8** [comment]
New build for testing: https://github.com/guardianproject/orbot/releases/tag/16.2.0-BETA-2-tor-0.4.2.7

It has fixes specifically addressing Android Q issues, and how the tor and obfs4proxy are deployed.

**Comment by sindastra** [comment]
With Google's new security policies sideloading has been blocked. I cannot currently test this build on my affected device. However, I will try to install LineageOS (Android 10) on a spare device for some testing (old builds vs new build) in the coming days.

**Comment by n8fr8** [comment]
@sindastra Where has sideloading been blocked? I haven't heard this before.

**Comment by sindastra** [comment]
@n8fr8 See here: https://support.google.com/accounts/answer/9764949?hl=en

Although it claims ADB sideloading should still work, it didn't for me.

**Comment by bitmold** [comment]
Closing this because I can connect to ofbs4 with Orbot on different versions of Android. Recently with #411 the new IPtProxy runs obfs4 in process instead of packaging an executable obfs4 binary as was done before. Please open a new issue if obfs4 issues still persist
