### ISSUE TITLE
Release 16.1.2-RC-2-tor-0.4.1.5-rc 

### ISSUE THREAD

**Issue by ingfabby** [guardianproject/orbot#291]
The App gets stuck after going into the background. The only way to connect to the Tor network again is to reinstall the app.
We have many similar reports from different devices, It worked fine on my phone for a day and then it started to do the same thing.

**Comment by n8fr8** [comment]
The next release (now in beta here: https://github.com/guardianproject/orbot/releases/tag/16.1.3-BETA-2-tor-0.4.1.6-rc) should solve these issues.

I'm doing the first RC this week.
