### ISSUE TITLE
Bridge Test Connection...

### ISSUE THREAD

**Issue by minutesinch** [guardianproject/orbot#294]
I check bridge for connecting to tor network the green text apear and say "Test Bridge Connection to Tor" Obfv4 say nothing happens and Meek conecct perfectly but when i change to obfs4 and change to meek stuck in "Test Bridge Connection to Tor" and stucking when i change to other too.

This bugs happens in pc version too i think there is problem with tor please fix it...

**Comment by n8fr8** [comment]
we have an improved bridge UX now in the latest Orbot.
https://github.com/guardianproject/orbot/releases/tag/16.2.0-RC-1-tor-0.4.2.7

**Comment by minutesinch** [comment]
> we have an improved bridge UX now in the latest Orbot.
> https://github.com/guardianproject/orbot/releases/tag/16.2.0-RC-1-tor-0.4.2.7

yes but bug still happens

**Comment by bitmold** [comment]
There's unfortunately a known issue where all of the ofbs4 bridges hardcoded into Orbot (`85.17.30.79`, `154.35.22.9`, `192.99.11.54`) are offline (see #258). 

The way this screen works is that one at a time each of those IP addresses are tested for connectivity for a total of ten seconds, so after 30 seconds you will see the test failed text. Notably if you launch another test, say to meek, you still will have to wait for the obfs4 test to finish before the meek test is run. Unfortunately, even in 16.2 that @n8fr8 linked above, it is possible that when you click one of those tests (direct tor connection, ofbs4, meek, etc) multiple tests are fired off at once (so perhaps you'd have to wait 30 seconds on ofbs4 multiple times before seeing something else...). These issues usability issues are being addressed in #365 so I am going to close this issue.
