### ISSUE TITLE
Usb Tethering Issue - 4G cellular provider - Orbot

### ISSUE THREAD

**Issue by Kylvan** [guardianproject/orbot#298]
Hello there,

I have a usb tethering issue while using Orbot. Even if i've checked Open proxy on all interfaces when i'm using my laptop browser my ip is the one provided by my cellular provider, although when i use my smartphone browser my IP is correctly hidden.

Is it possible to manage to hide my ip on my laptop browser while using 4G connection over usb tethering ? With and without root available ? And if it is, how ?

Regards

**Comment by rhystedstone** [comment]
This is the same issue as #317 as the option simply doesn't work. That's why it's your provider's IP address on your laptop.
I know this issue is over 2 years old now, so can an admin close it please?

**Comment by bitmold** [comment]
Closing, i intend to work on #317 soon
