### ISSUE TITLE
context menu in Tor log in Zulu

### ISSUE THREAD

**Issue by Parckwart** [guardianproject/orbot#300]
When marking text in the Tor log that's shown when swiping left, the options "Copy", "Share" etc. are shown in Zulu as "Kopisha", "Yabelana" and so on.
![aaa](https://user-images.githubusercontent.com/8195243/73412182-bc367280-42ff-11ea-8863-5e083889c7fe.jpeg)

**Comment by bitmold** [comment]
Hi, I'm looking into this right now. I've noticed that additional Android default Dialog text strings (such as "accept", "cancel", etc) also are in Zulu (I use Orbot in English). 

![image](https://user-images.githubusercontent.com/22125581/78734338-00547d80-7916-11ea-8503-0d89a315b40b.png)

**Comment by bitmold** [comment]
And that this bug exists throughout the entire app, not just the log

**Comment by bitmold** [comment]
Also, I saw the menu in English and then when I opened the app Settings and returned back to the Tor log the settings were then in Zulu
