### ISSUE TITLE
App's welcome screen showing blank screen (text is missing after orientation change)

### ISSUE THREAD

**Issue by Hashik-Donthineni** [guardianproject/orbot#304]
The welcome screen, when you open the app for the first time, is showing a blank screen when you rotate the device (change orientation). 
Reference Image (All the slides are same):
![Screenshot_20200227-141135](https://user-images.githubusercontent.com/22850179/75426831-71922f80-596b-11ea-98ef-59c916d9ca57.png)

**Comment by bitmold** [comment]
I think this can be closed with #305 being merged

**Comment by bitmold** [comment]
I've tested this and text is no longer lost, but upon rotation you are always taken back to the first slide. I'm working on a fix for this right now

**Comment by bitmold** [comment]
Both of these issues seem to still exist or were reintroduced :(

**Comment by Hashik-Donthineni** [comment]
Hey @bitmold The text is going away again?

**Comment by bitmold** [comment]
Yes, right now the onboarding flow will just close:
![close](https://user-images.githubusercontent.com/22125581/88683040-5e71c000-d0c1-11ea-8d25-2865204f94ce.gif)

I've been tinkering with this flow, and we don't actually need to do any complicated work to preserve activity state on rotation. You get the expected results by setting the `android:configChanges` property in the manifest for the `OnboardingActivity`:

```
        <activity
            android:name=".ui.onboarding.OnboardingActivity"
            android:configChanges="orientation|screenSize|screenLayout|keyboardHidden" />
```

This tells the system to not destroy/create a new activity when the device is rotated and it gives us the desired results we want. In fact, it lets us safely delete a bunch of code we have written!

**Comment by bitmold** [comment]
@Hashik-Donthineni if you'd like please take a look at #373

**Comment by Hashik-Donthineni** [comment]
Okay! thank you for working on this. But it's weird it reoccurring, It's supposed to work, are there recent complaints about this @bitmold ?

**Comment by bitmold** [comment]
Not that I am aware of. Today/yesterday I've been going through older issues that are still open and trying to close out as many as possible. When revisiting this one I tested the code off of the `master` branch and found that this issue (or at least an issue similar to the one you initially reported with this ticket) still existed.

**Comment by Hashik-Donthineni** [comment]
Can you please confirm that it's not working by testing? It's just that, I am doing everything that can be done to save the state, it's not possible to lose the state. What do you think?

**Comment by bitmold** [comment]
I did confirm by testing, I posted a gif of the onboarding flow crashing after rotation and on April 26th I tested the code at that point in time and noticed that the slide position would be incorrectly set after rotation

**Comment by Hashik-Donthineni** [comment]
Ah, yeah. It's not related to the restore I just couldn't find a way to reset the slide number. There is no way to manually set the slide from the API as far as I can remember I tried.

**Comment by bitmold** [comment]
Anyway, that issue aside, the onboarding slids would still break after rotation. Feel free to test the code on `master` right now to verify this yourself

**Comment by Hashik-Donthineni** [comment]
"Yes, right now the onboarding flow will just close:"
I just saw this, the GIF didn't load earlier. So I guess we can drop this since you are handling this at #373
