### ISSUE TITLE
Newer orbot versions opens socks 5 proxy prior of circuits being established

### ISSUE THREAD

**Issue by tlaurion** [guardianproject/orbot#306]
The past several versions of orbot for lineageos 14.1 (Android 7.1.2, build made by e.foundation for the N7100, N7105, I9300 and I9305 and others) are behaving pretty weird.

First, circuits are not always established:
```
checking binary version: 0.4.2.5-openssl1.0.2p
upgrading binaries to latest version: 0.4.2.5-openssl1.0.2p
Waiting for control port...
Set background service to FOREGROUND
checking binary version: 0.4.2.5-openssl1.0.2p
updating settings in Tor service
updating torrc custom configuration...
torrc.custom=
ControlPortWriteToFile /data/data/org.torproject.android/files/control.txt
PidFile /data/data/org.torproject.android/files/torpid
SOCKSPort 9051 IsolateDestAddr  IPv6Traffic PreferIPv6 
SafeSocks 0
TestSocks 0
HTTPTunnelPort 8119
ReducedConnectionPadding 1
CircuitPadding 1
ReducedCircuitPadding 1
TransPort auto
DNSPort 5400
VirtualAddrNetwork 10.192.0.0/10
AutomapHostsOnResolve 1
DormantClientTimeout 10 minutes
DormantOnFirstStartup 0
DisableNetwork 0
Log debug syslog
Log info syslog
SafeLogging 0
UseBridges 0
GeoIPFile /data/data/org.torproject.android/files/geoip
GeoIPv6File /data/data/org.torproject.android/files/geoip6
StrictNodes 0



success.
```

When that happens, orbot is setuped to be useble through port 5400 for DNS and port 9050 for socks 5 proxy. If netguard is setuped to use those ports and it's vpn function is forced to be on, even if orbot is not fully started up at that point, any application network traffic is tunneled through clear net, passing through orbot failing open.

Expected behavior:
Orbot should fail close prior of circuits being established. 

Actual behavior:
The actual behavior is that once orbit application is started, communications are proxied even though circuits aren't. Dangerous behavior.

**Comment by Hashik-Donthineni** [comment]
Wow, this seems pretty serious.

**Comment by jhoc2000** [comment]
Not working on LineageOS 17.1-20200405-NIGHTLY-beryllium.

**Comment by n8fr8** [comment]
The ports are opened by Tor itself, as part of the boostrap process.

If your app is configured to use the ports, but no circuits are established, the traffic will just NOT be routed at all. It will not route through clear text. The packets will just not go anywhere.

**Comment by tlaurion** [comment]
@n8fr8 : I would advise for Tor browser and Orbot to default to a different set of ports in code config.
So that Orbot defaults to 5400, 9050 etc, while Tor Browser defaults to 54001 and 9051. So that the usage of both programs on a single device doesn't produce unwanted outcome and undesired bugs and needs of manual reconfiguration for end user. There is nothing stopping a Tor Browser user to go through Orbot if he desires so to use the double circuits in this scenario.
