### ISSUE TITLE
VPN mode is barely usable on Samsung Galaxy S9+ 

### ISSUE THREAD

**Issue by gustavonalle** [guardianproject/orbot#316]
I have enabled AUTO for all the HTTP, DNS and SOCKS ports, the Tor circuit is stablished 100%, but VPN mode works only 1 out of 10 tries. Most times the app under VPN mode cannot connect to the internet at all, sometimes it can only reach clearnet.
Constantly restarting, enabling and disabling VPN somehow make it work, but I am not sure why

**Comment by n8fr8** [comment]
New build for testing: https://github.com/guardianproject/orbot/releases/tag/16.2.0-BETA-2-tor-0.4.2.7

**Comment by n8fr8** [comment]
Please test: https://github.com/guardianproject/orbot/releases/tag/16.2.0-BETA-3-tor-0.4.2.7
with a fresh install. Thanks!

**Comment by gustavonalle** [comment]
It does not solve it unfortunately

**Comment by gustavonalle** [comment]
Problem also happens on GrapheneOS, I tested https://github.com/guardianproject/orbot/releases/tag/16.2.0-RC-1-tor-0.4.2.7
The only way to make it work is setting ```Private DNS``` to ```Off``` in Android itself

**Comment by odiferousmint** [comment]
I have the same issue with Samsung Galaxy J3. I have to clear data and restart the app for it to work. In older versions it was even worse, but it is still an ongoing issue albeit the workaround is less time-consuming now.
