### ISSUE TITLE
“Open Proxy on All Interfaces” has no effect

### ISSUE THREAD

**Issue by d-g** [guardianproject/orbot#317]
LineageOS 16.0, Guardianproject’s build of Orbot 16.1.4-RC-1-tor-0.4.2.5-rc.

## Steps to reproduce:

1. Settings / Open Proxy on All Interfaces [✓]
2. START

## Expected result

Tor listens for SOCKS and HTTP connections on any interface.

## Actual result

Tor still listens local clients only:

	# ss -tlp sport == 9050 or sport == 8118
	State       Recv-Q Send-Q Local Address:Port                 Peer 	Address:Port                
	LISTEN      0      128    127.0.0.1:8118                 0.0.0.0:*                     users:(("tor",pid=1394,fd=10))
	LISTEN      0      128    127.0.0.1:9050                 0.0.0.0:*                     users:(("tor",pid=1394,fd=7))

## (Possibly) related

- https://github.com/guardianproject/orbot/pull/110
- https://github.com/guardianproject/orbot/issues/298

**Comment by wafles38** [comment]
yep, this is also happening to me.

I attempted to use the configuration I use on desktop, I went to the settings and modified the torrc to say
SocksPort 0.0.0.0:9050
SocksPolicy *

This works on Tor Browser ubuntu and windows. I can connect to the proxy on my desktop devices. It didn't work on android sadly. I was thinking of directly modifying the torrc file or messing with the app settings, since I have root, but I don't know how to find it on Android 5.1.1 (Monstro's Rom V3, SM-G360T1)

**Comment by wafles38** [comment]
god damn thank god I didn't lose my update. I felt very bummed out when I lost connection and the page reloaded (I had to disable Fwd in order to look at the titles of the fields and properly provide instructions)

**Comment by n8fr8** [comment]
Will take a look... def that preference should set the proxy ports to 0.0.0.0

**Comment by n8fr8** [comment]
@d-g you are using a pretty old version of Orbot. Might want to try a newer release:
https://github.com/guardianproject/orbot/releases

**Comment by Kylvan-8** [comment]
> 

With the workaround or by simply using the default option for tethering, i still get the same ip address when not using Orbot when i connect my computer to the wi-fi access point of my phone, even with other devices.

I'm running Orbot on the last github release version on Samsung Galaxy S20 Android 11.

**Comment by bitmold** [comment]
This preference uses `SocksListenAddress 0.0.0.0` which has been deprecated for some time.

I'm looking into doing something like @wafles38 said in an upcoming release.

Like they said, adding something like this to the `torrc` should but doesn't work.

```
SocksPort 0.0.0.0:9051
SocksPolicy Accept *
```

**Comment by bitmold** [comment]
If there isn't a trivial fix for this, we should hide the preference from users until we get this functionality back

**Comment by bitmold** [comment]
This feature is finally working, however a new release of tor-android will be needed as well as orbot #715
