### ISSUE TITLE
 Orbot connects directly to raw.githubusercontent.com on startup 

### ISSUE THREAD

**Issue by n8fr8** [guardianproject/orbot#323]
https://trac.torproject.org/projects/tor/ticket/34025

**Comment by Hashik-Donthineni** [comment]
Hey, @n8fr8 You said you were going to provide a way to turn it off since folks in China might need it to get updates. Did you ditch that idea? If so, what's the plan to inform the said people about the updates.

**Comment by bitmold** [comment]
I think that's a good idea, having the raw.githubusercontnet.com update check happen behind a preference that is initially set to off.

**Comment by bitmold** [comment]
With this check removed, this ticket can be closed. This update check was never really update to date anyway as the `update.json` file pointed to a very outdated release of Orbot. I deleted the json file that `AppUpdater` was checking against just now
