### ISSUE TITLE
obfs4 problem

### ISSUE THREAD

**Issue by minutesinch** [guardianproject/orbot#332]
in Orbot 16.2.0 RC-1 (tor-0.4.2.7) version of tor still obfs4 have problem and return error when i try to connect with and some times this bridge not work but  TB work well, i found a way; first close orbot, force stop it and clear data and with this way obfs4 work well but i must every time do it and i know there is problem with orbot please fix

**Comment by n8fr8** [comment]
Please try: 16.4.1-RC-2-tor.0.4.4.6 latest release. You can also request fresh obfs4 bridges from Tor in the app now.
