### ISSUE TITLE
Orbot_16.1.4-RC android 6.0.1CM arm7

### ISSUE THREAD

**Issue by Mixalhadas** [guardianproject/orbot#333]
Hello, 

First of all, great work you have done, thank you very much for this project.

- there are some issues related with cache, I must delete the "app data" folder after ending the session if I want to connect again.
this issue is very consistent, if I want to restart the app, I must delete the "app_data" folder or it will stop the log on "SUCCESS connected to Tor control port."

- there is a bug regarding the switches (main on/off and vpn )
starting a connection without first switching on vpn mode will prevent the vpn switch, of switching off upon pressing main switch(to end the connection), keeping the vpn on, without being connected to tor network. this may be intentional but I dont see the point.

This part is very confusing to me, and I'm not fluent in english language, but I will try to explain the best i can.
                                                            SETUP
   -  I'm using mobile network to connect the device to the internet 3g/4g
   -  I'm using localhost:8118 for apn proxy
   -  I'm using  localhost:5400 for system dns server
  As I see things, clearnet access should be very hard to get from my device with this settings on.

                                                            ISSUE
- Connecting to tor network with vpn(full device) mode on, will grant access to clearnet on the device. Connecting with vpn mode off solves this issue.
-this does not replicate on wiffi connections with global http_proxy set to localhost:8118

Now, the reason I'm opening this issue,

I intend to use the device as a tor network hotspot, but I'm not able to share the connection, even with "open proxys on all interfaces" on. (transparent proxy off)

Sharing the connection with mobile hotspot, and vpn mode off, I get no connection at all on the client.

Sharing the connection with mobile hotspot, and vpn mode on, I get connection to clearnet on the client. 
Sharing any vpn connection is only possible, to me, using an app named "vpn hotspot", this app manage all hotspot connections and creates a connection(ap0) between the connected peers redirecting upstream network interface(tun0) or/and fallback upstream interface(ccmni0) connections to them.

Using netcfg with vpn mode on, the terminal shows me that I have 3 interfaces UP, names "lo","tun0", "ccmni0"

this procedure works well when I'm sharing an ssh/vpn connection, I don't see why it shouldn't work with orbot.

All this problems may only be, misconfiguration from my side, and probably it is. Anyway sharing this information may help others with similar issues.

Sorry for the long post, but I couldn't do this any other way because it would be a mess.

there are no logs cause I delete data/cache on app shutdown automatically.

Thank you again for all your work.

**Comment by n8fr8** [comment]
Thanks for all of this detail. I will go through it closely when I can. For now, please try the latest release from here:
https://github.com/guardianproject/orbot/releases/tag/16.2.0-RC-1-tor-0.4.2.7

**Comment by n8fr8** [comment]
Also there are known issues on Android with connecting mobile hotspot with VPNs. You can do it with a rooted device and iptables rules, but not via VPN.

**Comment by Mixalhadas** [comment]
> Also there are known issues on Android with connecting mobile hotspot with VPNs. You can do it with a rooted device and iptables rules, but not via VPN.

the app vpn hotspot uses iptables no route and mask. the device is rooted latest busybox.

I'm looking at the new app, and it seems that the issue with cache is solved.
I will look into the other issues as well, and ill report back if they are solved

**Comment by bitmold** [comment]
@Mixalhadas could you please test the cache issue again with our latest release. https://github.com/guardianproject/orbot/releases/tag/16.3.3-RC-1-tor-0.4.3.6 Over the summer I believe that this problem was fixed... Thanks :)

**Comment by bitmold** [comment]
Closing, the cacheing issue was resolved a while ago and this issue is for a superficially very old version of Orbot
