### ISSUE TITLE
i can't install Orbot universal version

### ISSUE THREAD

**Issue by Azoic** [guardianproject/orbot#340]
i cant install any universal version of orbot on my nexus 5 lineageos 16
only v7a version is installable

![photo_2020-05-15_12-36-35](https://user-images.githubusercontent.com/3455580/82027141-06721280-96a9-11ea-9c3b-ca495b39bfaa.jpg)

**Comment by bitmold** [comment]
Are you still having this issue with new universal builds of Orbot? We'd appreciate it if you tried with https://github.com/guardianproject/orbot/releases/tag/16.3.3-RC-1-tor-0.4.3.6

**Comment by Azoic** [comment]
i installed from google play
