### ISSUE TITLE
Missing ABI in F-Droid package

### ISSUE THREAD

**Issue by leophys** [guardianproject/orbot#347]
Hi, thanks for your work!

The latest update from guardian project f-droid repo provides an orbit update that is apparently not compatible with the ABI of my phone (one plus 6, android 10 - Lineage 17.1).

Am I missing something?

Thanks again

**Comment by n8fr8** [comment]
Our F-Droid versioning got mixed up, and is promoting an older release of Orbot. We are fixing it.

For now you can find the latest Orbot release here as an APK download:
https://github.com/guardianproject/orbot/releases/tag/16.3.0-RC-1-tor-0.4.2.7

You should likely get the arm64 release:
https://github.com/guardianproject/orbot/releases/download/16.3.0-RC-1-tor-0.4.2.7/Orbot-16.3.0-RC-1-tor-0.4.2.7-fullperm-arm64-v8a-release.apk

**Comment by leophys** [comment]
Thanks, it worked!
