### ISSUE TITLE
Can not find "TorVpnService" Service Class

### ISSUE THREAD

**Issue by SArsalanK** [guardianproject/orbot#348]
Hey, I Tried to clone the project. I can not find Can not find "TorVpnService" Service Class

![Screen Shot 2020-06-07 at 3 20 37 AM](https://user-images.githubusercontent.com/2125947/83955617-057a6e00-a86e-11ea-9fd6-422178edc109.png)

**Comment by bitmold** [comment]
Hi, this is because by default Android studio will try to build the `app-mini` build variant instead of the regular Orbot app. Recent code changes to Orbot broke the unreleased miniature app, but it's probably not what you were trying to build anyway.

**Comment by bitmold** [comment]
At the top of your screenshot it says `app-mini` and you can change it to `app`.

**Comment by SArsalanK** [comment]
> At the top of your screenshot it says `app-mini` and you can change it to `app`.

Thanks, It resolved the issue.

**Comment by SArsalanK** [comment]
can you help me with https://github.com/guardianproject/orbot/issues/349#issue-632777273
