### ISSUE TITLE
Please include app control on VPN mode.

### ISSUE THREAD

**Issue by onioneye** [guardianproject/orbot#35]
Orbot's VPN mode is great.
However, I am using NoRoot Data Firewall, which use VPN API to filter which apps to connect.

Try out https://apkpure.com/noroot-data-firewall/com.jianjia.firewall , and please include their
filtering to Orbot itself, so I could delete it and use Orbot natively.
## 

I don't want other apps to connect to the Internet, even they routed by Tor.
My phone can't be rooted because there's no guide to do this.

**Comment by n8fr8** [comment]
Rethink/BraveDNS app is the best way to do this. It is an app firewall, DNS privacy tool ,and also can proxy all traffic to Orbot's localhost 9050 SOCKS port.

https://www.bravedns.com/

We are working to better integrate them: https://github.com/celzero/rethink-app/issues/131

**Comment by ignoramous** [comment]
Hi there,

One of the developers of RethinkDNS/BraveDNS here. We have scoped one-click Orbot support for our v054 release (hopefully in time for Christmas if not the New Year). The current release is v052. v053 is days away.

**Comment by ignoramous** [comment]
We've merged Orbot integration in RethinkDNS mainline: https://github.com/celzero/rethink-app/tree/b3e126e1de2cc78f61747b228ccc572696a0d6a3

Release is days away (even if late by 3 months: The lead developer was down with virus for parts of Jan and entire Feb).
