### ISSUE TITLE
Orbot fails to stop

### ISSUE THREAD

**Issue by ingfabby** [guardianproject/orbot#352]
From GP support email

Phone: Xiaomi Mi 9t pro android 10 miui 11
Orbot version: latest from Google play

 I can't shut down orbot. It says that tor service is turning off and never goes full off. I have to kill app in system to force it's shutdown.

**Comment by bitmold** [comment]
Do you use the VPN feature at all? There was a bug #329 that sounds like the behavior you are describing. 

The latest release, 16.3 hasn't been put out on the play store yet. I'm not sure when it will be, but if you could please test this version and report if this issue still occurs you can download it from this GitHub: https://github.com/guardianproject/orbot/releases/tag/16.3.0-RC-1-tor-0.4.2.7

**Comment by bitmold** [comment]
Specifically version 16.3 that I linked you fixes a similar sounding bug...
