### ISSUE TITLE
Bridges configuration fail

### ISSUE THREAD

**Issue by ingfabby** [guardianproject/orbot#358]
Galaxy 8S
Android 9
Whenever you try to change your current Bridge configuration to a different one once you select a different option and go back to the main screen Bridges are deactivated, if you go into Bridges settings again the option you last selected is not the one active, instead the app goes back to the "Custom Bridges" option.

**Comment by bitmold** [comment]
Working on this now, another thing I noted is that when you click "Connect directly to Tor (Best)" in the `BridgeWizardActivity` you still see the messages: "Testing bridge connection to Tor" and possibly "Success. Bridge configuration is good" despite a direct Tor connection not actually using any bridges. The status text needs to be specialized in this case...
