### ISSUE TITLE
Improvements to MOAT server access

### ISSUE THREAD

**Issue by n8fr8** [guardianproject/orbot#370]
The MOAT server has its own direct Meek endpoint. We can use it to talk to it directly, without the need for Tor.

To do so, we should use the APT library, which is already built into Orbot. We can start up a Meek instance directly to a custom endpoint, like this:

https://github.com/guardianproject/AndroidPluggableTransports/blob/master/sample/src/main/java/info/pluggeabletransports/sample/SampleClientActivity.java#L94

Then we can read/write bytes to it to speak HTTP.

Let's see if we can get it working!

**Comment by tladesignz** [comment]
@n8fr8, see the mentioned commit. This starts obfsproxy's meek_lite in a new thread (would need to move to a service, of course for production) and should prepare `Volley` resp. `HttpURLConnection` to use it as a SOCKS proxy.

No error messages can be seen, no response arrives. Can you have a look? Thanks!
