### ISSUE TITLE
hard time connecting to v3 using orbot socks

### ISSUE THREAD

**Issue by justinvforvendetta** [guardianproject/orbot#377]
i have an android app that uses a hidden service, and requires orbot running. recently i changed my apps service's v2 onion name to a v3 address, but now its having a hard time, and orbot is saying "SOCKS: Host unreachable", however i'm connecting just fine to the original shorter .onion still.  does orbot have any known issues with connecting to a v3 via sock or is it likely just something im overlooking on my end?

**Comment by bitmold** [comment]
Curious if you are still having difficulties reaching v3 with the latest beta https://github.com/guardianproject/orbot/releases
