### ISSUE TITLE
mbps instead of Mbps in the indicator

### ISSUE THREAD

**Issue by DaKnig** [guardianproject/orbot#378]
when checking the download rate both in the app main page and in the notifications, it measures download speed in mbps instead of Mbps - in ISO units, m is .001 and in this case this doesnt make much sense. Mbps is more correct and more common.

**Comment by n8fr8** [comment]
In fact, what we mean is MBps and KBps, as those numbers come from bytes transfered per second, not bits.

https://www.attplans.com/resources/difference-mbps-and-mbps/

Will fix, so thanks for having us take another look.

**Comment by bitmold** [comment]
It is using 1024 bytes as kB, it should be KiB/s and MiB/s respectively, thanks!
