### ISSUE TITLE
can't connect to any hidden services

### ISSUE THREAD

**Issue by infinity0** [guardianproject/orbot#384]
I am on 16.3.0-RC-1-tor-0.4.2.7 but I think this problem has been happening for quite a few months - I host a calendarserver as a hidden service and haven't been able to connect to it for a few months, but so far have been ignoring the errors.

Trying to debug this, I find that I can't get any application to connect to a hidden service via orbot - I get various DNS-related errors. In Fennec in `about:config` I have set `network.dns.blockDotOnion` to `false` and `network.proxy.socks_remote_dns` to `true` but it still doesn't work. It used to work a few months ago. Other applications give similar DNS-related errors.

Tor Browser Android works fine, I can connect to the hidden service there.

I get the same results when I switch off my firewall, and with v2/v3 services, and with stealth hidden services.

**Comment by n8fr8** [comment]
>BTW why is version 16.3.0 32 MB, but 16.1.4 only 10 MB??

Hmm.... 32MB must be the "universal" build which contains all the architecture binaries (ARM, X86 32 and 64 bit). I think before we were just distributing the armeabi/32 bit binaries as our "default" release.
