### ISSUE TITLE
An equivalent for desktop PC ?

### ISSUE THREAD

**Issue by stemy2** [guardianproject/orbot#393]
Hello,

I'm using regularly orbot on m'y phone ans it works well. But i'd like to use a similar app on my phone. Are you planning to develop orbot for PC ? Is there a PC app that does the dame as orbot ?

**Comment by n8fr8** [comment]
Please see Tor Browser from https://www.torproject.org/

**Comment by n8fr8** [comment]
(or did you mean more the VPN functionality?)

**Comment by stemy2** [comment]
> (or did you mean more the VPN functionality?)

Yes, i'd like to have all my connection through tor, and not only the browser.

**Comment by bitmold** [comment]
There are a lot of ways you can go with this and probably a lot of specific concerns to address given your operating system, what your PC is doing, etc. But a good first step might be to take a look at Whonix https://www.whonix.org/

**Comment by ValZapod** [comment]
Just use tor console and SOCS 5 with SwitchOmega.
