### ISSUE TITLE
Empty Notification Text 

### ISSUE THREAD

**Issue by bitmold** [guardianproject/orbot#398]
Orbot shows an empty notification to the user that doesn't convey anything to the user and looks sort of suspicious. 

This happens because when the app is launched, `OrbotService` is automatically started which displays an empty notification with this line in `onStartCommand()`. 

```java
showToolbarNotification("", NOTIFY_ID, R.drawable.ic_stat_tor);
```

Getting rid of this line will remove the confusing notification, `OrbotService` will instead `showToolBarNotification` only when meaningful events occur concerning the tor connection itself, and not merely because an Android Service was initiated. 

The app can also be put into an inconsistent state where the user sees this empty notification when they first launch the app. Eventually they start and stop tor, and remain within the Orbot app. Since `OrbotService` will be stopped, the notification will be gone even though the user just saw the empty notification when tor wasn't running.

**Comment by bitmold** [comment]
Another reason why I propose getting rid of this line is because the preference for always on notifications reads:

> Always keep the icon in the toolbar when Orbot is connected 

Users will likely be confused upon encountering a notification (that conveys nothing) that should mean Orbot is connected/connecting when Orbot is **not** in fact not connected

**Comment by bitmold** [comment]
Some screenshots: 

Orobt when first launched and no tor connection is attempted: 

Main screen:
![image](https://user-images.githubusercontent.com/22125581/95271813-d0c2f700-080c-11eb-9baa-6859df1b4800.png)

Expanded Notification (empty):
![image](https://user-images.githubusercontent.com/22125581/95271855-f3eda680-080c-11eb-8fa0-213aeffb7300.png)


And ya, from here if you start and then stop tor, you won't get the empty notification on the main screen.

**Comment by ValZapod** [comment]
> Users will likely be confused upon encountering a notification (that conveys nothing) that should mean Orbot is connected/connecting when Orbot is **not** in fact not connected

No. This is not that. A notification must be present so that Android will not be able to too simple (it can still do it) close the app.

But yeah, it is buggy. IP and countries do not work either.
