### ISSUE TITLE
Orbot does not work it target API is updated to 29

### ISSUE THREAD

**Issue by BeAnonymousTech** [guardianproject/orbot#403]
By November 2, 2020, all apps that are being updated must target at least Android 10 (API level 29). On most modern devices that support compressed native libraries the CustomTorResourceInstaller class currently copies the libtor.so binary to the apps internal home directory and OrbotService.exec() executes the it as a shell command. Unfortunately the execute permission has been removed from the home directory in Android 10 and this will not loner work. 

CusomTorResourceInstaller.java, line 143, will copy the binary to an unelectable path.

        //let's try another approach
        fileTor = CustomNativeLoader.loadNativeBinary(context, TOR_ASSET_KEY, fileTorBin);

https://developer.android.com/about/versions/10/behavior-changes-10#execute-permission

https://stackoverflow.com/questions/62391811/android-10-alternative-to-launching-executable-as-subproccess-stored-in-app-ho

https://github.com/termux/termux-app/issues/1072

**Comment by n8fr8** [comment]
Thanks for the help, but we don't use the CusomTorResourceInstaller except on older devices where we can't find/execute the libtor.so as automatically extracted by the JNI loader.

**Comment by in-sohelrana** [comment]
My app same issue how to solve

**Comment by in-sohelrana** [comment]
Same Issue my side, when I test in debug or release apk in my mobile then working fine, but when I publish that same apk in play console, after i install through play store then app open and closed soon. what the reason ? please solve this issue, I have browser application  which have orbot services used.

**Comment by n8fr8** [comment]
We have a new RC 1 out and also a newer beta:
https://github.com/guardianproject/orbot/releases/tag/16.3.3-BETA-1-tor-0.4.3.6

We are not seeing this issue in either.
