### ISSUE TITLE
[Feature request] Desktop PC version

### ISSUE THREAD

**Issue by stemy2** [guardianproject/orbot#405]
Hello,

I'd like to use a Tor VPN on my PC because i i don't trust common VPN providers. Is there a PC equivalent to orbot ? If not, could you build it ?

**Comment by bitmold** [comment]
Hi, I'm closing this issue because it's beyond the scope of this project, but for your PC I would encourage you to look into the TAILS operating system which comes with a lot of tight knit security features and forces your PC's traffic to go through Tor 

https://tails.boum.org

**Comment by stemy2** [comment]
Tails works only with preinstalled apps, the apps i'm installing myself after installing tails can't connect to internet at all, so this is not exactly what i'm looking for.

But thanks for trying to help me.

**Comment by Pantyhose-X** [comment]
> Hi, I'm closing this issue because it's beyond the scope of this project, but for your PC I would encourage you to look into the TAILS operating system which comes with a lot of tight knit security features and forces your PC's traffic to go through Tor
> 
> https://tails.boum.org

Desktop is a must, no one is going to have a browser open running the [Snowflake extension](https://chrome.google.com/webstore/detail/snowflake/mafpmfcccpbjnhfhjnllmmalhifmlcie) for long.

If there is a desktop we can play games, read files, etc., running Snowflake helps people in censored countries bypass censorship, without having to open a browser

In censorship countries, bridges other than Snowflake are basically dead.
