### ISSUE TITLE
Can't enable VPN mode

### ISSUE THREAD

**Issue by MyNameIsOka** [guardianproject/orbot#406]
Hello community,

I played around with Orbot and I can connect to the TOR network but the VPN mode button is not working.
Whenever I tap it, it switches back to OFF after a split second.
I don't see any error or logs or anything. Googling didn't get any results.
I am also not getting a popup to configure the VPN settings in the Android OS when initially tapping the VPN mode button.

Do you guys know what the issue could be?
Appreciate your help!

Specs:
OnePlus5 Android 10
Orbot 16.3.2-RC-1-tor-0.4.3.6
Using NordVPN in parallel

**Comment by MyNameIsOka** [comment]
Switching to version 16.1.3-BETA-2-tor-0.4.1.6-rc solved the issue for me. The other versions after that are all not working.

**Comment by n8fr8** [comment]
How do you " Using NordVPN in parallel" ? You can only run one VPN at a time.

**Comment by MyNameIsOka** [comment]
Sorry, my statement wasn't clear. 
I just wanted to say that I am using NordVPN. I thought that maybe NordVPN would make trouble during the VPN Configuration of Orbot.

**Comment by n8fr8** [comment]
Do you have the ability to capture adb logcat output? You can also enable DEBUG in Orbot settings, and look for messages in the right-hand swipe out drawer.

**Comment by explorer422** [comment]
> I just wanted to say that I am using NordVPN. I thought that maybe NordVPN would make trouble during the VPN Configuration of Orbot.
Sorry, I don't quite get it. Do you mean that you have both software installed but you encountered the problem when you use only Orbot or you encountered the problem when enable both of them?
One more thing, you can go to the VPN setting in your phone(not the software) and see if you turned on something like "Always-on VPN " or "Block Connection Without VPN".

**Comment by bitmold** [comment]
We can probably close this, but first I want to experiment with what the UI does when you try to start Orbot with another Android VPN Service running...

**Comment by m-alice** [comment]
Hello, i have a protonvpn and orbot installed together. Face same problem. The solution is switch "always on" for the orbot in android vpn settings (settings -> network and internet -> vpn -> orbot -> [gear button] -> always on)
![image](https://github.com/guardianproject/orbot/assets/7101860/dc5a24d6-791a-4a9c-a61b-df0fa35a48c9)
