### ISSUE TITLE
Orbot working just with https urls

### ISSUE THREAD

**Issue by cenapatop** [guardianproject/orbot#408]
On bromite browser orbot working just with https address.

it is not working with urls without ssl

**Comment by n8fr8** [comment]
Are you using bromite browser via the HTTP proxy in Orbot? Can you try using it with the SOCKS proxy or the Orbot VPN?

**Comment by annihat** [comment]
It sounds like this is related – 

I'm getting this message in Orweb & Privacy Browser after updating from (F-Droid) Orbot v15.1.2 to v16.3.2-RC-1-tor-0.4.3.6 
I did not alter any settings during the update & I think the proxy settings are at defaults in Orbot, Orweb & Privacy Browser. All seem to use http proxy on port 8118. There seem to be no settings anywhere about "CONNECT tunnel", just "HTTP proxy". 
It worked before the update...

"This is an HTTP CONNECT tunnel, not an HTTP proxy.

It appears you have configured your web browser to use this Tor port as an HTTP proxy.

This is not correct: This port is configured as a CONNECT tunnel, not an HTTP proxy. Please configure your client accordingly. You can also use HTTPS; then the client should automatically use HTTP CONNECT.

See https://www.torproject.org/documentation.html for more information."

**Comment by n8fr8** [comment]
You no longer need to use the HTTP proxy setting. Just use the Orbot VPN and all traffic, be it HTTP or HTTPS or anything, will be proxied through Tor.

Otherwise, yes the HTTP port on Tor is now HTTP Connect, which means it only supports HTTPS urls, and not plain HTTP. This is also better for security, of course.

**Comment by annihat** [comment]
Nope. 
Not fixed. 
I've just turned on 'VPN mode' & the http://....onion addresses I have still don't work in Orweb or Privacy Browser. The error message appears to be the same – 
"This is an HTTP CONNECT tunnel, not an HTTP proxy.

It appears you have configured your web browser to use this Tor port as an HTTP proxy.

This is not correct: This port is configured as a CONNECT tunnel, not an HTTP proxy. Please configure your client accordingly. You can also use HTTPS; then the client should automatically use HTTP CONNECT.

See https://www.torproject.org/documentation.html for more information."

**Comment by annihat** [comment]
None of these addresses work in either browser
http://xmh57jrzrnw6insl.onion/ 
http://msydqstlz2kzerdg.onion/search/?q= 
http://hss3uro2hsxfogfq.onion/

**Comment by annihat** [comment]
Changing 'proxy type' & 'proxy port' in Orweb to 'socks' & '9050' produces –

"This is a SOCKs proxy, not an HTTP proxy.

It appears you have configured your web browser to use this Tor port as an HTTP proxy.

This is not correct: This port is configured as a SOCKS proxy, not an HTTP proxy. If you need an HTTP proxy tunnel, use the HTTPTunnelPort configuration option in place of, or in addition to, SOCKSPort. Please configure your client accordingly.

See https://www.torproject.org/documentation.html for more information."

**Comment by annihat** [comment]
This move forces the use of VPN mode, which forces all internet traffic through Tor. 

This might be good with some, carefully tailored, devices but Android is designed & set up to extend Google's personal tracking service. 

Google's data is sold to third parties. 

The internet traffic emanating from your device is designed to track you. 

Forcing VPN mode destroys the purpose of Tor.

**Comment by annihat** [comment]
This move forces the use of VPN mode, which forces all internet traffic through Tor. 

This might be good with some, carefully tailored, devices but Android is designed & set up to extend Google's personal tracking service. 

Google's data is sold to third parties. 

The internet traffic emanating from your device is designed to track you. 

Forcing VPN mode destroys the purpose of Tor. 

@n8fr8 please rescind this change

**Comment by annihat** [comment]
This move forces the use of VPN mode, which forces all internet traffic through Tor. 

This might be good with some, carefully tailored, devices but Android is designed & set up to extend Google's personal tracking service. 

Google's data is sold to third parties. 

The internet traffic emanating from your device is designed to track you. 

Forcing VPN mode destroys the purpose of Tor. 

@n8fr8 please rescind this change

**Comment by alanthehat** [comment]
@n8fr8 it strikes me that reverting to a 5 year old version of `Orbot` is more of a security hole than allowing `http` for the final hop from `Tor` into the open internet when using locked-down browsers. The first & intermediate hops are encrypted by `Tor` as part of the protocol. 

Plus, it disallows the current version of `Tor` because it's unsupported by the old `Orbot` version, this cannot be an improvement to security.

Your 'solution' of using `VPN-mode`, as @annihat says, drags the entire `Android spyware ecosystem` through `Tor`, breaking many of the purposes of using `Tor` in the first place. Plus, it drags `Bittorrent` & other high-bandwidth services through a narrow bandwidth system, overloading it's services. 

@cenapatop was correct to start this `issue`

**Comment by alanthehat** [comment]
It looks like `Tor` will cease to function entirely in October this year unless this issue is sorted out because `Orbot v16` simply does not work for me, meaning that `Tor V3 addresses` are inaccessible (or unless I can figure out how to use the instance of `Tor` within `Termux`)
https://thehiddenwiki.com/new-long-v3-onion-services-version-3-hidden-service-links-on-the-hidden-wiki/

**Comment by alanthehat** [comment]
> None of these addresses work in either browser
> http://xmh57jrzrnw6insl.onion/
> http://msydqstlz2kzerdg.onion/search/?q=
> http://hss3uro2hsxfogfq.onion/

`Torch`, `Ahmia` & `Not Evil` search engines respectively.

`Torch` has a `V3 address` notification, 
`Ahmia` still works & 
`Not Evil` is unresponsive.

**Comment by n8fr8** [comment]
If you need to brows to Onion addresses, please Tor Browser for Android. That is the official web browser for Tor on Android. It uses the Gecko browser engine, built on Firefox/Tor Browser desktop code, which handles the onion resolution as expected.

If you MUST use a separate browser with Orbot VPN, then use Firefox Focus which also handles onion address resolution.

**Comment by n8fr8** [comment]
As for this comment "Your 'solution' of using VPN-mode, as @annihat says, drags the entire Android spyware ecosystem through Tor, breaking many of the purposes of using Tor in the first place. Plus, it drags Bittorrent & other high-bandwidth services through a narrow bandwidth system, overloading it's services"

Orbot allows you to CHOOSE SPECIFIC APPS to route through Tor. You don't have to run the entire device.

**Comment by eighthave** [comment]
Privacy Browser should use SOCKS to connect to Orbot/Tor, then HTTP will work fine.  Or it can use NetCipher 2.2.0-alpha to handle setting up the SOCKS stuff.

**Comment by alanthehat** [comment]
You forget that this is `Android`, the OS where **nothing** works properly, using a single `web browser` is simply not an option.

Plus, `web browsing` is _not_ the only function of the internet or even of _http(s)_ & narrowing down to a `single web browser` does not make any difference whatsoever to all the other internet functions which may or may not wish to use Tor. 

This, for instance, is `F-Droid` appstore where I get `Orbot` from – 
![Screenshot_2021-05-09-09-34-59-26_66a3b1c2c181ff92b8bf945e748b6fb7](https://user-images.githubusercontent.com/7391459/117565604-003f2800-b0aa-11eb-9f4c-d339049fe278.jpg)

This is the first full paragraph in README.md - 
> ...provides an HTTP Proxy for connecting web browsers and other HTTP client applications into the Tor SOCKS interface
 
– blatantly this issue negates this & with no explanation 
> n8fr8 commented:
> ...This is also better for security, of course 

 is an assertion, an unsupported assertion, not an explanation 

I (& presumably others) am absolutely fed up of ***improvements*** making everything worse & often, as here, unusable! Just _please_ put it back, _please_!

**Comment by alanthehat** [comment]
I have ***zero*** interest in the arcanities of security or networking esoterica, all I want is to disrupt as much as possible the democracy-destroying psychographic profiling of Google, Facebook & others that gave my country a trashed economy with food & medicine shortages (not yet serious but they will be), a right-wing government that's happily killing thousands of it's citizens, the worst record so far with COVID & looks like it might start World War Three before it's finished. 

Just restore `Orbot` to a functioning form _please_, we are just asking you to put something back that you took out, we're not asking you to rewrite the whole app.
