### ISSUE TITLE
Simplest way to host a website using Orbot?

### ISSUE THREAD

**Issue by elimisteve** [guardianproject/orbot#414]
Hi @n8fr8, I've admired your cypherpunk work for some time :+1: . I'm considering building a mobile app that lets people host simple .onion websites on their phones. Questions:

1. Can Orbot be easily bundled into an Android app?

2. Is there functionality already in Orbot to respond to an incoming request by serving index.html et al, or must incoming requests be proxied to another process?

3. Will Orbot ever work on iOS, or is Apple too strict in what they allow apps to do for such a thing to work?

Thanks!

**Comment by n8fr8** [comment]
Hey, there, and thanks!

1. You can bundle Tor Services via a few different third-party libraries. 
https://gitlab.com/guardianproject/torservices/
https://github.com/thaliproject/Tor_Onion_Proxy_Library


2. You can request Orbot to host and start an Onion service via an Intent call, which will host the .onion and redirect traffic to a localhost port. You have to run the web service itself in your app. Our Haven app does this, which you can see here:
https://github.com/guardianproject/haven/blob/master/src/main/java/org/havenapp/main/service/WebServer.java

You can see how to request the Onion service here:
https://github.com/guardianproject/haven/blob/master/src/main/java/org/havenapp/main/SettingsFragment.java#L720

3. We have Onion Browser on iOS (https://github.com/OnionBrowser/OnionBrowser) which is built on Tor.framework: https://github.com/iCepa/Tor.framework - you can build this into your own app and run Onion Services and a web server just like on Android. I don't have any example code of that however.

Good luck!

**Comment by bitmold** [comment]
Closing this because it's not an active issue with Orbot, but please feel free to continue discussing things here @elimisteve

**Comment by elimisteve** [comment]
@n8fr8 Thanks!
