### ISSUE TITLE
RPV doesn't work anymore for some apps

### ISSUE THREAD

**Issue by stemy2** [guardianproject/orbot#418]
Hello,

Since a couple of hours, firefox can't connect to any site if the orbot RPV is enabled, i must disable it to make the browser usable. Other apps like Discord (and maybe some other apps) have a similar problem, but the rest seems to work fine. RPV orbot mode worked fine for them until now, why did it stopped working ?

**Comment by n8fr8** [comment]
what is RPV?

**Comment by stemy2** [comment]
VPN. Sorry, i forgot my app is on french.

Anyway, the problem resolved itself.
