### ISSUE TITLE
v3 Onion Addresses are Base32 encoded (a-z2-7)

### ISSUE THREAD

**Issue by 05nelsonm** [guardianproject/orbot#424]
https://github.com/guardianproject/orbot/blob/1439356d9cc5be4fbd22f4ee421205056f6fc937/app/src/main/java/org/torproject/android/ui/hiddenservices/backup/BackupUtils.java#L53

**Comment by bitmold** [comment]
This is correct! Actually this code doesn't do anything for v3s anywhere so I'm going to delete it, on the v3onions branch of my fork there are tests that make the correct a-z2-7 56 char check. thanks for pointing this out
