### ISSUE TITLE
Orbot on the F-Droid repository is not up to date

### ISSUE THREAD

**Issue by n1m1** [guardianproject/orbot#439]
Hi,
the last Orbot release available on Google Play Store is 16.04.0-RC2 (Tor binary 0.4.4.6) while the one on the F-Droid repo is 16.3.3.RC-1 (Tor binary 0.4.3.6).

Can you please update the F-Droid repository, please? And, if possible, can you **keep** the F-Droid repository up to date, please? Unfortunately it is not the first time that the last version of Orbot is uploaded on F-Droid with a huge delay.

Cheers

**Comment by hefty-fading-culprit-epiphany-drew** [comment]
Please update it soon

**Comment by hefty-fading-culprit-epiphany-drew** [comment]
@n8fr8

**Comment by khassad** [comment]
Unfortunately the situation has worsened : Orbot is no more available on F-Droid :(, what's going on ?

**Comment by n8fr8** [comment]
Please enable the Guardian Project repository in F-Droid settings. We haven't removed Orbot from anywhere.

We posted a new RC release a few days ago:
https://github.com/guardianproject/orbot/releases/tag/16.4.1-RC-1-tor.0.4.4.6

**Comment by BayLee4** [comment]
Hi, even with the Guardian Project repository enabled, the latest version available is still 16.3.3.RC-1 :/

**Comment by alanthehat** [comment]
version still not current 
![version still not current](https://user-images.githubusercontent.com/7391459/116007589-5fac2b00-a608-11eb-80c8-72a037ba4802.jpg)

**Comment by BoBeR182** [comment]
Currently getting 404 error for downloading from fdroid repo.

![Screenshot_20210501-204919_F-Droid](https://user-images.githubusercontent.com/525433/116798560-c45efe00-aabe-11eb-8705-5f86757ea511.png)

**Comment by eighthave** [comment]
@BoBeR182 @n8fr8 @m-p-3 try now, it should be on all the mirrors now.
