### ISSUE TITLE
UK exit node does not exist

### ISSUE THREAD

**Issue by ingfabby** [guardianproject/orbot#440]
From the GP email:

Device:  OnePlus 6

"if I select UK as tor exit server, I get Europe or USA IP addresses."

**Comment by bitmold** [comment]
this functionality isn't broken per se though we ought to have a better user experience

Setting UK through the spinner adds something like this to the torrc:

`ExitNodes {GB}` 

which tells tor to prefer a UK exit node, however the user needs to actually go into Obot's settings and turn on strict nodes such which will add something like this to the configuration: `ExitNode {GB} StrictNodes 1` and actually will force tor to stick with UK exit nodes 


The Spinner UI on the main screen is kinda busted in general. It's not broken per se, but there are more countries than the ones that Orbot lists, and in theory you can have select multiple exit nodes anyway such as `ExitNode {GB}, {RU}` ... etc

**Comment by macerg** [comment]
I concur, in my experience, you get 51.* IP address exit node reliably but not all 51.* range IP addresses are UK addresses. Would be great if this could be sorted. I don't think this would take much effort. Just a simple lookup table.

**Comment by ValZapod** [comment]
Am I an idiot, but country of exit node and IP do no longer work in Orbot status screen?

**Comment by macerg** [comment]
In my experience, you just exit at nodes that have a 51.*.*.* IP address. Could be UK, France or a number of other countries. I've highlighted this to the team but they dismissed it.  Regards,Richard MaceOn 23 Jun 2021 04:03, Valerii Zapodovnikov ***@***.***> wrote:
Am I an idiot, but country of exit node and IP do no longer work in Orbot status screen?

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
@bitmold 
> 
> however the user needs to actually go into Obot's settings and turn on strict nodes such which will add something like this to the configuration: `ExitNodes {GB} StrictNodes 1` and actually will force tor to stick with UK exit nodes
> 

This is all wrong information! You do it wrong.
**StrictNodes applies to neither ExcludeExitNodes nor to ExitNodes, nor to MiddleNodes**

```
StrictNodes 0|1

    If StrictNodes is set to 1, Tor will treat solely the ExcludeNodes option as a requirement to follow for all the circuits you generate, even if doing so will break functionality for you (StrictNodes applies to neither ExcludeExitNodes nor to ExitNodes, nor to MiddleNodes). If StrictNodes is set to 0, Tor will still try to avoid nodes in the ExcludeNodes list, but it will err on the side of avoiding unexpected errors. Specifically, StrictNodes 0 tells Tor that it is okay to use an excluded node when it is necessary to perform relay reachability self-tests, connect to a hidden service, provide a hidden service to a client, fulfill a .exit request, upload directory information, or download directory information. (Default: 0)

```

**Comment by macerg** [comment]
Neither ExitNodes GB with Strictnodes 1 work reliably. In my experience, you always get a 51.* IP address but not necessarily GB (UK). Orbit is unreliable in this respect.  Tor running within Termux works better.Regards,Richard MaceOn 3 Jul 2021 06:59, Bernd Eichelberger ***@***.***> wrote:
@bitmold

however the user needs to actually go into Obot's settings and turn on strict nodes such which will add something like this to the configuration: ExitNodes {GB} StrictNodes 1 and actually will force tor to stick with UK exit nodes

This is all wrong information! You do it wrong.
StrictNodes applies to neither ExcludeExitNodes nor to ExitNodes, nor to MiddleNodes
StrictNodes 0|1

    If StrictNodes is set to 1, Tor will treat solely the ExcludeNodes option as a requirement to follow for all the circuits you generate, even if doing so will break functionality for you (StrictNodes applies to neither ExcludeExitNodes nor to ExitNodes, nor to MiddleNodes). If StrictNodes is set to 0, Tor will still try to avoid nodes in the ExcludeNodes list, but it will err on the side of avoiding unexpected errors. Specifically, StrictNodes 0 tells Tor that it is okay to use an excluded node when it is necessary to perform relay reachability self-tests, connect to a hidden service, provide a hidden service to a client, fulfill a .exit request, upload directory information, or download directory information. (Default: 0)

**Comment by macerg** [comment]
Fixed in latest version. Thanks.

**Comment by macerg** [comment]
closing.
