### ISSUE TITLE
Orbot 16.4.1-BETA-2-tor.0.4.4.6-1-g3fccd4cf does not show non-system apps in the "VPN Mode / Tor-Enabled Apps" menu

### ISSUE THREAD

**Issue by n1m1** [guardianproject/orbot#441]
As per title.

If I click on the "Tor-Enabled Apps" menu I can see system apps (such ass "Phone services", "Settings" and a few more objects) but no non-system apps.

I have tried both "Orbot-16.4.1-BETA-2-tor.0.4.4.6-1-g3fccd4f5-fullperm-arm64-v8a-release.apk" and "Orbot-16.4.1-BETA-2-tor.0.4.4.6-1-g3fccd4f5-fullperm-universal-release.apk".

I am running Orbot on a Pixel 3a with GrapheneOS RQ1A.210205.004.2021.02.19.15 (last stable release).

**Comment by n8fr8** [comment]
I can't reproduce this yet, but will try. Perhaps there is some limitation in Graphene OS on this front, in terms of being able to query what apps are installed?

**Comment by n1m1** [comment]
Hi @n8fr8 !

Just tried again to be sure:
With Orbot 16.3.3-RC1-tor.0.4.3.6 I can see non-system apps in "VPN mode" menu and route them through Orbot. 
With Orbot 16.4.1-BETA-2-tor.0.4.4.6-1-g3fccd4cf I do not see non-system apps in "VPN mode" menu.

Same phone, same GrapheneOS version.

**Comment by n8fr8** [comment]
Thanks for checking. Maybe it was changed related to SDK 30. Which OS/SDK is the version of Graphene you are running based on?

**Comment by n8fr8** [comment]
Here is the issue:
https://developer.android.com/about/versions/11/privacy/package-visibility

**Comment by n1m1** [comment]
> Thanks for checking. Maybe it was changed related to SDK 30. Which OS/SDK is the version of Graphene you are running based on?

Hi, I am very sorry but I am not sure about the answer. For what I can see on[ GrapheneOS' changelog](https://grapheneos.org/releases), they mention SDK 30. 

`"2020.09.18.13 preview: Updater: update targetSdkVersion to 30"`

But again, I am not sure.

**Comment by n8fr8** [comment]
Yeah, I've figured it out. Will push a new beta.

**Comment by n8fr8** [comment]
New beta 3 is up: https://github.com/guardianproject/orbot/releases/tag/16.4.1-BETA-3-tor.0.4.4.6

**Comment by n1m1** [comment]
Fantastic. It works.

I am closing this.
