### ISSUE TITLE
Restoring backup of v3 onion addresses not working

### ISSUE THREAD

**Issue by LinkTroisUn** [guardianproject/orbot#448]
Hi. I generated a new v3 onion service with the latest version of orbot. I checked if I could connect, and it worked. Then, I removed the service from the app and added it again. But now, it seems that the service doesn't start at all.

I checked with v2 services, but the backup restored successfully.

I don't know if the following information can help, but, with v3, creating a new service with the same name as the restored backup, generate a new address for both, while with v2, it keeps the same address.

**Comment by bitmold** [comment]
Hi, thanks for reporting this Orbot's v3 support is new and there are still things to be ironed out with that... Looking into this now

**Comment by bitmold** [comment]
Fixed with https://github.com/guardianproject/orbot/pull/449
