### ISSUE TITLE
unaddressed security problem

### ISSUE THREAD

**Issue by alanthehat** [guardianproject/orbot#453]
There is a security discussion going unaddressed in #408 

@n8fr8 has provided a 'solution' to which objections have been made but there is no response. I believe the `issue` was prematurely closed but either way a response to the points raised would be appreciated.

**Comment by n8fr8** [comment]
I've responded on #408 with more detail.

**Comment by alanthehat** [comment]
> I've responded on #408 with more detail.

..."detail" that doesn't address the issue of getting dozens of apps working again
