### ISSUE TITLE
"Select Apps" checkbox in settings always enabled

### ISSUE THREAD

**Issue by lucabertoni** [guardianproject/orbot#47]
Hi,
reading Orbot code to fix another similar problem, I found out that "Select Apps" checkbox in settings panel is always enabled in Android versions >= Lollipop. Is it correct?
If it is correct, there's a bug because I still need to set the "Transparent Proxying" checkbox checked to let this function work (I'm talking about proxying apps internet traffic through orbot). And you should also have to make the same check here: https://github.com/n8fr8/orbot/blob/master/src/org/torproject/android/settings/SettingsPreferences.java#L174
If it is not correct that the button "Select Apps" is always enabled in Android Versions >= Lollipop, you have just to remove this if statement: https://github.com/n8fr8/orbot/blob/master/src/org/torproject/android/settings/SettingsPreferences.java#L123
I don't understand why the button should always be enabled in Lollipop and latest versions. It should be enabled only if the "Transparent Proxying" checkbox is checked, shouldn't it?

**Comment by bitmold** [comment]
Closing this because the "Select Apps" checkbox isn't even part of Orbot anymore
