### ISSUE TITLE
TorService-debug.log grows out of control and crashes system

### ISSUE THREAD

**Issue by syphyr** [guardianproject/orbot#471]
While testing 16.5.0-ALPHA-2, I've noticed that the debug log ( /data/data/org.torproject.android/cache/TorService-debug.log ) will grow out of control very quickly and make the data partition run out of disk space.  This happens very quickly when downloading any files through the orbot socks proxy.  The debug log grew to 14Gigs on my tablet in a few hours.  We need either an option to disable debug logging or limit the size of the debug log.

**Comment by syphyr** [comment]
Ah, this needs to be fixed in the tor-android repository instead.

diff --git a/tor-android-binary/src/main/java/org/torproject/jni/TorService.java b/tor-android-binary/src/main/java/org/torproject/jni/TorService.java
index 2a10acb4..b34cef70 100644
--- a/tor-android-binary/src/main/java/org/torproject/jni/TorService.java
+++ b/tor-android-binary/src/main/java/org/torproject/jni/TorService.java
@@ -330,7 +330,6 @@ public class TorService extends Service {
 
                             // can be moved to ControlPort messages
                             "--LogMessageDomains", "1",
-                            "--Log", "debug file " + new File(getCacheDir(), TAG + "-debug.log").getAbsolutePath(),
                             "--TruncateLogFile", "1"
                     ));
                     String[] verifyLines = lines.toArray(new String[0]);

**Comment by syphyr** [comment]
This debug log also causes very high cpu usage for normal users.

**Comment by syphyr** [comment]
https://github.com/guardianproject/tor-android/pull/40

**Comment by syphyr** [comment]
Fixed

**Comment by SkewedZeppelin** [comment]
After a few hours on a fresh install of Orbot-16.5.1-BETA-2a-tor.0.4.5.9-fullperm-arm64-v8a-release.apk app cache is at 40MB and climbing.
My device is not rooted, so I cannot inspect its contents.

**Comment by syphyr** [comment]
> After a few hours on a fresh install of Orbot-16.5.1-BETA-2a-tor.0.4.5.9-fullperm-arm64-v8a-release.apk app cache is at 40MB and climbing.
> My device is not rooted, so I cannot inspect its contents.

The debug log for the tor service is no longer created, but there is still a debug log for pdnsd that is created.

**Comment by SkewedZeppelin** [comment]
Guess that should be disabled too then.
It is up to 65MB now.
