### ISSUE TITLE
Exclude Briar from full device VPN

### ISSUE THREAD

**Issue by akwizgran** [guardianproject/orbot#474]
The Briar messaging app includes its own copy of Tor, which is unable to connect to the Tor network when Orbot is providing a full device VPN. Please exclude Briar from the list of affected apps when providing a full device VPN.

Ideally, please also exclude Briar from the list of Tor-enabled apps when VPN mode is enabled for selected apps, as selecting Briar in this list breaks Briar's Tor connectivity.

**Comment by grote** [comment]
If excluding it from the list of selectable apps is too much, one could also disable it in the list, so it can't be selected. Alternatively, one could also show a general warning when selecting apps like Briar: Selecting this app is going to break its functionality. Are you sure you want to proceed?
