### ISSUE TITLE
Use Maxmind or IPFire geoip location database?

### ISSUE THREAD

**Issue by syphyr** [guardianproject/orbot#479]
I've noticed that Orbot is currently using a geoip location database from Maxmind GeoLite2 Country (https://mvnrepository.com/artifact/info.guardianproject/geoip/20191217).  But, the Tor project has moved away from using Maxmind in favor of IPFire's location database (https://location.ipfire.org/).  Shouldn't Orbot be using the same location database as Tor?  The main reason for the switch to IPFire seems to be a licensing issue, but there also seems to be security issues as well.

**Comment by ValZapod** [comment]
> licensing issue,

What are they going to do, sue us? LOL. Anyway, Maxmind is the best in the world. It is funny not to use it.

> Orbot be using the same location database as Tor

In what way does Tor itself use it?

**Comment by syphyr** [comment]
> > Orbot be using the same location database as Tor
> 
> In what way does Tor itself use it?

Tor requires updated geoip data to determine what county the tor node is located. Currently, Orbot's geoip data has not been updated in over two years. Official Tor sources have current geoip data.

**Comment by bitmold** [comment]
@syphyr can you point to where tor project uses the ipfire geoip databases

**Comment by bitmold** [comment]
Nevermind, I found README.geoup in the tor repository:

> To generate new geoip files, you'll need to install the
> libloc/"location" tool provided by https://location.ipfire.org/.
> I personally build it with:
> 
>   ./configure CFLAGS='-g -O2' --disable-perl --without-systemd --prefix=/opt/libloc
>   make
>   make install
> 
> Then (after adjusting PATH and PYTHONPATH) you can get the latest
> dump with:
> 
>   location update
>   location dump geoip-dump.txt
> 
> And transform it into geoip files with
> 
>   cargo run --release -- -i geoip-dump.txt
> 
> 
> ==============================
> 
> Note that the current version "0.1.9" of rangemap has a performance
> bug, making this tool quite slow.  Previous versions had a
> correctness bug that made the output needlessly long.  With luck,
> there will soon be a fast correct rangemap version.

**Comment by syphyr** [comment]
> @syphyr can you point to where tor project uses the ipfire geoip databases

When building Orbot, I have been creating geoip.jar using the geoip databases from tor's official sources.

```
cp -a ../tor-android/external/tor/src/config/geoip assets/
cp -a ../tor-android/external/tor/src/config/geoip6 assets/
zip -o geoip.jar assets/geoip assets/geoip6
```

**Comment by bitmold** [comment]
Thanks I have a new geoip.jar here https://github.com/guardianproject/orbot/pull/685 - waiting on Nathan and the others to review but hopefully a release soon :)

**Comment by n8fr8** [comment]
@eighthave can we update the info.guardianproject:geoip to use ipfire? Maybe we can give @bitmold access to manage this?

**Comment by bitmold** [comment]
Using the script I put here you can generate a jar file based on the contents of the tor repository

**Comment by irl** [comment]
(or just get the pre-built files from https://tpo.pages.torproject.net/network-health/metrics/geoip-data/ - which is what the CI generates)

**Comment by eighthave** [comment]
@syphyr @n8fr8 @bitmold please test these geoip Maven artifacts:

https://gitlab.torproject.org/eighthave/geoip-data/-/packages/3

These are produced by:
https://gitlab.torproject.org/tpo/network-health/metrics/geoip-data/-/merge_requests/4
