### ISSUE TITLE
Orbot often crashes when Network situation changes

### ISSUE THREAD

**Issue by vanitasvitae** [guardianproject/orbot#48]
Hi!
Unfortunately I find Orbot barely usable at the moment.
Orbot often crashes when my network situation changes. When I'm on the road and I lose mobile signal, Orbot often seems to be unable to handle that. Sometimes the notification icon changes to the "problem-icon" and when I open Orbot, the onion is either yellow, hanging at "Starting Orbot", or sometimes even plain gray.
Also sometimes Orbot seems to crash completely. The vpn-key is still shown (I'm using the VPN feature), but the Orbot icon is vanished from the notification area.

Whenever Orbot has such problems, I have to force kill and restart it in order to get it back to work. 

I wish I could provide some logs, but I can barely manage to reproduce this with a logcat running :disappointed: 

I'm running CopperheadOS (latest version for Nexus 5) and installed Orbot from FDroid (guardianproject repo). 

PS: I hope, I'm using the right issue tracker now :)

**Comment by neoretix** [comment]
Try turn off "tor auto sleep" feature. It worked for my case.

**Comment by n8fr8** [comment]
This is definitely the easiest issue tracker to use, so happy to have your reports here. We are working with Tor to try and unify and simplify this moving forward.

Can you try this build: https://guardianproject.info/releases/Orbot-v15.1.3-beta-1.apk

I think the one in our repo doesn't include this beta release.

**Comment by n8fr8** [comment]
Also, the VPN definitely is the most susceptible to issues related to network changes. Try not using that for now, and see if it is any better.
