### ISSUE TITLE
How can I make orbot allow connection to devices in lan?

### ISSUE THREAD

**Issue by wafles38** [guardianproject/orbot#480]
I couldn't find an answer to this. I want my browser to use orbot, but when I use orbot I am unable to connect to websites in my lan, such as pihole, syncthing, resilio sync, among others.

Is there any way I can make this work?
I did notice this also happens when I use another device as my proxy for my computer, but when I use switchyomega, I am able to connect to my Pihole, it has a whitelist that includes "127.0.0.1, ::1, localhost, 192.168.*".

**Comment by bitmold** [comment]
Closing because the open proxy on all interfaces feature works again. 

Devices on your LAN and connect to the SOCKS port on the IP address of your device running Orbot to reach Tor
