### ISSUE TITLE
Orbot can't auto start on system boot

### ISSUE THREAD

**Issue by neoretix** [guardianproject/orbot#49]
1) Everything is allowed for this app in system settings including autostart. But autostart NEVER WORK on android 6.0. On android 5.1 autostart worked in normal mode. This is URGENT for me. HELP HELP!

2) "tor auto sleep" feature often cause routing errors and internet hangs (only restart of orbot can fix it) and I always turn it OFF.

My device is "Highscreen boost 3 pro". I have latest stable OFFICIAL firmware on android 6.0 and root (from twrp).

**Comment by n8fr8** [comment]
Autostart is working on Android 6 and 7 with Nexus, Moto and others.

When you say "everything is allowed" what do you mean?

Also is Orbot perhaps installed on the SD Card? If so, move to internal storage.
