### ISSUE TITLE
Test (and update to) latest IPtProxy changes

### ISSUE THREAD

**Issue by tladesignz** [guardianproject/orbot#496]
https://github.com/tladesignz/IPtProxy/releases/tag/1.1.0
https://github.com/tladesignz/IPtProxy/blob/master/CHANGELOG.md
https://github.com/tladesignz/IPtProxy/pull/10

Client seems to work on iOS. Please test client and esp. proxy, which had some more changes!

**Comment by bitmold** [comment]
IPtProxy 1.2.0 has been in Orbot for a while now. To be safe I just tested all of its features within Orbot and it looks good to me
