### ISSUE TITLE
Firefox does not show on the VPN list

### ISSUE THREAD

**Issue by ingfabby** [guardianproject/orbot#498]
Android 11
Galaxy 20

When I select Firefox from the VPN mode list it doesn't show on the Tor-Enabled Apps list.[
![Screenshot_20210702-133102_Orbot](https://user-images.githubusercontent.com/28932186/125909474-57d73e66-991f-4445-9d0d-74d30934645e.jpg)
](url)

**Comment by bitmold** [comment]
Firefox will go through the Tor VPN if it is selected, it's just not rendering on the main screen (alongside other apps)...
