### ISSUE TITLE
Master Build Breaks on Lint Error

### ISSUE THREAD

**Issue by sisbell** [guardianproject/orbot#503]
String.format string doesn't match the XML format string. This check error occurs in the OrbotVpnManager class.

[lint-results.html.zip](https://github.com/guardianproject/orbot/files/6912831/lint-results.html.zip)

**Comment by sisbell** [comment]
Regression caused by https://github.com/guardianproject/orbot/commit/93bf7b24b14d74e1b628b3ac544f62b1c2b1ed46

**Comment by bitmold** [comment]
Thank you so much for finding + fixing this! I am sorry to say I ended up fixing it when I came across it via `c3f2395d4aeed32e7d2baab7fbccde98c544d9f5`, I didn't get around to reading this issue or your pull request yet otherwise I would have merged it.
