### ISSUE TITLE
Add "Device Specific" label to issue tracker

### ISSUE THREAD

**Issue by sisbell** [guardianproject/orbot#506]
It would be helpful to add labels: 

- "Device Specific" (or something similar) 
-  "Version Specific" 

for the issue tracker.  This would help determine the severity of a bug, with general bugs being more critical.

**Comment by sisbell** [comment]
I think also adding labels for app types: main, tv, mini would be helpful.

**Comment by bitmold** [comment]
For now I've added labels for each of the app types
