### ISSUE TITLE
guardianproject.info

### ISSUE THREAD

**Issue by Dmole** [guardianproject/orbot#516]
orbit is a mobile app but the README.md links to https://guardianproject.info
which is not usable on mobile (menu is off screen)
![Screenshot_20210817-062850_Fennec](https://user-images.githubusercontent.com/1793802/129711310-c3a12e17-2cef-43f5-b6b1-ccd83ce31ad7.png)

**Comment by bitmold** [comment]
This issue is reported on the repo for the website: https://gitlab.com/guardianproject/info/-/issues/2 

I'm closing this since it doesn't pertain to Orbot itself, but thank you for bringing this up.
