### ISSUE TITLE
Orbot doesn't exit itself completely

### ISSUE THREAD

**Issue by corkia1** [guardianproject/orbot#519]
1. Open Orbot

2. Orbot icon appears in above notification bar

3. Tap 3-dot and "Exit"

4. Orbot icon is still there

**Comment by bitmold** [comment]
It seems like this issue only exists if Orbot is **not** connected to tor. If a connection is established clicking the three dots seems to remove the icon.

If orbot is in the process of establishing a connection to tor the icon will also go away.

**Comment by cimarronline** [comment]
I was having this issue also, but it seems to be fixed in the newest release, Orbot 16.5.2-BETA-1-tor.0.4.6.7. Thanks!
