### ISSUE TITLE
“Open Proxy on All Interfaces” has no effect in latest release (7-Oct-2021)

### ISSUE THREAD

**Issue by Deathtanium** [guardianproject/orbot#530]
As noted in issue #317, despite enabling this setting, the proxy adress is still 127.0.0.1 instead of 0.0.0.0.

**Comment by rhystedstone** [comment]
This issue is still present in `16.5.2-RC-5 tor.0.4.6.9`

**Comment by bitmold** [comment]
Thanks, looking into this now. 

Closing this ticket since it's a duplicate of the admittedly old #317
