### ISSUE TITLE
library "libtun2socks.so" not found

### ISSUE THREAD

**Issue by sahabuddinsk** [guardianproject/orbot#545]
Please solve this issue when run this project in my windows system then this problem "library "libtun2socks.so" not found", I trying to install library but there was a issue 

[armeabi-v7a] Install        : pdnsd => libs/armeabi-v7a/pdnsd
make: *** No rule to make target 'D:/AndroidAPP/orbot-master/orbotservice/src/main/jni/../../../../external/badvpn/base/BLog_syslog.c', needed by 'D:\AndroidAPP\orbot-master\orbotservice\src\main/obj/local/armeabi-v7a/objs/tun2socks/__/__/__/__/external/badvpn/base/BLog_syslog.o'.  Stop.

or

Android NDK: WARNING: APP_PLATFORM android-16 is higher than android:minSdkVersion 1 in D:\AndroidAPP\orbot-master\orbotservice\src\main/AndroidManifest.xml. NDK binaries will *not* be compatible with devices older than android-16. See https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md for more information.
[armeabi-v7a] Install        : pdnsd => libs/armeabi-v7a/pdnsd
make: *** No rule to make target 'D:/AndroidAPP/orbot-master/orbotservice/src/main/jni/../../../../external/badvpn/base/BLog_syslog.c', needed by 'D:\AndroidAPP\orbot-master\orbotservice\src\main/obj/local/armeabi-v7a/objs/tun2socks/__/__/__/__/external/badvpn/base/BLog_syslog.o'.  Stop.

**Comment by bitmold** [comment]
This seems like you haven't followed all of the Windows instructions in [BUILD.md](https://github.com/guardianproject/orbot/blob/master/BUILD.md) --- have you installed all of the submodules and ran the `ren` commands after `ndk-build`?

I recently built a working Orbot fine on a Windows machine
