### ISSUE TITLE
Can I upload the app on my Play Store?

### ISSUE THREAD

**Issue by albomenti** [guardianproject/orbot#547]
The question is simple, 
Can I reskin the app and upload on my Play Store account ? The credits and license will be given to this app

**Comment by bitmold** [comment]
Why do you want to do this? I personally don't approve, but even if it's something everyone agreed to [it's likely that Google wouldn't even allow you to do it anyway](https://support.google.com/googleplay/android-developer/answer/9888072?hl=en)
