### ISSUE TITLE
Can't compile Tor

### ISSUE THREAD

**Issue by kithack** [guardianproject/orbot#56]
I can't compile Tor for ARM using the orbot repository. I cloned the repository, ran `git submodule update --init --recursive`, set up the ANDROID_NDK_HOME and ran `make -C external`. The error message is (during configure of Tor)

`checking for openssl directory... configure: WARNING: Could not find a linkable openssl.  If you have it installed somewhere unusual, you can specify an explicit path using --with-openssl-dir
configure: WARNING: On Debian, you can install openssl using "apt-get install libssl-dev"
configure: error: Missing libraries; unable to proceed.
Makefile:233: recipe for target 'tor/Makefile' failed
make: *** [tor/Makefile] Error 1`

Running `make -C external openssl` finishes fine and leaves libcrypto.a and libssl.a in lib.
I also confirmed that configure is run with --with-openssl-dir.

Any ideas what goes wrong here?

**Comment by arrase** [comment]
On Debian, you can install openssl using "apt-get install libssl-dev", in other linux flavour just search for the package who installs the ssl headers

**Comment by n8fr8** [comment]
Yes, it could be that there is still some dependency on your local environment, outside of the code we provide in the package itself.

Are you on Debian?

**Comment by kithack** [comment]
Yes I am using Debian. The package libssl-dev is already installed.

**Comment by nAkhmedov** [comment]
NAVRUZs-MacBook-Pro:orbot navruz$ make -C external
Makefile:66: /Users/navruz/install/android-ndk-r13b//toolchains/arm-linux-androideabi-4.9/setup.mk: No such file or directory
make: *** No rule to make target `/Users/navruz/install/android-ndk-r13b//toolchains/arm-linux-androideabi-4.9/setup.mk'.  Stop.

**Comment by goapunk** [comment]
@nAkhmedov You need to use an older ndk, 10e works, not 13b - or modify the Makefile.
