### ISSUE TITLE
Download & upload speed stuck at 0KiB

### ISSUE THREAD

**Issue by anwar-alsilwy** [guardianproject/orbot#573]
Hi,
I'm using Android 5.0 armv7a
With Latest release 16.5.2.rc5-tor.0.4.6.9.
In orbot UI the downlod & upload speed not working at all and stuck on 0 KiB even if I connected to Tor,
It's also not showing any thing on notification bar.
See below:
![Screenshot_2022-01-12-15-52-00-1](https://user-images.githubusercontent.com/71539261/149148310-5736b1d5-58c4-4e05-92bf-ef9526d2efc4.jpg)

![Screenshot_2022-01-12-15-53-39-1](https://user-images.githubusercontent.com/71539261/149148341-1a51e2ab-7b90-4798-afd3-35edb7b67e1e.jpg)

So, I came back to version 16.4.1-rc2-tor.0.4.4.6 at the moment.

**Comment by bitmold** [comment]
Thanks for reporting this, this should be fixed in an upcoming release...
