### ISSUE TITLE
Move tun2socks VPN code to use Leaf

### ISSUE THREAD

**Issue by n8fr8** [guardianproject/orbot#584]
We now Leaf is a modern way to do VPN/TUN interface binding into Tor, and it works on iOS thanks to @tladesignz 
https://github.com/eycorsican/leaf

It can also work on Android:
Android version: https://github.com/DdVwl6Fj3a/aleaf

Let's replace Orbot's tun2socks and pdnsd code with Leaf!

**Comment by bitmold** [comment]
@n8fr8 @tladesignz 

I remember in the chat you were saying you had issues building aleaf. I was too. I had always used the latest NDK toolchain in the SDK Manager in Android Studio `23.1.7779620`

And this failed. Installing `20.1.5948944`, setting `NDK_HOME` to point at that, worked. I was able to compile the rust code successfully with (from within aleaf): 
`./app/src/main/rust/leaf-android/build.sh debug `

**Comment by tladesignz** [comment]
For reference, this is how we start and control Leaf in Orbot iOS:

https://github.com/guardianproject/orbot-ios/blob/main/Shared/Tunnel/LeafPTProvider.swift
https://github.com/guardianproject/orbot-ios/blob/main/Shared/template.conf

As you can see, it is completely done via a config file.

**Comment by syphyr** [comment]
> @n8fr8 @tladesignz
> 
> I remember in the chat you were saying you had issues building aleaf. I was too. I had always used the latest NDK toolchain in the SDK Manager in Android Studio `23.1.7779620`
> 
> And this failed. Installing `20.1.5948944`, setting `NDK_HOME` to point at that, worked. I was able to compile the rust code successfully with (from within aleaf): `./app/src/main/rust/leaf-android/build.sh debug `

NDK 21.4.7075529 also builds successfully

**Comment by bitmold** [comment]
Thanks, i'll post further findings here

**Comment by bitmold** [comment]
Posting this here for when I get back on later https://dawnarc.com/2016/10/android-ndk-link-static-library-to-your-jni-library/

As of right now I'm able to create a static library `*.a` for leaf for each target architecture. Also there is a header exposing leaf's foreign function interfaces. I'm going to experiment building a small C wrapper library that creates a JNI interface and exposes the relevant FFI functions into java for use in Orbot

**Comment by gregoiregentil** [comment]
I have NDK 21.4.7075529 too and I'm getting at the very end of the compilation the following error during linkage:

```
/opt/google/android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: cannot find -lunwind
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
``` 
Any idea what I could do wrong?
