### ISSUE TITLE
Repeated DNS errors

### ISSUE THREAD

**Issue by SkewedZeppelin** [guardianproject/orbot#589]
With the latest update, Conversations via Orbot VPN can no longer connect to server.
Logcat shows the following error repeatedly:
```
01-27 13:47:09.946  2749  2927 D Tun2Socks: INFO(tun2socks): DNS: process device dns packet: 60 bytes
01-27 13:47:09.946  2749  2927 D Tun2Socks: INFO(tun2socks): DNS: IP version 4
01-27 13:47:09.946  2749  2927 D Tun2Socks: INFO(tun2socks): DNS: not UDP! FAIL
01-27 13:47:09.947  2749  2927 D Tun2Socks: INFO(tun2socks): UDP: from device 60 bytes
```

Conversations does a SRV lookup on connect, maybe related.

**Comment by n8fr8** [comment]
Ah yes, good find. We did change how DNS was handled, and SRV records may be getting lost somewhere.

**Comment by pgerber** [comment]
I'm seeing DNS issues too.

.onion addresses no longer resolve:

![a](https://user-images.githubusercontent.com/11895833/151494755-b9294381-d369-48e3-85ff-98754768b629.jpeg)

This is a screenshot of Termux but I'm also seeing it in other apps using .onion. As far as I can tell this is a regression in  16.5.3-RC-1.

DNS resolution via dig in Termux no longer works either:

![b](https://user-images.githubusercontent.com/11895833/151494944-169cc9b3-cddb-4d99-82e6-d28b6a65e4a7.jpeg)

Not exactly sure when this regressed, but this definitely worked.

DNS resolution via TCP appears to work (kind of), however:

![c](https://user-images.githubusercontent.com/11895833/151496085-5dfe7428-8612-4004-9c71-66a59313c92b.jpeg)

Except that DNS is not relayed through Tor properly. Tor doesn't support TXT (or SRV) records:

![e](https://user-images.githubusercontent.com/11895833/151496391-336caa5c-d3ae-4178-9095-d21de2560372.jpeg)


.onion addresses are leak to the DNS as well:

![d](https://user-images.githubusercontent.com/11895833/151495879-6babbbdb-8de1-436e-bf3a-68ff997037c7.jpeg)

This request shouldn't be responded to by root-servers.net.

**Comment by n8fr8** [comment]
On it... seems like in some cases not setting the DNS server value in the VPN Builder interface causes that traffic to NOT go through the VPN TUN interface at all. Didn't see this in testing on our devices/OS, but I can believe it is happening in some cases.

**Comment by fireneat** [comment]
So is this fixed in newer versions?

**Comment by SkewedZeppelin** [comment]
@fireneat
Latest version has been very reliable, probably one of the best releases in a
long while.

**Comment by n8fr8** [comment]
Fantastic.... new RC build coming today.
