### ISSUE TITLE
update geoip

### ISSUE THREAD

**Issue by n8fr8** [guardianproject/orbot#60]
I use both orbot on my phone and torbrowser on pc. There is an interesting bug about the geoip file.I have to use some bridges to make tor work well because i am in China.I found that the geoip file in torbrowser is the latest version but it is the old in orbot. So some bridges are not in the excluding states according to torbrowser but they are excluded in orbot. In order to resolve the problem,i replace the geoip file of orbot in the directory  /date/date/org.torproject.android/app_bin with the latest geoip in torbrowser. Then something new happened. When i use some bridges that are not excluded in both old and latest version geoip file, it is shown in orbot log file something like that Received http status code 404("Not found") from server 'xxx.xxx.xxx.xxx:xxxx' while fetching "tor/keys/fp-sk/xxxxxxxxxxxxxxxxxxxx......).But the bridges work well with the old geoip file. The bug if found in the newest version of orbot from 15.2.0-RC2 to 15.2.0-RC7-multi. I hope that the developers can fix the bug and use the latest geoip file with every new version orbot.

**Comment by bitmold** [comment]
Closing this since the tor-android-binary should contain the updates needed
