### ISSUE TITLE
Fake text in Russian translation

### ISSUE THREAD

**Issue by ghost** [guardianproject/orbot#609]
Hello!
You have been removed root support from the app, and already fixed English description. But we have a fake description in another languages. For example Russian. Please check and remove :)

Screenshot:
https://i.postimg.cc/pL94fzzP/Screenshot-20220217-002858-Orbot.jpg

**Comment by mitty119** [comment]
And I think, that you have to check and update another translations :)

**Comment by bitmold** [comment]
I don't speak Russian, if you're still following this issue i encourage you to help with the translation efforts and make it yourself.
