### ISSUE TITLE
Useless information in app

### ISSUE THREAD

**Issue by ghost** [guardianproject/orbot#610]
Hello!
Tor project had stopped v2 onion services. I think that the text «v3» is useless because of no alternative provided. I think, that the text «v3» should be removed.

Screenshot (English):
https://i.postimg.cc/4dMh9Cgf/Screenshot-20220217-005752-Orbot.jpg
Screenshot (Russian):
https://i.postimg.cc/d3yZRWs8/Screenshot-20220217-005815-Orbot.jpg

**Comment by bitmold** [comment]
Fair point, Tor doesn't use it anymore at https://community.torproject.org/onion-services/ I'll drop this text...

**Comment by ValZapod** [comment]
Tor still uses v2.
