### ISSUE TITLE
Background start is broken

### ISSUE THREAD

**Issue by BayLee4** [guardianproject/orbot#616]
After the last update pushed on F-droid (`16.6.0-RC-2-tor.0.4.6.9`), the background start option isn't working like it was before : now, the application must be opened manually to allow other application to start it.

It could be replicated using F-droid with the "Use Tor" option : open Orbot, click "Start",  then "Stop" and **close** the application by wiping it frop recent items (swipe Orbot up in the "recent items" menu). Open F-droid, try to refresh/update applications and notice that it fails as Orbot isn't started anymore, where it previously was. The Start/Stop/Close step is only to make sure that the application is not opened (no Orbot top bar icon / no silent notification stating 'Orbot is deactivated' / not present in recent items).

Android 12 / No GMS

**Comment by bitmold** [comment]
Looking into this, F-Droid uses netciphre's `OrbotHelper` to see if Orbot is installed and start it. 

On Android 11, the method `isOrbotInstalled(Context)` fails, because Orbot is by default not visible to other packages https://developer.android.com/training/package-visibility/declaring

**Comment by bitmold** [comment]
I'm going to submit a patch to F-Droid to fix this....

**Comment by bitmold** [comment]
F-Droid patch is here, it's in their hands now so I'm closing this issue.

https://gitlab.com/fdroid/fdroidclient/-/merge_requests/1095

**Comment by BayLee4** [comment]
@bitmold Did you test your patch?

Because F-droid isn't the only affected application, for instance the [CTemplar ](https://f-droid.org/en/packages/com.ctemplar.app.fdroid/) android application which already contains your [fix](https://github.com/CTemplar/android/blob/master/app/src/main/AndroidManifest.xml#L17-L19) also doesn't work (in the exact same way as described above). I believe the issue should be reopened as this isn't fixing it.

**Comment by bitmold** [comment]
Netcipher could be upgraded to have a manifest with the right queries information and also be distributed as an AAR instead of as a JAR. This would make it so that apps using it could upgrade without having to apply additional code

**Comment by bitmold** [comment]
I've noticed that app you linked uses an outdated version of netcipher, maybe upgrading to the latest 2.1.0 would fix the issue?

**Comment by BayLee4** [comment]
@bitmold Thank you for the feedback! I think you pointed the right issue : the CTemplar application is effectively targeting SDK [30](https://github.com/CTemplar/android/blob/master/app/build.gradle#L15) and is using [OrbotHelper](https://github.com/CTemplar/android/blob/master/app/src/main/java/mobileapp/ctemplar/com/ctemplarapp/net/ProxyController.java#L32) to start Orbot, does that means that Orbot couldn't be started at all in that case? If so, is there an alternative method? (I'll try updating to the latest version 2.1.0 first if you think that could be sufficient).
