### ISSUE TITLE
Strange things going on here since I installed Orbot 16.6.0

### ISSUE THREAD

**Issue by Michas0206** [guardianproject/orbot#617]
I used Orbot 16.5.2 RC 5 for a while, everything seemed fine. Then I updated to 16.6.0 RC 2 - and the problems began.

On 2 phones.

On both phones Orbot 16.6.0 does not start automatically. But the biggest problem is, that it crashes all the time. It connects, its ok for a while - but after some minutes/hours, it/the connection breaks - in a way, that just a "hard close" + deleting Orbot's cache + restart helps.

Ok, so I thought minutes ago that it is so annoying, that I have to revert to the old version that was fine here - but now this also does not work anymore?! Whyever....just tried it on one of the 2 mobiles, but whatever I try - I can't get Orbot 16.5.2 RC 5 to work again. It crashes every time when I open the VPN-applist to select apps and pushing the back-button in the upper left. 
I also have already tried some 16.5.3-beta, same result - it crashes after I select an app for VPN and pressing the back-button.

I can't imagine really but to me it looks as if 16.6.0 RC 2 broke something here - and/or is not being fully uninstalled by Android.

I'll check my second phone now if I am being able to revert to 16.5.2 on that one...

**Comment by Michas0206** [comment]
Sometimes it is nice to have 2 mobiles - phone 2 does not crash after deleting Orbot 16.6, reinstalling 16.5.2 and selecting apps - but they do not appear at the bottom.

Before I installed 16.6.0, the selected apps appeared left to the gear-symbol...now they dont anymore. Closing the app 'hard' and deleting cahe+used memory makes no difference.

**Comment by n8fr8** [comment]
Thanks for the detailed report. If you do a full clear data/cache of Orbot and uninstall, there is nothing it can break or do permanently to your device. There is no root/admin/mod capability. 

Has your device recently had an OS upgrade? Can you tell us more details about which OS/rom you are using?

**Comment by Michas0206** [comment]
Its Lineage OS 18.1, updated weekly on both mobiles. I currently watch this a bit more...on my LG everything seems fine atm, but I have to check it more and try a reboot later today.

Currently I am sitting in front of my Samsung - seems it has the most problems: after a reboot it takes very long in my opinion until Orbot starts. But it starts after a while and connecting to Tor.

Unfortunately my Vpn-activated app did not get any connection.
Then I 'hard' closed Orbot (its 16.6.0 RC 2 currently), deleted its cache, closed my Vpn-activated app - and after a restart of Orbot it hangs at “20% bootstrapped"...after another restart I had to reselect Vpn-mode and the app at the bottom + crash when pushing the back arrow at the top, it took another restart of Orbot until everything looks fine and as it should for now.

I'll watch this how long it works now and later today I try a reboot on my LG.

**Comment by n8fr8** [comment]
Thanks for the update. We currently have a solution to the start on boot issue in review.

**Comment by Michas0206** [comment]
Tonight my LG lost its connection, my Vpn activated app just wrote 'connecting' all the time but Orbot was connected to Tor successful.
It made no difference to change identity in Orbot.

After a reboot of my phone, Orbot's notification now hangs with "Orbot is starting, done, connected to a relay", the blue bar indicates around 15% done and nothing more happens. Inside of the app everything seems ok, its connected to Tor successful. But my app still does not work, just showing 'connecting'. 

I assume a clearing of Orbots cache will fix it, I'll wait now and looking forward for the update.

**Comment by bitmold** [comment]
Thanks we are working on this now. Please report other information you find pertaining to this issue at #621

**Comment by Michas0206** [comment]
Quick update with 16.6.0 rc3:
LG start looks fine, symbol appears, Orbot app says connected and "whatismyip" in vpn-activated browser shows not my real...unfortunately the notification message hangs at "Orbot startet...   Connect to tor control port " and blue bar at around 5%. Furthermore the symbol does not show any data activity after the reboot / no black lines/arrows inside the symbol. Before the reboot it was fine. Luckily Orbot seems to connect and work at all.

On my Samsung Galaxy S5 Orbot 16.6.0 did not start on first reboot at all, looks better on second reboot now, the symbol appears, notification hangs at "Orbot startet...  Connected to a relay", blue bar is at around 10%“.
Same behavior as on the LG now - notification hangs, notification-symbol shows no data activity indicators, but it looks as if Orbot connects fine and is running at all.
