### ISSUE TITLE
Can Portugal be added to the list of countries?

### ISSUE THREAD

**Issue by TiagoDeSousa** [guardianproject/orbot#643]
Is it possible to add Portugal to the list of countries in order to access blocked sites in this country? Thanks.

**Comment by bitmold** [comment]
Yes it is, though there aren't many relays for [Portugal](https://metrics.torproject.org/rs.html#search/country:pt). Depending on how reliable these relays are if time goes on, then it might not work.

With whatever version of Orbot you have now, you can add this line to your torrc: 
```
Exit Nodes: {pt} StrictNodes 0
```

Anyway, I'll just add it to the spinner in the next release

**Comment by bitmold** [comment]
I just reverted this, there are no exit relays in Portugal, when I configured Orbot to use a "pt" relay it ended up using one that was in another country. there seems to be issues with Orbot's geo IP which lead the app to display Portugal in the notification. Apologies for the false hope here. 

It's beyond the scope of this issue, but you will need to find a way to proxy into Portugal, and maybe you can enter that proxy through the tor network ...
