### ISSUE TITLE
Feature Request: More control over "paste bridges" field

### ISSUE THREAD

**Issue by darkblaze69** [guardianproject/orbot#644]
Right now as of "Orbot for Android 16.6.0 RC 4" you cannot conveniently operate in "Paste Bridges" field like in all other standard text fields.
- Seems you can only paste bridges.
- You cannot select all bridges or part of them and delete selected at once.
- You cannot copy bridges from the field to share or for archive purposes.

**Comment by bitmold** [comment]
Thanks for reporting this !
