### ISSUE TITLE
Orbopt gets disconnected when opening Via broser app

### ISSUE THREAD

**Issue by tebicap** [guardianproject/orbot#645]
Hi, I can't make Via (web browser https://play.google.com/store/apps/details?id=mark.via.gp) works with Orbot for android, here is the log. I don't know if it's a bug, or a configuration issue.

when I connect Orbot to the Tor network then I open Via and Orbot gets disconnected. Via is not able to pass trough the Tor network.

Here a log on Android 6:

adb logcat |grep 'Orbot|via'
03-20 15:49:37.423 18847 18847 I HwResources: load icon id : 7f0d0000, pkgName : mark.via.gp
03-20 15:49:37.426 18847 18847 I HwResources: icon : mark.via.gp found in app
03-20 15:49:37.734 18847 18847 I OrbotService: onCreate end
03-20 15:49:37.745 18847 18874 W Orbot : unhandled OrbotService Intent: org.torproject.android.intent.action.START_VPN
03-20 15:49:37.916 889 969 I ActivityManager: Displayed org.torproject.android/.OrbotMainActivity: +3s429ms
03-20 15:49:43.266 18847 18874 W Orbot : unhandled OrbotService Intent: org.torproject.android.intent.action.START
03-20 15:50:00.559 18847 18874 W Orbot : unhandled OrbotService Intent: org.torproject.android.intent.action.UPDATE_ONION_NAMES
03-20 15:50:03.281 18847 18874 W Orbot : unhandled OrbotService Intent: org.torproject.android.intent.action.STOP_VPN
03-20 15:50:03.375 18847 18876 W Orbot : unhandled OrbotService Intent: org.torproject.android.intent.action.STOP
03-20 15:50:03.502 889 1306 W InputDispatcher: channel '32f2ae org.torproject.android/org.torproject.android.OrbotMainActivity (server)' ~ Consumer closed input channel or an error occurred. events=0x9
03-20 15:50:03.502 889 1306 E InputDispatcher: channel '32f2ae org.torproject.android/org.torproject.android.OrbotMainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
03-20 15:50:03.511 889 1629 W InputDispatcher: Attempted to unregister already unregistered input channel '32f2ae org.torproject.android/org.torproject.android.OrbotMainActivity (server)'
03-20 15:50:31.116 19144 19144 I HwResources: load icon id : 7f0d0000, pkgName : mark.via.gp
03-20 15:50:31.120 19144 19144 I HwResources: icon : mark.via.gp found in app
03-20 15:50:31.380 19144 19144 I OrbotService: onCreate end
03-20 15:50:31.386 19144 19172 W Orbot : unhandled OrbotService Intent: org.torproject.android.intent.action.START_VPN
03-20 15:50:31.520 889 969 I ActivityManager: Displayed org.torproject.android/.OrbotMainActivity: +2s670ms
03-20 15:51:04.286 19144 19172 W Orbot : unhandled OrbotService Intent: org.torproject.android.intent.action.START_VPN
03-20 15:51:04.365 889 969 I ActivityManager: Displayed org.torproject.android/.OrbotMainActivity: +2s621ms
03-20 15:51:09.057 19144 19173 W Orbot : unhandled OrbotService Intent: org.torproject.android.intent.action.START
03-20 15:51:23.380 19144 19173 W Orbot : unhandled OrbotService Intent: org.torproject.android.intent.action.UPDATE_ONION_NAMES
03-20 15:51:47.176 1493 2013 I HwResources: load icon id : 7f0d0000, pkgName : mark.via.gp
03-20 15:51:47.182 1493 2013 I HwResources: icon : mark.via.gp found in app
03-20 15:51:47.185 19405 19405 W System : ClassLoader referenced unknown path: /data/app/mark.via.gp-2/lib/arm64
03-20 15:51:47.202 19405 19405 I System.out: try to read channel info from apk : /data/app/mark.via.gp-2/base.apk
03-20 15:51:47.204 19405 19405 I System.out: getByteBufferValueById , destApk /data/app/mark.via.gp-2/base.apk IdValueMap = {1896449818=java.nio.ByteArrayBuffer[position=0,limit=1767,capacity=1767], -2012129793=java.nio.ByteArrayBuffer[position=0,limit=6,capacity=6], 558253134=java.nio.ByteArrayBuffer[position=0,limit=175,capacity=175], 1114793335=java.nio.ByteArrayBuffer[position=0,limit=2068,capacity=2068]}
03-20 15:51:47.594 889 1306 W InputDispatcher: channel 'fcf5afb org.torproject.android/org.torproject.android.OrbotMainActivity (server)' ~ Consumer closed input channel or an error occurred. events=0x9
03-20 15:51:47.594 889 1306 E InputDispatcher: channel 'fcf5afb org.torproject.android/org.torproject.android.OrbotMainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
03-20 15:51:47.597 889 910 W InputDispatcher: Attempted to unregister already unregistered input channel 'fcf5afb org.torproject.android/org.torproject.android.OrbotMainActivity (server)'
03-20 15:51:48.185 889 969 I ActivityManager: Displayed mark.via.gp/mark.via.Shell: +1s91ms
03-20 15:51:48.855 19709 19709 I OrbotService: onCreate end
03-20 15:51:48.858 19709 19842 W Orbot : unhandled OrbotService Intent: org.torproject.android.intent.action.START_VPN
03-20 15:51:48.858 19709 19843 W Orbot : unhandled OrbotService Intent: org.torproject.android.intent.action.START_VPN
03-20 15:51:48.879 19709 19844 W Orbot : unhandled OrbotService Intent: org.torproject.android.intent.action.UPDATE_ONION_NAMES
03-20 15:51:49.045 19709 19843 W Orbot : unhandled OrbotService Intent: org.torproject.android.intent.action.START

**Comment by bitmold** [comment]
Thanks, I'm looking into this, and similar issues, right now. 
I'm curious, what version of Orbot were you using

**Comment by tebicap** [comment]
> Thanks, I'm looking into this, and similar issues, right now. I'm curious, what version of Orbot were you using

The last one on the playstore: 16.6.0-RC-4-tor.0.4.6.9

**Comment by bitmold** [comment]
![Screenshot_20220726-160305.png](https://user-images.githubusercontent.com/22125581/181101850-f2c92805-f91b-4e6c-a73d-eaf6c5a7bd2c.png)

It's working well in the latest build. Closing.
