### ISSUE TITLE
Icon size issues

### ISSUE THREAD

**Issue by syphyr** [guardianproject/orbot#646]
Since df852d61 the notification icons are incorrect.  I was able to fix the xhdpi resolution icons on my tablet by copying the deleted files from drawable-xhdpi-v11 into drawable-xhdpi.  https://github.com/syphyr/orbot/commit/84caebec317abcc90e110cf5234e243d081c41d6

Although, my changes only fix xhdpi notification icons.  xxhdpi and xxxhdpi are also currently using incorrect notification icons after df852d61 was added.

**Comment by bitmold** [comment]
Please grab the latest master and let me know if this issue still exists, I believe it's fixed

**Comment by syphyr** [comment]
Its fixed now. Thanks.
