### ISSUE TITLE
Does VPN service need to be active in order to run relay node? 

### ISSUE THREAD

**Issue by e-t-l** [guardianproject/orbot#665]
I'd like to use my device as a relay node, but I have a different VPN service permanently active (Blokada). I can exempt Orbot traffic from Blokada easily enough, but I can't actually set Orbit as the active VPN. Will the relay node still work?

**Comment by n8fr8** [comment]
Yes, being a relay doesn't require the VPN to be active. That is one reason the VPN is optional.

The other thing you can do is be a Snowflake Bridge. See the bottom of the Settings screen for this experimental (but soon mainline) feature. Learn more at: https://snowflake.torproject.org/

**Comment by e-t-l** [comment]
Great, thank you. I did also enable the setting to be a snowflake bridge. I assume that also does not require the VPN to be active?

**Comment by n8fr8** [comment]
No it does not require VPN. VPN is only needed if you want to send your app traffic through Tor.
