### ISSUE TITLE
VPN mode fails deadly

### ISSUE THREAD

**Issue by jtracey** [guardianproject/orbot#667]
I would expect apps with Orbot set to VPN mode on them would fail to connect when Orbot is disabled. Instead, they seem to continue working, without proxying through Tor. (I confirmed this via the Termux app.) This either needs to be fixed, or at the very least, clearly documented, since Orbot semi-regularly crashes, and users right now could be relying on it for their safety without realizing that VPN mode is more of a suggestion than any kind of guarantee.

**Comment by n8fr8** [comment]
If the VPN icon isn't visible, then the VPN isn't on. If you stop Orbot manually, the VPN also stops.

It is more a suggestion, but Android OS itself provides no guarantees about VPN stability or permanence... 

UNLESS, you enable in Android settings->Networks->VPN->Orbot

"Always-On VPN"
and
"Block connection without VPN"

**Comment by jtracey** [comment]
Is that not something users should be informed of? I certainly didn't expect "the OOM killer can cause my Tor connections to become non-Tor connections". TBH, I question the utility of a VPN mode if it comes with such risk--what's the point of proxying an app through Tor if it only proxies some of the time, and can switch without warning?

The "Block connection without VPN" is for all connections, so e.g. Tor Browser stops working if you enable it.

**Comment by syphyr** [comment]
It seems like adding back the root option for tor is the safest solution, at least for legacy devices on older versions of android. This would ensure the vpn never leaks.

**Comment by n8fr8** [comment]
We are going to do the work to put "root mode" back in. If someone wants to resurrect Orwall, we'd be happy to endorse/support that: https://github.com/EthACKdotOrg/orWall

@jtracey the VPN mode is not meant to provide the "Tor always" guarantee. It is meant to enable apps that have no idea about Tor to be able to proxied through Tor with one switch, improving privacy against network surveillance and helping with unblocking network connections for blocked/censored apps. If you want an app to always go through Tor, then it should support SOCKS proxying and use our NetCipher SDK to integrate with Orbot.

Another option is to use the excellent Rethink DNS+Firewall app which can route app traffic through Orbot/Tor. It has easy built in support. This gives you a powerful firewall capability that is separate from Tor, and will likely not get OOM'd like orbot does.

Lastly, we just pushed 16.6.1  RC 3 public. It is the most stable version of Orbot yet, and has been widely tested on many devices. If Orbot is still crashing a lot and being unstable for you, then I'd like to know so we can fix that. I use Orbot across many devices at various levels of capability from Android 6 to 12, and do not experience random crashes and OOMing of the Orbot VPN.
