### ISSUE TITLE
I am gonna make a build external but failed

### ISSUE THREAD

**Issue by nAkhmedov** [guardianproject/orbot#67]
I have updated all submodules, when i try to `make -C external` i got exception

Configured for android.
making depend in crypto...
clang: error: unknown argument: '-mandroid'
make[2]: *** [local_depend] Error 1
make[1]: *** [depend] Error 1
make: *** [lib/libcrypto.a] Error 2

All todos are done as BUILD file written

**Comment by goapunk** [comment]
Not sure if compiling with clang is working, the Makefile was made for gcc. You should try to use gcc (and android-ndk version 10e).
