### ISSUE TITLE
Capabilitie

### ISSUE THREAD

**Issue by ghost** [guardianproject/orbot#674]
Hi, could you please tell me if it is possible to configure the application to let all traffic through a LOCAL proxy (for example 127.0.0.1:8787) before connecting to Tor? This is necessary for the network level ad blocker to work.

**Comment by n8fr8** [comment]
That is not possible with Tor.

You can use Rethinkdns (https://rethinkdns.com/) as a firewall+ad blocker app, that integrates with Orbot. Rethink will be the VPN and then do all content filtering locally before proxying outbound data/network through Orbot/Tor.

**Comment by bililto** [comment]
Thank you. You can close the issue
