### ISSUE TITLE
Fdroid version is sorely out of date

### ISSUE THREAD

**Issue by mechanic41turk** [guardianproject/orbot#676]
My fdroid client lists Orbot 16.6.0-RC-4-tor.0.4.6.9 as the latest available version for the Orbot app, while on Github the latest release is  16.6.1 RC 3. The Guardian Project repo is enabled (and have always been enabled) in my Orbot settings.

Why is Orbot on fdroid lagging behind in releases?

**Comment by Nickoriginal** [comment]
> Why is Orbot on fdroid lagging behind in releases?

No, it is not now. Check your repo again, it was updated today.

> on Github the latest release is 16.6.1 RC 3.

There are uploaded multiple beta and RC releases for testing, as mentioned [here](https://orbot.app/download):

> You can find releases tagged with downloadable files for testing on GitHub at https://github.com/guardianproject/orbot/releases

Keep in mind, that uploading in repo may be little delayed.

**Comment by mechanic41turk** [comment]
>Check your repo again, it was updated today.

Yes. I can confirm that fdroid now has the 16.6.1 RC 3 release of the Orbot. Thanks for updating it.
