### ISSUE TITLE
App VPN Tor over Tor

### ISSUE THREAD

**Issue by vapingisgood4you** [guardianproject/orbot#68]
Using the app VPN mode to torify all apps seems to create a tor over tor situation as described here https://trac.torproject.org/projects/tor/wiki/doc/TorifyHOWTO i noticed as soon as i turn it on in the notification two to three more relays instantly appear.

**Comment by n8fr8** [comment]
Hmm, interesting. It really shouldn't in that we actively work to either specifically mark traffic to NOT route Tor traffic over the VPN. On Android 5+ this is easy, and supported by the API. In Android 4, we do this by routing Tor traffic over a localhost SOCKS proxy that is just a passthrough. Which device are you on?

**Comment by vapingisgood4you** [comment]
Im on a Samsung Galaxy J1 on 5.1.1 you could be completely right im no expert on the matter of course, just pointing out my findings.
