### ISSUE TITLE
UI update

### ISSUE THREAD

**Issue by ghost** [guardianproject/orbot#682]
I think the app should have a UI update. It doesn't look very aesthetically pleasing on android 12. I would like the app to support Material You style, and if possible a dark theme depending on the system settings.

By dark theme I mean to fill the background with a completely black colour, in case the settings of the device is enabled this theme.

These changes are necessary so that the application does not stand out among the others :)

**Comment by syphyr** [comment]
https://github.com/guardianproject/orbot/tree/NEW_UX

**Comment by bitmold** [comment]
We are working on an overhaul of the Orbot UI right now. Thanks for your feedback, but closing this.
