### ISSUE TITLE
Add support for new Moat API version

### ISSUE THREAD

**Issue by n8fr8** [guardianproject/orbot#684]
New capabilities added for region specific bridges

https://gitlab.torproject.org/meskio/rdsys/-/blob/doc_moat_api/doc/moat.md

**Comment by n8fr8** [comment]
Python implementation of the Censorship API routes https://github.com/onionshare/onionshare/blob/a998a327af831caf9dbfa13d232bd874071a81d5/cli/onionshare_cli/censorship.py

**Comment by bitmold** [comment]
This has been implemented in Kotlin on the `NEW_UX` branch 0d1b027e64abbfbe992b604ad3a6fdd11880875a
