### ISSUE TITLE
16.6.2 closes itself after some seconds

### ISSUE THREAD

**Issue by Michas0206** [guardianproject/orbot#706]
As written, on my  Galaxy S5 it looks as if everything is fine, I'll check it more intensive later.

But on my LG V20, Orbot 16.6.2 RC1 crashes after around 5 or 10 seconds. Its completely unusable now here.
Update was also not possible, It hanged for a long time until I aborted it and uninstalled the old version.

I dont have to press anything I just have to open it and wait a bit.

Whatever is wrong now - please test the software youre releasing before releasing!!!!!! Get better testers (or testers at all) please! Since several weeks/months for now no usable Orbot, every release has more problems...thats not very good.

Btw, I already tried to delete apps cache and mem, tried a restart of my mobile, still the same behaviour, app crashes after a few seconds.

**Comment by bitmold** [comment]
This is fixed by reverting `03fcec9f5fadb0788f92b7d513e27c043bfda05e`
