### ISSUE TITLE
Cannot disable SOCKS/HTTP proxy

### ISSUE THREAD

**Issue by 7546bgenwnr58v5w** [guardianproject/orbot#709]
# Software & Hardware

- Device: Google Pixel 4a
- Operating System: GrapheneOS (SQ3A.220705.003.A1.2022070600)
- Orbot version: 16.6.2-RC-1-tor.0.4.7.8 (arm64-v8 release from GitHub)

# Steps To Reproduce

- Set `Tor SOCKS` and/or `Tor HTTP` to `0`. According to Orbot settings, this should disable the proxy.
- Try to use `127.0.0.1:9050` and/or `127.0.0.1:8118` as proxy in the browser and it will still successfully connect even though the proxy should be disabled.

# Additional Informations

I checked that this issue is reproductible in Privacy Browser 3.10.1 and Bromite 102.0.5005.96.

**Comment by SkewedZeppelin** [comment]
These are unconditionally set in TorService: https://github.com/guardianproject/tor-android/blob/master/tor-android-binary/src/main/java/org/torproject/jni/TorService.java#L341-L342

**Comment by SkewedZeppelin** [comment]
> This rule is simple for options that take a single value, but it can become complicated for options that are
>        allowed to occur more than once: if you specify four SocksPorts in your configuration file, and one more
>        SocksPort on the command line, the option on the command line will replace all of the SocksPorts in the
>        configuration file. If this isn’t what you want, prefix the option name with a plus sign (+), and it will be
>        appended to the previous set of options instead. For example, setting SocksPort 9100 will use only port
>        9100, but setting +SocksPort 9100 will use ports 9100 and 9050 (because this is the default).

These three bugs are the same.

TorService always overrides the commandline, which is #708 and #709

And for #707 correct syntax would be prepended with a `+`

**Comment by pgerber** [comment]
> And for https://github.com/guardianproject/orbot/issues/707 correct syntax would be prepended with a +

I'm not sure about that. Wouldn't a `--+SocksPort 9050` still override a `SocksPort 9050 IsolateDestAddr` in the config? It states, "prefix the option name with a plus sign (+), and it will be appended to the previous set of options". I'm not sure how "appending" would work if the same port was specified twice.

**Comment by pgerber** [comment]
I decided to just test it, if you combine `--+SocksPort 9100` with a config file containing `SocksPort 9100` you get an error:

```
Jul 10 00:08:54.069 [notice] Tor 0.4.7.8 running on Linux with Libevent 2.1.12-stable, OpenSSL 1.1.1n, Zlib 1.2.11, Liblzma 5.2.5, Libzstd 1.4.8 and Glibc 2.31 as libc.
Jul 10 00:08:54.070 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://support.torproject.org/faq/staying-anonymous/
Jul 10 00:08:54.078 [notice] Read configuration file "/home/user/c".
Jul 10 00:08:54.081 [notice] Opening Socks listener on 127.0.0.1:9100
Jul 10 00:08:54.081 [notice] Opened Socks listener connection (ready) on 127.0.0.1:9100
Jul 10 00:08:54.081 [notice] Opening Socks listener on 127.0.0.1:9100
Jul 10 00:08:54.082 [warn] Could not bind to 127.0.0.1:9100: Address already in use. Is Tor already running?
Jul 10 00:08:54.082 [notice] Closing partially-constructed Socks listener connection (ready) on 127.0.0.1:9100
Jul 10 00:08:54.082 [warn] Failed to parse/validate config: Failed to bind one of the listener ports.
Jul 10 00:08:54.082 [err] Reading config failed--see warnings above
```

**Comment by pgerber** [comment]
What's done on Debian is to use `--defaults-torrc` which can be overridden by configs in the regular `--torrc-file`/`-f`:

```
user@tor-test:~$ cat /usr/share/tor/tor-service-defaults-torrc
DataDirectory /var/lib/tor
PidFile /run/tor/tor.pid
RunAsDaemon 1
User debian-tor

ControlSocket /run/tor/control GroupWritable RelaxDirModeCheck
ControlSocketsGroupWritable 1
SocksPort unix:/run/tor/socks WorldWritable
SocksPort 9050

CookieAuthentication 1
CookieAuthFileGroupReadable 1
CookieAuthFile /run/tor/control.authcookie

Log notice syslog
```

**Comment by SkewedZeppelin** [comment]
@pgerber 
defaults is already used, see: 

https://github.com/guardianproject/tor-android/blob/master/tor-android-binary/src/main/java/org/torproject/jni/TorService.java#L333-L334
https://github.com/guardianproject/orbot/blob/master/orbotservice/src/main/java/org/torproject/android/service/OrbotService.java#L704-L711

**Comment by SkewedZeppelin** [comment]
The solution is for TorThread to never pass SOCKSPort if it is contained in either torrc.

**Comment by pgerber** [comment]
I suggest to formally reserve --torrc-defaults for use by tor-android allowing consumers to override any settings via --torrc-file.

**Comment by bitmold** [comment]
> I suggest to formally reserve --torrc-defaults for use by tor-android allowing consumers to override any settings via --torrc-file.

@eighthave I intend to implement a patch doing this. One thing that might be tricky is that the hardcoded 9050/8118 auto increment if the ports are already in use. Using torrc defaults and having orbot override them might break integrating apps that rely on this port incrementing, I'm sure there's a way around this too though

**Comment by pgerber** [comment]
I can confirm that isolation still doesn't work as expected.

Unrelated, I wonder if the IsolateDestAddr flag should be added to DNSPort too.

**Comment by bitmold** [comment]
I said on another issue but this fix is still in development. It was not included in the orbit release that just came out. It will be fixed soon though, thanks
