### ISSUE TITLE
Orbot crashes after starting Snowflake proxy

### ISSUE THREAD

**Issue by vv394pdcvn52q2kt** [guardianproject/orbot#712]
# Software & Hardware

- Device: Google Pixel 4a
- Operating System: GrapheneOS (SQ3A.220705.003.A1.2022071300)
- Orbot version: 16.6.2-RC-2-tor.0.4.7.8 (arm64-v8 release from GitHub)

# Steps To Reproduce

- Enable `Run Snowflake Proxy` option.
- Start Orbot.

**Comment by bitmold** [comment]
Once we get this merged into IPtProxy this will no longer crash... https://github.com/tladesignz/IPtProxy/pull/30

**Comment by tladesignz** [comment]
IPtProxy 1.7.1 released containing this fix.
