### ISSUE TITLE
A lot of apps leak traffic to clearnet in VPN mode

### ISSUE THREAD

**Issue by e3b** [guardianproject/orbot#72]
Most, if not all, apps I enable in VPN mode leak traffic (e.g. Firefox, Forcastie and Good Weather), as this screenshot of [Net Monitor](https://github.com/SecUSo/privacy-friendly-netmonitor) shows. Apps configured to use Tor without VPN mode (Orfox, Syncthing, ...) do not leak (traffic only to localhost/0.0.0.0).

![net-monitor](https://cloud.githubusercontent.com/assets/28929208/26689373/f7bc2440-46e4-11e7-8ff0-ca2a728dd42f.jpeg)

Could this be prevented with a VPN mode for all traffic? (Why doesn't Orfox offer one?)

In any case, I think Orbox should warn users about just how leaky the VPN mode is, not just label it as experimental.

**Comment by n8fr8** [comment]
Are you choosing specific apps with the VPN mode, or selecting all? Are you sure it is properly enabled?

Our plan moving forward is to really only focus on using the VPN mode for circumventing firewalls and filters on apps we know use HTTPS/TLS traffic. 

Thanks for this test and report!

**Comment by e3b** [comment]
Previously I have excluded some apps from the VPN mode; now I tried selecting all. The result is the same. Whether it is properly enabled? Nothing indicates otherwise. Android displays the key. <https://check.torproject.org> tells me I'm using Tor in both Firefox and Chromium, and yet they both leak clearnet traffic according to Net Monitor.

I'm running the newest version of CopperheadOS, otherwise nothing special I can think of.

**Comment by n8fr8** [comment]
I am not convinced that what you are seeing to NetMonitor is actually "leaking traffic". To the app itself, it is connecting to that IP address. We do not tell the app that their traffic is being redirect to the localhost, we simply intercept it enroute, rewrite the packets to proxy through socks/Tor, and do the same with the response. The test for leaking traffic would need to be at a router level, with something like Wireshark running.

**Comment by e3b** [comment]
Maybe you're right. But does that also account for the fact that the apps configured to use Orbot as a proxy (without VPN mode) appear to not leak traffic to clearnet?

At least for now, I don't have the possibility to intercept the traffic at router level. But I hope I get a chance to do before too long.

**Comment by thestinger** [comment]
I think you're misinterpreting the Net Monitor output. The VPN API is intercepting that traffic. It's not a valid way to look for leaks.

Similarly, Net Monitor can be misleading when apps make requests via APIs like DownloadManager since they get attributed to the OS, other apps, etc. It also currently handles shared UIDs poorly by attributing all connections from those apps to an arbitrary one which is should be more clear about in the output even though it might not be able to attribute them to specific apps.

**Comment by e3b** [comment]
@thestinger Thanks for the explanation!

I guess this issue can be closed, then.
