### ISSUE TITLE
NEW_UX - No button to start normal mode

### ISSUE THREAD

**Issue by licaon-kter** [guardianproject/orbot#720]
In https://github.com/guardianproject/orbot/releases/tag/17.0.0-ALPHA-1-tor.0.4.7.8 there's only a "start VPN" button that does nothing _(at least while the Netguard VPN is active)_.

![noproxynbutton](https://user-images.githubusercontent.com/2282799/183100795-71964313-cfc3-4940-9d96-16e100fed1ca.jpeg)

/LE: I can use the Notification "Connect to Tor" action though

**Comment by n8fr8** [comment]
Thanks for the feedback. We are still figuring this out. The releases are VERY alpha.

The vast majority of our users want a simple "Start VPN" button. We understand there are others who are using Orbot in combination with other exist VPNs, so considering how we can detect that or offer a setting to not use VPN by default.

**Comment by licaon-kter** [comment]
Is the old way with "one more button" _not modern_ enough?

Ok, put Start VPN on top, but... under... add start proxy or something
