### ISSUE TITLE
Debug log logs info entries twice 

### ISSUE THREAD

**Issue by cheahjs** [guardianproject/orbot#73]
Is it intentional that there are log info and log debug entries in the config when debug logging is enabled?

https://github.com/n8fr8/orbot/blob/5b255df92d8ddffb2b6941e2f1be1efc0714e8a4/orbotservice/src/main/java/org/torproject/android/service/TorService.java#L707

This ends up logging info messages twice in logcat.

**Comment by bitmold** [comment]
This is a bug, there are five log levels supported in tor, and anything that would be logged at the `info` level would also be logged at the `debug` level. 


- `"err"`: something bad just happened, and we can't recover. Tor will exit.
- `"warn"`: something bad happened, but we're still running. The bad thing might be a bug in the code, some other Tor process doing something unexpected, etc. The operator should examine the message and try to correct the problem.
- `"notice"`: something the operator will want to know about.
- `"info"`: something happened (maybe bad, maybe ok), but there's nothing you need to (or can) do about it.
- `"debug"`: for everything louder than info. It is quite loud indeed.

On the settings page the preference for logging is captioned _"Enable debug log to output"_ which so I will delete the torrc line for `Log info syslog`
