### ISSUE TITLE
Automatic update

### ISSUE THREAD

**Issue by xyz-nobody** [guardianproject/orbot#740]
It would be cool if via the API of github, that it automatically downloads the automatic update:

https://api.github.com/repos/guardianproject/orbot/releases/latest

Not everyone wants to use a store and many people download apk directly from github directories.

**Comment by ASHIT-AXAR** [comment]
it'll be much better if it can update itself within the app (both Alpha and Stable version).
Telegram messenger does it's updates built-in (the version you downloaded directly from their website which has less restrictions compared to googleplay one)
many people have no direct access to Google play.
