### ISSUE TITLE
Use Orbot without root behind Netguard

### ISSUE THREAD

**Issue by ghost** [guardianproject/orbot#75]
Hi all,

So, I'd like some help in configuring orbot to communicate behind netguard, a non-root firewall for android.

That is, if it's possible?

Here are links: homepage https://www.netguard.me

Xda forum: https://forum.xda-developers.com/android/apps-games/app-netguard-root-firewall-t3233012

github: https://github.com/M66B/NetGuard

There's much I've checked before presenting this query, as in, the various methods to redirect network traffic for some, if not all apps though tor.

However, all of them only mention using a rooted device, via orwall/afwall together as an example answer, for a rooted device.

Theres also the iptables redirection ruleset, as a same root only method, etc all I've come across in Google search are root only methods.

Netguard offers a socks5 proxy for redirection, also specific port redirection.

Ive followed the official netguard instruction set here, for socks5 redirection at https://github.com/M66B/NetGuard/blob/master/FAQ.md#FAQ54, no profit.

I've tested also the port redirection inside netguard for both tcp/udp 53 toward tor dns 5400. Again, no profit.

In closing, I guess an additional question would be, is the udp networking that netguard excludes in its socks5 proxy implementation (it doesn't seem to exclude udp in port redirection) nessesary for orbot to work correctly behind netguard?

fwiw, I'm using a wifi only tablet, its an sm-t230nu with stock rom kitkat 4.4.2 with installed orbot 15.4.2-rc-1-multi-sdk16.

Can anyone here provide a working instruction set for me to use orbot without root behind the netguard non root firewall?

I thank anyone willing to help in advance :)

**Comment by n8fr8** [comment]
Tor can support using an upstream proxy. This is a setting available in Orbot. Have you tried that?

**Comment by Keridoo** [comment]
@ghost I face a similar issue of wanting to chain NetGuard with a local SOCKS5 proxy server – Orbot or otherwise – on my Android device. Have you made any progress since you OP?

@n8fr8 This means that all the traffic is routed through the Tor network and afterwards via a specified SOCKS5 proxy? I've set up a [Streisand server](https://github.com/StreisandEffect/streisand/blob/master/README.md) but, for example, SSH authentication requires key handling. Is that possible with Orbot or does only work with username and password?

**Comment by KeyWeeUsr** [comment]
@DI555 https://github.com/M66B/NetGuard/blob/62bc61bcfcf7521231a49c33f8a6b6bf8b5ab574/FAQ.md (54)

**Comment by robovoice1** [comment]
@ghost 

Android 5.1 or later featured and required (NetGuard faq.)
