### ISSUE TITLE
meek support for custom bridges

### ISSUE THREAD

**Issue by mbrostami** [guardianproject/orbot#756]
Hello,   

I know that meek support has been stopped because major CDN providers stopped accepting domain fronting. 

I would like to suggest supporting meek again because of the following reasons (correct me if I'm wrong)   

- There are still some small/medium CDN providers that support DF
- It's still a great obfuscation layer over https and with the help of uTLS it's quite difficult to be detected by censorship 
- Even without DF it can still be used over CDN to hide the actual server IP
- As for private bridges, meek is the best option IMO
- It can be easily integrated with other chain proxy tools

So my question is why don't you just give the meek_lite option for custom bridges to the clients?

**Comment by n8fr8** [comment]
Afaik, we still support meek_lite. We haven't removed any code. We just don't offer default meek bridges in the user interface.

Have you tried using a meek_lite lin with custom bridges?

**Comment by mbrostami** [comment]
@n8fr8 I should've posted this in Orbot for iOS 😬
