### ISSUE TITLE
Orbot overwrites specified Exit Nodes with "{CA}" after a fresh start

### ISSUE THREAD

**Issue by rojoweko** [guardianproject/orbot#77]
When you specify exit nodes that should be used by orbot in the settings, current and recent versions of orbot seem to overwrite this setting with "{CA}" after a fresh start of the app. The last version without this problem appears to be 15.0.1-RC-3-PIE from F-Droid.

**Comment by n8fr8** [comment]
Do you have Canada selected in the left hand side menu? That is the menu that would override any manually settings you have entered. Can you try testing from a fresh install?

**Comment by rojoweko** [comment]
I did not select anything in the left hand side menu. But it appears is if a fresh start of the app would select Canada automatically. I also tried with a fresh install (in order to switch from the f-droid version to the GuardianProject version you have to uninstall Orbot).

**Comment by rojoweko** [comment]
Just an idea: Would it make sence to introduce a setting allowing the user to disable the list of countries in the left hand side menu to solve this problem? That way the user would not be able to select a country and overwrite his exit node settings by accident.

**Comment by n8fr8** [comment]
If he user manually enters something in Settings, it should disable or override the side menu for sure. Will consider this for the next release.

**Comment by rojoweko** [comment]
Thanks a lot! I really appreciate that! ;-)

**Comment by rojoweko** [comment]
Will you have the chance to fix this issue in the upcoming release 16 of Orbot?

**Comment by n8fr8** [comment]
We will do a full triage of all the open tickets in January. never fear!

**Comment by rojoweko** [comment]
Thanks! Great! ;-)

**Comment by n8fr8** [comment]
This should be fixed in the latest beta.

There is a new beta release build to try:
https://github.com/n8fr8/orbot/releases/tag/16.0.2-BETA-3

the "armeabi-v7a" APK should work for most people, or just get the "universal" one if you aren't sure.
