### ISSUE TITLE
Update STUN server list

### ISSUE THREAD

**Issue by n8fr8** [guardianproject/orbot#772]
https://github.com/guardianproject/orbot-apple/issues/45

**Comment by bitmold** [comment]
I updated the STUN Server list, but @n8fr8 it's worth noting that version 17 removed the distinction between "AMP rendezvous" and "domain fronting" snowflake

see in OrbotService:
```java
public void run() {
            var action = mIntent.getAction();
            if (TextUtils.isEmpty(action)) return;
            if (action.equals(ACTION_START)) {
                var connectionPathway = Prefs.getConnectionPathway();
                if (connectionPathway.equals(Prefs.PATHWAY_SNOWFLAKE) || Prefs.getPrefSmartTrySnowflake()) {
                    // todo for now just do domain fronting ...
                    startSnowflakeClientDomainFronting();
                } else if (connectionPathway.equals(Prefs.PATHWAY_CUSTOM) || Prefs.getPrefSmartTryObfs4() != null) {
                    IPtProxy.startObfs4Proxy("DEBUG", false, false, null);
                }
```

**Comment by bitmold** [comment]
We could update the smart connection flow to first try domain fronting and if that fails to try AMP Rendezvous. 

I believe in some old v16 series of Orbot, users could select in the antiquated Bridge Wizard which snowflake configuration they would like... I wonder if there's a usable way to bring that back..?
