### ISSUE TITLE
Please apply “Advanced User Mode” by default

### ISSUE THREAD

**Issue by ghost** [guardianproject/orbot#781]
Hello!
I am a user of your app, which works in conjunction with the AdGuard app ([ADGUARD LOGO](https://user-images.githubusercontent.com/122754090/212569020-82976e71-1dde-4d76-a5e5-9a7c481728e9.jpeg) ), and in order for them to work properly, Orbot needs to give the ability to connect to Tor in local Proxy mode without activating VPN mode ([A screenshot of the function we are going to talk about](https://user-images.githubusercontent.com/122754090/212569105-978e30a0-d0de-4724-a836-4c0bd820cfda.jpeg) ). So can you activate it by default? 

Here is some screenshots of AdGuard function that needs Tor running in local Proxy mode:
[Screenshot 1](https://user-images.githubusercontent.com/122754090/212569239-768e3ccc-c9c8-493e-b980-f40dd43fe272.jpeg) 
[Screenshot 2](https://user-images.githubusercontent.com/122754090/212569242-733a4805-881a-4044-90d6-b48324a7757f.jpeg)

**Comment by n8fr8** [comment]
this is now available, and next release will show the http and socks proxy ports again
