### ISSUE TITLE
Interface proposal

### ISSUE THREAD

**Issue by ghost** [guardianproject/orbot#782]
Hello!
Could you please remove the bottom bar? Everything you need is in the clickable curtain in the upper left corner. Why duplicate functionality?

[SCREENSHOT](https://user-images.githubusercontent.com/122754090/212569390-45fec95d-c1f7-4ece-8703-35de203b71e1.jpeg)

**Comment by n8fr8** [comment]
Thanks for the feedback. We are considering that!
