### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by ghost** [guardianproject/orbot#784]
Hello!
Please tell me the following:

1. Does the application selection function work for routing through Tor in Proxy mode?
2. Is it possible to route ABSOLUTELY ALL of the device's traffic through the Tor network (including DNS requests) using your app?
3. How to fix automatic obfs4 bridging request in Android 7 without having root rights? I will be grateful for instructions. Samsung galaxy s6 device

I am using [17.0.0 BETA 1](https://github.com/guardianproject/orbot/releases/tag/17.0.0-BETA-1-tor.0.4.7.11)

You can close issue after answering

**Comment by n8fr8** [comment]
1. Yes, the apps you pick will go through tor
2. If you choose no apps, then all traffic will go through Tor. If you want to ensure all traffic always goes, please look at VPN settings in Android OS, to enable lockdown features.
3. Not sure what the issues is for Android 7? Do you mean, you do not have bridge request capability? I think that may be something related to the ability to run Go Pluggable Transport code.

**Comment by Timpimlimy** [comment]
I mea a known issue with old certificates on Android 7. It prevents me to request Obfs4 bridges through the app. How can I fix it?

**Comment by syphyr** [comment]
> I mea a known issue with old certificates on Android 7. It prevents me to request Obfs4 bridges through the app. How can I fix it?

You would need to replace the certificates on your device (in /system/etc/security/cacerts/) with these newer certificates from google:
https://android.googlesource.com/platform/system/ca-certificates/+/refs/tags/android-8.1.0_r81/files/

This will require you to have a custom recovery or root access.  Just use adb to push the new certs overwriting the older ones.

**Comment by meenbeese** [comment]
Lastly, this issue can now be closed too as it is resolved @bitmold
