### ISSUE TITLE
No longer seeing number of people helped with Snowflake

### ISSUE THREAD

**Issue by 6jarjar6** [guardianproject/orbot#787]
Updated to the new UI 17.0.0 BETA 1 (Running on Android TV)

Can't see where the number of users helped statistic is.

It was really cool checking it out every time I opened the app.

Thanks

**Comment by n8fr8** [comment]
Try tapping on "kindness mode" tab at the bottom

**Comment by 6jarjar6** [comment]
Kindness mode only shows a switch to turn it on and off, is it below? Maybe it's below and can't access as I am on Android TV. Maybe a layout/version could be made for Android TV. My stick stays on 24/7 so it's acting as a reliable proxy. Maybe others would find it useful to run on their Android TV box/stick. Thank you

**Comment by n8fr8** [comment]
Ohhh, yes once you turn it on, it should display the stats.

I will check the UI display on Android TV. It might be getting lost.

**Comment by 6jarjar6** [comment]
> Ohhh, yes once you turn it on, it should display the stats.
> 
> I will check the UI display on Android TV. It might be getting lost.

Not sure it is being built for Android TV, as I have to launch it through Sideload launcher by Chainfire. Ususally apps built for Android TV show up on the stock app selector.
