### ISSUE TITLE
2 typos in new 17.0.0 beta 1

### ISSUE THREAD

**Issue by Soup333** [guardianproject/orbot#789]
Hi, there are 2 typos in the newest version in the activate kindness mode menu, one is "It will not drain your batter" which should be "battery" not "batter", and "It Can be turned off anytime", where "Can" should not be capitalized and should be "can".

Thank you all for the new beta version of Orbot, it looks great!

![Screenshot_20230126-184501](https://user-images.githubusercontent.com/92235850/215004117-598deba8-774c-4d1a-8f4e-5893ede8e396.png)

**Comment by bitmold** [comment]
Thanks this will be fixed in the next release
