### ISSUE TITLE
Hidden services trouble

### ISSUE THREAD

**Issue by iillyyaa2033** [guardianproject/orbot#79]
Wtf are you done with hidden services?

I'he got 'hostname' and 'private_key' files from my PC. On old versions I can write few lines in 'custom torrc' preference to start hidden service described by this two files. And all was working fine.

But how can I do it now with this beautiful UI but without functionality?

**Comment by n8fr8** [comment]
You can still modify the torrc file in Orbot settings. We've also enabled backup/restore with Onion Services now.
