### ISSUE TITLE
stuck on orbot is starting

### ISSUE THREAD

**Issue by farhan97** [guardianproject/orbot#81]
i have compiled orbot from sources but, when i tap on start it only shows "orbot is starting", also it do not show any logs. please help me to resolve this issue.
Thanks in advance.

**Comment by n8fr8** [comment]
You need to build the native tor runtime, separately from the Android/Gradle build.

Please read the instructions here related to submodules and "make -C external": https://github.com/n8fr8/orbot/blob/master/BUILD

**Comment by Akku05** [comment]
Same issue is happening with me... I am using NDK r13 and done changes Makefile.... and followed all the instruction given in [https://github.com/n8fr8/orbot/blob/master/BUILD](https://github.com/n8fr8/orbot/blob/master/BUILD)

But when I run "make -C external" I get stuck ....

```
touch openssl-build-stamp
test -d lib || mkdir lib
test -d include || mkdir include
test -d include/openssl || mkdir include/openssl
cp openssl/libcrypto.a lib/libcrypto.a
cp openssl/libssl.a lib/libssl.a
cp openssl/include/openssl/* include/openssl
sed -i 's@\(SUBDIRS = . include\) sample test@\1@' libevent/Makefile.am
cp libevent-patch-1 libevent
cd libevent && \
 	patch -N -p1 --reject-file=- < libevent-patch-1
patching file configure.ac
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored
patching file evutil_rand.c
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored
Makefile:156: recipe for target 'libevent/Makefile' failed
make: [libevent/Makefile] Error 1 (ignored)
##sed -i 's@\(AC_OUTPUT(Makefile include/Makefile\) test/Makefile sample/Makefile)@\1)@' libevent/configure.in
cd libevent && ./autogen.sh
./autogen.sh: 11: ./autogen.sh: aclocal: not found
Makefile:156: recipe for target 'libevent/Makefile' failed
make: *** [libevent/Makefile] Error 127
make: Leaving directory '/home/ist/Documents/Personal/orbot/external'
```

will anyone please help me.
