### ISSUE TITLE
Dialogue cut off

### ISSUE THREAD

**Issue by jidanni** [guardianproject/orbot#814]
Due to different users having different Android Settings for  font size and screen magnifications, sometimes dialogue is cut off and can't be scrolled up to see it. This is an accessibility problem.

![Screenshot_20230214_175747_OONI Probe.jpg](https://user-images.githubusercontent.com/1230959/218702441-e01a043b-075f-4f50-8daa-c3a3f3cd8175.jpg)

**Comment by n8fr8** [comment]
This is for the OONI app, not Orbot
