### ISSUE TITLE
Connectivity test needs progress bar

### ISSUE THREAD

**Issue by jidanni** [guardianproject/orbot#815]
Without some kind of progress bar, we don't know if we're going to be here for a minute or an hour.
![Screenshot_20230214_181538_OONI Probe.jpg](https://user-images.githubusercontent.com/1230959/218706701-a1c86a80-d7b7-46d3-a8a4-eece1fdb72ab.jpg)

**Comment by jidanni** [comment]
Oh, it seems there is a progress bar, but we haven't started seeing it yet. It should be visible from the very start.

**Comment by jidanni** [comment]
It seems the problem is with this Web Connectivity Test block. It just doesn't have any kind of progress bar at all.

**Comment by n8fr8** [comment]
This is Orbot, not OONI - please see https://ooni.org/ for reporting bugs on their tool.
