### ISSUE TITLE
But we haven't completed our first test...

### ISSUE THREAD

**Issue by jidanni** [guardianproject/orbot#816]
Here we are running our very first test. The first test still has a tiny bit left before it's complete as you can see in the lower left. However on the upper part of the page we see "last test run 1 minute ago". But we haven't completed our very first test!
![Screenshot_20230214_182148_OONI Probe.jpg](https://user-images.githubusercontent.com/1230959/218708337-31c3e544-36c1-4d42-8909-999c56dff321.jpg)

**Comment by n8fr8** [comment]
We are Orbot not OONI. Please report this to OONI: https://github.com/ooni/probe
