### ISSUE TITLE
Testing a website doesn't work

### ISSUE THREAD

**Issue by jidanni** [guardianproject/orbot#817]
Today let's test a website.
We typed the website in, and press Run and then see this screen:
![Screenshot_20230214_182916_OONI Probe.jpg](https://user-images.githubusercontent.com/1230959/218710697-5b158571-0013-4f6d-a5db-6a82427f5651.jpg)

No there isn't any progress bar.

Okay then after a minute or two the white Web Connectivity Test block at the bottom just disappears.

We look around for the test results but they are nowhere. Not in the test results menu or anywhere.

We have to go back and then type the site in again by hand and then the same thing happens all over again.

By the way, in the image I posted, it'd be great if the name of the website we are currently testing could be, perhaps, shown.

**Comment by meenbeese** [comment]
This issue is in no way related to the Orbot app. Please close it and open a new one for its respective application @jidanni
