### ISSUE TITLE
Could we please get a new release?

### ISSUE THREAD

**Issue by chirayudesai** [guardianproject/orbot#827]
It'd be nice to have a new v16 maintenance release, that includes https://github.com/guardianproject/orbot/pull/767

Last 16.x RC was Dec 7, 2022: https://github.com/guardianproject/orbot/releases/tag/16.6.4-RC-1-tor.0.4.7.11

Last 17.x Beta was Jan 14, 2023: https://github.com/guardianproject/orbot/releases/tag/17.0.0-BETA-1-tor.0.4.7.11

**Comment by chirayudesai** [comment]
Friendly bump :)

Last 16.x RC was Dec 7, 2022: Same as above

Last 17.x Beta was Mar 22, 2023: https://github.com/guardianproject/orbot/releases/tag/17.0.0-BETA-5-tor.0.4.7.11

**Comment by n8fr8** [comment]
We aren't putting out any new v16 maintenance releases.

v17 will be RC and fully public be end of this week.

**Comment by mikeNG** [comment]
Any updates on this?
