### ISSUE TITLE
UI Problems

### ISSUE THREAD

**Issue by ghost** [guardianproject/orbot#832]
Hello!
There is a glitch with incorrect menu display on the Samsung Galaxy s7 device (screenshot below). Android 7, 8, 9 tested. Problem persisted. The problem is most pronounced on 7 and 8. A similar problem persists on most devices with a relatively small screen. I also want to pay attention to the fact that immediately after starting the application logs cannot be scrolled to 100%, scrolling stops at about 95%

[Screenshot of problem](https://user-images.githubusercontent.com/128077614/225703099-65516b65-9d9d-4f94-bc93-d23311fecdc7.jpeg)

I would also like to see the additional menu also called by swiping from the left edge, as this has become one of the most common methods in most applications.

**Comment by n8fr8** [comment]
thank's so much. it is meant to be a scrollable list for a menu, but it is clearly not working. we can create better tuned spacing on smaller screen devices. will get that in before the full release.

**Comment by n8fr8** [comment]
Some improvements here: https://github.com/guardianproject/orbot/releases/tag/17.0.0-BETA-4-tor.0.4.7.11
