### ISSUE TITLE
Check Box overlap

### ISSUE THREAD

**Issue by ingfabby** [guardianproject/orbot#833]
Tested on Galaxy s20, Android 13
Version: 17.0.0-BETA-3-tor.0.4.7.11

The name of the apps overlap with the check box if the name is too long.
![Screenshot_20230316_150816_Orbot](https://user-images.githubusercontent.com/28932186/225742655-069aa967-993d-405b-9b4f-3a080e4af836.jpg)

**Comment by n8fr8** [comment]
Fixed here: https://github.com/guardianproject/orbot/releases/tag/17.0.0-BETA-4-tor.0.4.7.11
