### ISSUE TITLE
[App bug] Language change settings not working correctly

### ISSUE THREAD

**Issue by ghost** [guardianproject/orbot#834]
Hello!
Installed the latest version of your application. I can't change the language to a language other than the system language.

For example:
My system is in English and I can not put the Ukrainian language. After selecting the appropriate language, nothing happens.

Tested on 7 and 13 android. Samsung galaxy s6 and Samsung galaxy S21

**Comment by n8fr8** [comment]
Fix is coming today, thanks!

**Comment by n8fr8** [comment]
Should work now: https://github.com/guardianproject/orbot/releases/tag/17.0.0-BETA-4-tor.0.4.7.11
