### ISSUE TITLE
Notifications broken/missing in 17.0.0 BETA 4

### ISSUE THREAD

**Issue by SkewedZeppelin** [guardianproject/orbot#837]
On DivestOS 20.0/Android 13
Likely due to bumping targetSdk from 31 to 33 without notification [permission](https://developer.android.com/develop/ui/views/notifications/notification-permission) declared
https://github.com/guardianproject/orbot/commit/79c096a4a0b5d0bff9de545307f603d7dc88950e

They worked in beta 3

**Comment by Diapolo** [comment]
I can confirm this behaviour on CalyxOS 4.7.0 / Android 13. Was working with beta 3 :-/.

**Comment by n8fr8** [comment]
Grrrg. Thought we had run through Android 13 smoke tests. Apparently just 12. Thanks for the report.

**Comment by SkewedZeppelin** [comment]
Fixed in beta 5, thanks @n8fr8 !
