### ISSUE TITLE
[Bug] Some UI problems

### ISSUE THREAD

**Issue by ghost** [guardianproject/orbot#838]
Hello!

I had installed [latest version](https://github.com/guardianproject/orbot/releases/tag/17.0.0-BETA-4-tor.0.4.7.11) of your app but some UI problems persistes.

Tested on the Samsung Galaxy s7 device (screenshot below). Android 7, 8, 9 tested. Problem persisted

Here is some screenshots:

[Screenshot 1](https://user-images.githubusercontent.com/128220576/226097659-377968f2-dc9f-43e4-83ac-4e734818c3a4.jpeg)
[Screenshot 2](https://user-images.githubusercontent.com/128220576/226097660-a4d61acf-77b9-4822-9b0e-1085611c2bc3.jpeg)
[Screenshot 3](https://user-images.githubusercontent.com/128220576/226097663-47bfa95e-0dfc-4323-9a89-a3510e66a49d.jpeg)

I hope you will fix it soon! Thank you for your awesome work!

**Comment by bitmold** [comment]
Thanks, I'll get on this soon ...

**Comment by n8fr8** [comment]
What is the Screenshot 3 issue? That the text isn't centered?

**Comment by n8fr8** [comment]
(also yes, we'll be doing more smaller screen tuning this week!)

**Comment by Cycyfyfyf** [comment]
> What is the Screenshot 3 issue? That the text isn't centered?

Yeah :(

**Comment by n8fr8** [comment]
Is your font set at the default size or larger?

**Comment by Gftftf** [comment]
> Is your font set at the default size or larger?

I have default font set :)
