### ISSUE TITLE
[Feature request] Snowflake

### ISSUE THREAD

**Issue by ghost** [guardianproject/orbot#839]
Hello!
Please add the ability to run Snowflake on mobile internet. Many people now have an unlimited rate, which allows you to transfer a large amount of traffic for free, if you pay your bill on time.

Also, not all places have the opportunity to use WiFi for the simple reason that not all wired Internet. And in some places wireless is even faster.

I ask you to add the following features:
- The ability to enable Snowflake on mobile internet
- The ability to automatically turn it off if the internet speed is too slow

Let's fight censorship together!

**Comment by Ftcycg** [comment]
Also what is the difference between Snowflake methods? Could you please explain it to me?

**Comment by n8fr8** [comment]
Why do you think Snowflake doesn't work on mobile internet? There is no limitation in our code related to that.

The two different Snowflake methods are related to how you reach the Snowflake bridge/broker service - one uses Azure/Fastly CDNs and the other Google AMP. Otherwise, no different once they are actually connected and working.

**Comment by Cycyfyfyf** [comment]
Hello @n8fr8!

> Why do you think Snowflake doesn't work on mobile internet? There is no limitation in our code related to that.

I mean Kindness mode.

Where did that information come from? Here:

```
string name="volunteer_mode_subtitle_desc">Kindness mode allows your device to be a bridge for others. It helps people use Tor in places where it is blocked.
\n
\n- It will not drain your battery
\n
\n- It will not slow down your internet
\n
\n- It can run only over wifi
\n
\n- It can be turned off anytime</string>
```

**It can run only over wifi**

Can you remove this limitation?

**Comment by Yftftdyvhc** [comment]
> It "can" means, that is an option. There is a toggle to choose if it only runs on wifi or not. Do you see that option?

Oh. My bad. I didn’t saw that toggle. Sorry for bothering :(
