### ISSUE TITLE
[BUG] Toggle not working

### ISSUE THREAD

**Issue by ghost** [guardianproject/orbot#844]
Hello!
This button from the settings does not change anything. Nothing happens with toggle installed or not. The display of the Orbot notification does not change.

[Screenshot](https://user-images.githubusercontent.com/128737351/227306550-6731944d-6c30-4d34-a638-f5bb1639d864.jpeg)

**Comment by n8fr8** [comment]
This pref has been removed because it didn't do anything as you correctly discovered
