### ISSUE TITLE
Stuck at "Added control port event handler"

### ISSUE THREAD

**Issue by RENOMIZER** [guardianproject/orbot#850]
I'm using latest GP version of Orbot with Lineage OS 20 on my phone and whenever I try to start it the process just stops here
![Screenshot_20230328-002331_Orbot](https://user-images.githubusercontent.com/94466218/228069962-b0b8cc3a-f7e2-4037-ba85-e694c52923e2.png)
No matter what I do, what settings I have it doesn't go any further. 
Is there any solution to this problem?

**Comment by n8fr8** [comment]
Please try our v17 beta release:
https://github.com/guardianproject/orbot/releases/tag/17.0.0-BETA-5-tor.0.4.7.11

It is also available via google play "open testing" beta.

**Comment by RENOMIZER** [comment]
Yeah, it appears the beta version works better.
It still takes forever to start up, but at least it does start eventually.
