### ISSUE TITLE
Issues with Orbi 

### ISSUE THREAD

**Issue by bitmold** [guardianproject/orbot#854]
After continuing to use Orbot 17 for a while I find Orbi's up and down animations to be very distracting. My small circle of friends who I tinker with anonymity tech with seems to agree. 

Beyond that I don't think that touching Orbi should change the state of tor being on and off. There's buttons below her to do just that - one scenario I envision is that a user:

- connects to tor 
- sees orbi's color changes
- interprets the color change as a queue/prompt to interact with orbi (especially with the movement) - not to mention being front and center on the screen screams: "click on me"
- tor is now immediately disconnected 

i am all for a cute mascot over a generic vector graphic of an onion like the old days, i just believe that the cuteness can be harnessed to bolster up a simplified and efficient design rather than adding complexities to users (and to the maintainers of the codebase)

**Comment by Uguchvhvhc** [comment]
I totally disagree. The current "mascot" is very cute and awesome. Don't take it away :)

The only thing I would like to change is to remove the clickable shutdown action from it (to paraphrase: make it so that clicking on Orbi does not shut down Orbot, the power-on function is better left unchanged)

**Comment by n8fr8** [comment]
I agree that we don't want the UX to be confusing and cause accidental disconnect, so point well taken on that front.

_The work to implement and maintain the Orbi aspects of the app are small relative to other aspects of the work, just to put that on the public record._

**Comment by bitmold** [comment]
It seems like you fundamentally misunderstood what I said Uguchvhvhc, I also think the mascot is cute and never wanted to take it away. I'm actually a bit of a maximalist when it comes to cuteness and welcome its proliferation through fashion, UX design, pretty much everything...... 

Anyway, I just wanted to invite a conversation on changing the behavior of clicking on the mascot and having it (dis)connect tor. I envision a lot of users clicking on it since it's so cute and then getting annoyed at the sudden change of the network - I did this, at least. And personally I find the up and down animation distracting, but I think that this is a lesser concern

**Comment by cstiens** [comment]
Hey there! It seems that we can remove the 'clicking on Orbie to turn Tor off'. It was originally kept to stay consistent with the former version. But now that it's live with the new UI, it doesn't seem that we need it.

**Comment by Tctcgc** [comment]
I think that the Orbi click activation can be left as well as the animation. But in the case of the animation it would be better to reduce it to a few seconds

**Comment by syphyr** [comment]
I also think that after connecting to the tor network, the animation for Orbi bouncing infinitely should be changed to maybe 10 bounces at most.
