### ISSUE TITLE
[BUG] Some information missing

### ISSUE THREAD

**Issue by ghost** [guardianproject/orbot#862]
Hello!
The application does not display open local proxy ports in spite of the activated switch in the description of which it is clearly stated that this should happen if this switch is activated:
![IMG_6712](https://user-images.githubusercontent.com/129987184/230161020-812a6238-e354-497f-81c2-e0e7d6eddf6c.jpeg)

**Comment by n8fr8** [comment]
Guess that was removed from the main screen in the UX, and didn't find a new home
