### ISSUE TITLE
[Problem] Weblate stopped working

### ISSUE THREAD

**Issue by ghost** [guardianproject/orbot#871]
Hello!
Suddenly Weblate stopped working. It says that the transfer is blocked.

A screenshot is attached

![IMG_6746](https://user-images.githubusercontent.com/130294239/230775489-414851fb-4e69-4e5b-b34c-e40c89070c37.jpeg)

**Comment by n8fr8** [comment]
somtimes it gets out of sync, and we have to manually fix it

All good now
https://hosted.weblate.org/projects/guardianproject/orbot/
