### ISSUE TITLE
[UI problems] Overlapping text

### ISSUE THREAD

**Issue by ghost** [guardianproject/orbot#874]
Hello!
In the connection settings section (section with ways to bypass blocking), text and UI objects overlap each other.

Tested on Samsung galaxy S7, but this problem is observed on all devices with a small screen

[Screenshot 1](https://user-images.githubusercontent.com/130294239/230777884-14079a67-86e5-4d9e-868e-51ed0d85712e.jpeg)
[Screenshot 2](https://user-images.githubusercontent.com/130294239/230777888-5c6a1d20-a908-4883-8aea-596bad9303b4.jpeg)

**Comment by bitmold** [comment]
on this today
