### ISSUE TITLE
Upgrade to Tor 0.7.13

### ISSUE THREAD

**Issue by Destroyinator69420** [guardianproject/orbot#875]
Always use the latest Tor binary. Torproject now provides binaries for android x86, x86-64 and arm64.

**Comment by n8fr8** [comment]
Thanks. We build and manage our own release of tor-android and will be updating to 0.4.7.13 (not 0.7.13) soon. There is no critical vulnerability in our current 0.4.7.10 release.

**Comment by Yfhchdtx** [comment]
> updating to 0.4.7.13 (not 0.7.13) soon
Can you tell me what the difference?

> There is no critical vulnerability in our current 0.4.7.10 release.
So there is non critical vulnerability?

**Comment by Yfhchdtx** [comment]
@n8fr8, hello!

> updating to 0.4.7.13 (not 0.7.13) soon

Can you tell me what the difference?

> There is no critical vulnerability in our current 0.4.7.10 release.

So there is non critical vulnerability?

**Comment by uniqx** [comment]
@ghost wrote:
> > updating to 0.4.7.13 (not 0.7.13) soon
> 
> Can you tell me what the difference?

Feel free to take a look at Tors change-log: https://raw.githubusercontent.com/torproject/tor/main/ChangeLog I think you can find all the answers you're looking for there.

**Comment by bitmold** [comment]
Closing, now on 0.4.8.7
