### ISSUE TITLE
UI: Button cut off choosing connection type in landscape mode

### ISSUE THREAD

**Issue by syphyr** [guardianproject/orbot#876]
When choosing the connection type, the connect button is cut off on bottom of screen in landscape mode.

![Screenshot_20230412-203027](https://user-images.githubusercontent.com/5009268/231552554-a479379f-7897-4e93-873f-82d4787776b6.png)

**Comment by DanielKonopka** [comment]
Same here! Please, fix it.

**Comment by syphyr** [comment]
I don't know much about fixing UI bugs. Bumping.

**Comment by syphyr** [comment]
@bitmold if you get a chance, could you pls take a look at this?

**Comment by syphyr** [comment]
Fixed
