### ISSUE TITLE
Logcat ContrastColorUtil

### ISSUE THREAD

**Issue by Blank517** [guardianproject/orbot#881]
EDIT:
After rebooting the device a lot of times it got fixed. I can't reproduce the issue anymore.
- - - - -

Android 13 logcat gets flooded with warning logs when Orbot version 17.0.0-RC-1-tor.0.4.7.11 is connected to the Tor network.

![Imagepipe_1](https://user-images.githubusercontent.com/26778354/231588788-cb32bb4f-7703-4368-86e2-376d0365a306.jpg)

**Comment by n8fr8** [comment]
That is a strange warning for sure!

**Comment by Blank517** [comment]
I agree with you, but i'm sure yesterday i got those warn only when i was connected to tor. Maybe it was just a rom issue

**Comment by Blank517** [comment]
I confirm is crDroid 9.3 issue, don't know why orbot was triggering the warning, closed
