### ISSUE TITLE
bug, v17 rc1, 

### ISSUE THREAD

**Issue by starobots** [guardianproject/orbot#882]
1. v16 beta 4, the choose app feature works well. v17 rc1 can use the 'choose app' feature but it's not working, only the app has the proxy setting can work with the orbot port.
2. v17 can't read the ipv6 bridge address, I can't comfirmed it is a bug. When I try to connect the ipv6 bridge, it always stuck at 2% or 10% progress. It happens on v16 and v17.

**Comment by n8fr8** [comment]
@starobots why did you close?

**Comment by starobots** [comment]
Hi!
I solved this problem by a 'clean' installation, deleted all old catch and reinstall the new v17 released apk, it fixed the problem of the v17 beta branch. 
I don't know how to delete this issue, so I closed it. 
Thanks for this project and excellent work.
