### ISSUE TITLE
Orbot doesn't work properly after some hours and says its connected but its not!

### ISSUE THREAD

**Issue by Y-Ghorbani** [guardianproject/orbot#888]
To whom may concern I'm on android 13 and saw this issue several times and the only fixing method is to restart the phone. Please pay attention and let me know if there is any solution.Thank you

**Comment by Y-Ghorbani** [comment]
> SV01 have in my country. 

Excuse me, what is the meaning of SV01?

**Comment by n8fr8** [comment]
Why did you close this ticket @Y-Ghorbani ?

**Comment by Y-Ghorbani** [comment]
> Why did you close this ticket @Y-Ghorbani ?

I found the solution and commented how we can solve the problem
So its done

**Comment by Y-Ghorbani** [comment]
> Okay. We will continue to work on solving the issue with Tor going idle and not restarting/connecting.
> 
> Are you using Tor Bridges / Pluggable Transports?

I usually use tor direct connection because of safety, sometimes snowflake option and rarely use orbot bridges and don't use custom bridges from out of orbot app at all (excuse me what is "Pluggable Transports" ?)

**Comment by n8fr8** [comment]
Pluggable Transports is the developer name for Bridges. :)

**Comment by Y-Ghorbani** [comment]
> Pluggable Transports is the developer name for Bridges. :)

Thank you!
