### ISSUE TITLE
Zstandard compression silently disabled for Orbot

### ISSUE THREAD

**Issue by ahf** [guardianproject/orbot#90]
In commit `90975fb18` `--enable-zstd` was added to Tor's set of `./configure` options, but if we build a debug `.apk` file containing Tor and Orbot we can see that it is not actually enabled in the final binary since Zstd is missing when running `tor --library-versions`:

    ahf@hathor:~/Android/Sdk/platform-tools$ adb shell
    bullhead:/ $ run-as org.torproject.android                                                                                                                                                    
    1|bullhead:/data/data/org.torproject.android $ ./app_bin/tor --library-versions                                                                                                               
    Tor version 0.3.1.8 (git-ad5027f7dc790624). 
    Library versions	Compiled		Runtime
    Libevent		2.0.22-stable  		2.0.22-stable
    OpenSSL 		1.0.2k         		1.0.2k
    Zlib    		1.2.8          		1.2.3

I believe this issue hasn't been spotted because Tor's configure script is silent if it cannot find Zstd's headers while running and will  silently not enable Zstd support in Tor. You can trigger a compilation error in the `make -C external` build process if you install the Zstd headers somewhere on your host file-system (`libzstd-dev` on Debian):

    src/common/compress_zstd.c:22:18: fatal error: zstd.h: No such file or directory #include <zstd.h>

It looks Tor's configure script picks up the host file-system header (the include path might be wrong here?).

I think the right solution is to add `libzstd` as an external dependency in the same manner we have with `libevent` and friends.

**Comment by n8fr8** [comment]
Got it, and lzma, as well. Will work on that as part of the migration of the binary build to its own repo this week!

**Comment by pgerber** [comment]
As far as I can tell, zstd and lzma are working in recent versions of Orbot:

```
May 01 21:57:41.768 [notice] Tor 0.4.2.7 (git-74cad14699087b7e) running on Linux with Libevent 2.1.7-beta, OpenSSL 1.1.1g, Zlib 1.2.11, Liblzma 5.2.3, and Libzstd 1.3.2.
```

**Comment by ahf** [comment]
Looks like it. Maybe this can be closed then?
