### ISSUE TITLE
Which branch or tag should I merge for stable updates?

### ISSUE THREAD

**Issue by TheTanmay1** [guardianproject/orbot#902]
Hello, Guardian Project maintainers and contributors!

I'm interested in updating my fork of the Orbot repository and want to make sure I'm merging with the most stable branch or tag. Could you please provide guidance on which branch or tag I should merge with to ensure a stable experience?

Here's what I'm looking for:

The branch or tag name that represents the most recent stable release.
Any specific instructions or recommendations for merging, if applicable.
If there's a recommended method for staying updated on future stable releases, please let me know.
Thank you for your time and for your work on this project. I'm looking forward to contributing and staying up-to-date with Orbot's development.

**Comment by meenbeese** [comment]
Hello,
To answer your question, you can merge the master branch with the latest changes. The 17x version should be stable enough today and it will probably be out of beta soon. I don't think any other branches are actively developed anyway, so master is your best bet.

**Comment by TheTanmay1** [comment]
> Hello, To answer your question, you can merge the master branch with the latest changes. The 17x version should be stable enough today and it will probably be out of beta soon. I don't think any other branches are actively developed anyway, so master is your best bet.

but sir can't i use release tags? till now i was using release tags...

**Comment by meenbeese** [comment]
> but sir can't i use release tags? till now i was using release tags...

Yes, you can use release tags as well. Sorry for misunderstanding what you meant. The tag I would recommend is ```17.1.1-BETA-3-tor-0.4.8.7``` which is also the latest release. I hope that answers your question, please consider closing the issue if that's the case.
