### ISSUE TITLE
OpenSSL : unknown argument: '-mandroid'

### ISSUE THREAD

**Issue by Joe-Mobarak-WoLf** [guardianproject/orbot#92]
i am getting this issue after make -C external with openssl 
clang: error: unknown argument: '-mandroid'
Please Help

**Comment by goapunk** [comment]
OpenSSL doesn't support compilation with clang yet. You'll have to use GCC.

**Comment by Sean66** [comment]
How I use GCC to execute "make -C external"?

**Comment by Sean66** [comment]
How I use GCC to execute "make -C external"?
1. /external/Makefile
2.make -C external
where I change clang to GCC?

**Comment by goapunk** [comment]
It actually should be used by default. Weird that clang is used for you. Which ndk version did you use ?

**Comment by Sean66** [comment]
android-ndk-r10e was the ndk I used. I used the android-ndk-r10e on Mac, not Debian or Ubuntu. Do I have to use Debian or Ubuntu?

**Comment by goapunk** [comment]
I don't own a mac so I can't test it. Could you post the output of make -C external showsetup ?

**Comment by Sean66** [comment]
1.os:mac 10.12.6 Sierra
2.ndk:android-ndk-r10e
I got an error: clang: error: unknown argument: '-mandroid'
when i execute: make -C external
the shell's log was shown below:

$ make -C external
cd openssl && \
		./Configure android -DL_ENDIAN  && \
		make CC="/Users/x/Downloads/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/Users/x/Downloads/android-ndk-r10e/platforms/android-16/arch-arm" ANDROID_DEV=/Users/x/Downloads/android-ndk-r10e/platforms/android-16/arch-arm/usr depend && \
		make CC="/Users/x/Downloads/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/Users/x/Downloads/android-ndk-r10e/platforms/android-16/arch-arm" ANDROID_DEV=/Users/x/Downloads/android-ndk-r10e/platforms/android-16/arch-arm/usr build_libs
Configuring for android
    no-ec_nistp_64_gcc_128 [default]  OPENSSL_NO_EC_NISTP_64_GCC_128 (skip dir)
    no-gmp          [default]  OPENSSL_NO_GMP (skip dir)
    no-jpake        [experimental] OPENSSL_NO_JPAKE (skip dir)
    no-krb5         [krb5-flavor not specified] OPENSSL_NO_KRB5
    no-libunbound   [experimental] OPENSSL_NO_LIBUNBOUND (skip dir)
    no-md2          [default]  OPENSSL_NO_MD2 (skip dir)
    no-rc5          [default]  OPENSSL_NO_RC5 (skip dir)
    no-rfc3779      [default]  OPENSSL_NO_RFC3779 (skip dir)
    no-sctp         [default]  OPENSSL_NO_SCTP (skip dir)
    no-shared       [default] 
    no-ssl-trace    [default]  OPENSSL_NO_SSL_TRACE (skip dir)
    no-ssl2         [default]  OPENSSL_NO_SSL2 (skip dir)
    no-store        [experimental] OPENSSL_NO_STORE (skip dir)
    no-unit-test    [default]  OPENSSL_NO_UNIT_TEST (skip dir)
    no-weak-ssl-ciphers [default]  OPENSSL_NO_WEAK_SSL_CIPHERS (skip dir)
    no-zlib         [default] 
    no-zlib-dynamic [default] 
IsMK1MF=0
CC            =gcc
CFLAG         =-DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DL_ENDIAN -mandroid -I$(ANDROID_DEV)/include -B$(ANDROID_DEV)/lib -O3 -fomit-frame-pointer -Wall
EX_LIBS       =-ldl
CPUID_OBJ     =mem_clr.o
BN_ASM        =bn_asm.o
EC_ASM        =
DES_ENC       =des_enc.o fcrypt_b.o
AES_ENC       =aes_core.o aes_cbc.o
BF_ENC        =bf_enc.o
CAST_ENC      =c_enc.o
RC4_ENC       =rc4_enc.o rc4_skey.o
RC5_ENC       =rc5_enc.o
MD5_OBJ_ASM   =
SHA1_OBJ_ASM  =
RMD160_OBJ_ASM=
CMLL_ENC      =camellia.o cmll_misc.o cmll_cbc.o
MODES_OBJ     =
ENGINES_OBJ   =
PROCESSOR     =
RANLIB        =/usr/bin/ranlib
ARFLAGS       =
PERL          =/usr/bin/perl
THIRTY_TWO_BIT mode
DES_UNROLL used
DES_INT used
BN_LLONG mode
RC4 uses uchar
RC4_CHUNK is unsigned long
BF_PTR used
e_os2.h => include/openssl/e_os2.h
making links in crypto...
crypto.h => ../include/openssl/crypto.h
opensslv.h => ../include/openssl/opensslv.h
opensslconf.h => ../include/openssl/opensslconf.h
ebcdic.h => ../include/openssl/ebcdic.h
symhacks.h => ../include/openssl/symhacks.h
ossl_typ.h => ../include/openssl/ossl_typ.h
constant_time_test.c => ../test/constant_time_test.c
making links in crypto/objects...
objects.h => ../../include/openssl/objects.h
obj_mac.h => ../../include/openssl/obj_mac.h
making links in crypto/md4...
md4.h => ../../include/openssl/md4.h
md4test.c => ../../test/md4test.c
md4.c => ../../apps/md4.c
making links in crypto/md5...
md5.h => ../../include/openssl/md5.h
md5test.c => ../../test/md5test.c
making links in crypto/sha...
sha.h => ../../include/openssl/sha.h
shatest.c => ../../test/shatest.c
sha1test.c => ../../test/sha1test.c
sha256t.c => ../../test/sha256t.c
sha512t.c => ../../test/sha512t.c
making links in crypto/mdc2...
mdc2.h => ../../include/openssl/mdc2.h
mdc2test.c => ../../test/mdc2test.c
making links in crypto/hmac...
hmac.h => ../../include/openssl/hmac.h
hmactest.c => ../../test/hmactest.c
making links in crypto/ripemd...
ripemd.h => ../../include/openssl/ripemd.h
rmdtest.c => ../../test/rmdtest.c
making links in crypto/whrlpool...
whrlpool.h => ../../include/openssl/whrlpool.h
wp_test.c => ../../test/wp_test.c
making links in crypto/des...
des.h => ../../include/openssl/des.h
des_old.h => ../../include/openssl/des_old.h
destest.c => ../../test/destest.c
making links in crypto/aes...
aes.h => ../../include/openssl/aes.h
making links in crypto/rc2...
rc2.h => ../../include/openssl/rc2.h
rc2test.c => ../../test/rc2test.c
making links in crypto/rc4...
rc4.h => ../../include/openssl/rc4.h
rc4test.c => ../../test/rc4test.c
making links in crypto/idea...
idea.h => ../../include/openssl/idea.h
ideatest.c => ../../test/ideatest.c
making links in crypto/bf...
blowfish.h => ../../include/openssl/blowfish.h
bftest.c => ../../test/bftest.c
making links in crypto/cast...
cast.h => ../../include/openssl/cast.h
casttest.c => ../../test/casttest.c
making links in crypto/camellia...
camellia.h => ../../include/openssl/camellia.h
making links in crypto/seed...
seed.h => ../../include/openssl/seed.h
making links in crypto/modes...
modes.h => ../../include/openssl/modes.h
making links in crypto/bn...
bn.h => ../../include/openssl/bn.h
bntest.c => ../../test/bntest.c
exptest.c => ../../test/exptest.c
making links in crypto/ec...
ec.h => ../../include/openssl/ec.h
ectest.c => ../../test/ectest.c
making links in crypto/rsa...
rsa.h => ../../include/openssl/rsa.h
rsa_test.c => ../../test/rsa_test.c
making links in crypto/dsa...
dsa.h => ../../include/openssl/dsa.h
dsatest.c => ../../test/dsatest.c
making links in crypto/ecdsa...
ecdsa.h => ../../include/openssl/ecdsa.h
ecdsatest.c => ../../test/ecdsatest.c
making links in crypto/dh...
dh.h => ../../include/openssl/dh.h
dhtest.c => ../../test/dhtest.c
making links in crypto/ecdh...
ecdh.h => ../../include/openssl/ecdh.h
ecdhtest.c => ../../test/ecdhtest.c
making links in crypto/dso...
dso.h => ../../include/openssl/dso.h
making links in crypto/engine...
engine.h => ../../include/openssl/engine.h
enginetest.c => ../../test/enginetest.c
making links in crypto/buffer...
buffer.h => ../../include/openssl/buffer.h
making links in crypto/bio...
bio.h => ../../include/openssl/bio.h
making links in crypto/stack...
stack.h => ../../include/openssl/stack.h
safestack.h => ../../include/openssl/safestack.h
making links in crypto/lhash...
lhash.h => ../../include/openssl/lhash.h
making links in crypto/rand...
rand.h => ../../include/openssl/rand.h
randtest.c => ../../test/randtest.c
making links in crypto/err...
err.h => ../../include/openssl/err.h
making links in crypto/evp...
evp.h => ../../include/openssl/evp.h
evp_test.c => ../../test/evp_test.c
evp_extra_test.c => ../../test/evp_extra_test.c
evptests.txt -> ../../test/evptests.txt
making links in crypto/asn1...
asn1.h => ../../include/openssl/asn1.h
asn1_mac.h => ../../include/openssl/asn1_mac.h
asn1t.h => ../../include/openssl/asn1t.h
making links in crypto/pem...
pem.h => ../../include/openssl/pem.h
pem2.h => ../../include/openssl/pem2.h
making links in crypto/x509...
x509.h => ../../include/openssl/x509.h
x509_vfy.h => ../../include/openssl/x509_vfy.h
verify_extra_test.c => ../../test/verify_extra_test.c
making links in crypto/x509v3...
x509v3.h => ../../include/openssl/x509v3.h
v3nametest.c => ../../test/v3nametest.c
making links in crypto/conf...
conf.h => ../../include/openssl/conf.h
conf_api.h => ../../include/openssl/conf_api.h
making links in crypto/txt_db...
txt_db.h => ../../include/openssl/txt_db.h
making links in crypto/pkcs7...
pkcs7.h => ../../include/openssl/pkcs7.h
making links in crypto/pkcs12...
pkcs12.h => ../../include/openssl/pkcs12.h
making links in crypto/comp...
comp.h => ../../include/openssl/comp.h
making links in crypto/ocsp...
ocsp.h => ../../include/openssl/ocsp.h
making links in crypto/ui...
ui.h => ../../include/openssl/ui.h
ui_compat.h => ../../include/openssl/ui_compat.h
making links in crypto/krb5...
krb5_asn.h => ../../include/openssl/krb5_asn.h
making links in crypto/cms...
cms.h => ../../include/openssl/cms.h
making links in crypto/pqueue...
pqueue.h => ../../include/openssl/pqueue.h
making links in crypto/ts...
ts.h => ../../include/openssl/ts.h
making links in crypto/srp...
srp.h => ../../include/openssl/srp.h
srptest.c => ../../test/srptest.c
making links in crypto/cmac...
cmac.h => ../../include/openssl/cmac.h
making links in ssl...
ssl.h => ../include/openssl/ssl.h
ssl2.h => ../include/openssl/ssl2.h
ssl3.h => ../include/openssl/ssl3.h
ssl23.h => ../include/openssl/ssl23.h
tls1.h => ../include/openssl/tls1.h
dtls1.h => ../include/openssl/dtls1.h
kssl.h => ../include/openssl/kssl.h
srtp.h => ../include/openssl/srtp.h
ssltest.c => ../test/ssltest.c
heartbeat_test.c => ../test/heartbeat_test.c
clienthellotest.c => ../test/clienthellotest.c
sslv2conftest.c => ../test/sslv2conftest.c
dtlstest.c => ../test/dtlstest.c
bad_dtls_test.c => ../test/bad_dtls_test.c
making links in engines...
making links in engines/ccgost...
make[3]: Nothing to be done for `links'.
making links in apps...
make[2]: Nothing to be done for `links'.
making links in test...
make[2]: Nothing to be done for `links'.
making links in tools...
make[2]: Nothing to be done for `links'.
generating dummy tests (if needed)...
make[2]: Nothing to be done for `generate'.

Configured for android.
making depend in crypto...
clang: error: unknown argument: '-mandroid'
make[2]: *** [local_depend] Error 1
make[1]: *** [depend] Error 1
make: *** [lib/libcrypto.a] Error 2

**Comment by Joe-Mobarak-WoLf** [comment]
I am having the exact same thing i am trying to switch my compiler from clang which is the default compiler to gcc
i will post if i succeed 
and if sm1 knows a safe way to do it , it would be great to share it

**Comment by goapunk** [comment]
@Sean66 I meant "make -C external showsetup" :)
@Joe-Mobarak-WoLf You are using a Mac as well ?

**Comment by Joe-Mobarak-WoLf** [comment]
yeah i am using a Mac as well

**Comment by Sean66** [comment]
@goapunk 
$ make -C external showsetup
NDK_TOOLCHAIN_VERSION: 4.9
NDK_TOOLCHAIN: arm-linux-androideabi-4.9
NDK_PLATFORM_LEVEL: 16
NDK_SYSROOT: /Users/x/Downloads/android-ndk-r10e/platforms/android-16/arch-arm
APP_ABI: armeabi
HOST: arm-linux-androideabi
CC: /Users/x/Downloads/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/Users/x/Downloads/android-ndk-r10e/platforms/android-16/arch-arm
LD: /Users/x/Downloads/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-ld
CFLAGS: -DANDROID  -fPIE -pie 
LDFLAGS: -llog  -fPIE -pie

**Comment by Joe-Mobarak-WoLf** [comment]
$ make -C external showsetup
NDK_TOOLCHAIN_VERSION: 4.9
NDK_TOOLCHAIN: arm-linux-androideabi-4.9
NDK_PLATFORM_LEVEL: 16
NDK_SYSROOT: /opt/android-ndk/platforms/android-16/arch-arm
APP_ABI: armeabi
HOST: arm-linux-androideabi
CC: /opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/opt/android-ndk/platforms/android-16/arch-arm
LD: /opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-ld
CFLAGS: -DANDROID  -fPIE -pie 
LDFLAGS: -llog  -fPIE -pie
Same here

**Comment by Sean66** [comment]
I got the answer: Mac does't contains gcc, it contains clang.
However, when user execute command on shell like this:
$make -C external
the Mac execute actually
$llvm-gcc -C external
finally
$clang  -C external

**Comment by Joe-Mobarak-WoLf** [comment]
so how to compile with gcc i downloaded it using brew

**Comment by goapunk** [comment]
>I got the answer: Mac does't contains gcc, it contains clang.
However, when user execute command on shell like this:
$make -C external
the Mac execute actually
$llvm-gcc -C external
finally
$clang -C external

@Sean66 
I don't know much about os x but if you install/use gnu make and not the llvm wrapper it could work ?

**Comment by pkalebu** [comment]
Was this solved? How can I go about compiling with gcc instead of clang?

**Comment by goapunk** [comment]
>Was this solved? How can I go about compiling with gcc instead of clang?
Use an older NDK (15 should work). You don't need to compile Tor by yourself any more (see https://github.com/n8fr8/tor-android) to build Orbot.

**Comment by joseandro** [comment]
Using NDK 14b fixed my problem

**Comment by jainabhinav249** [comment]
I am also using NDK 14b but still getting same issue
 unknown argument: '-mandroid'
please help me

**Comment by goapunk** [comment]
@jainabhinav249 Are you running OS X ?

**Comment by jainabhinav249** [comment]
ubuntu 16.04

**Comment by bitmold** [comment]
Closing this because with [tor-android](https://github.com/guardianproject/tor-android) hackers building Orbot don't need to build `tor` themselves anymore and because in general the build process has changed significantly since this ticket was open. Feel free to post here/contact me if anyone has any questions
