### ISSUE TITLE
Bring back orbot's proxy mode to use orbot without vpn in proxy mode

### ISSUE THREAD

**Issue by User1l0** [guardianproject/orbot#923]

**Comment by canary5** [comment]
How to use orbot with own vpn? Just proxy to some apps?

**Comment by n8fr8** [comment]
The VPN is not battery draining - it is not like a typical remote network VPN. It just takes packets from the apps you choose, and sends them through the Tor Proxy ports. It is the same as setting proxy values in the app.

**Comment by Alexey104** [comment]
> I Just need my favorite proxy mode without using vpn

In Orbot, go to settings and check `General`->`Power User Mode`. This is what you want.

**Comment by ccuser44** [comment]
This exists under

More > Settings > General > Advanced user mode

**Comment by ccuser44** [comment]
> Hope they bring back the vpn/proxy switch

It's not removed

**Comment by ghu1234** [comment]
Pls explain how to enable normal proxy mode instead of VPN mode, it is not clear

**Comment by bitmold** [comment]
Open the settings and enable power user mode.
