### ISSUE TITLE
New GUI Sucks.

### ISSUE THREAD

**Issue by now0clock** [guardianproject/orbot#947]
Hello. Long time fan. and beta tester. Now I have reverted to:

version 16.6.4-RC-1-tor.0.4.7.11

org.torproject.android
versionCode 1664300102

targetSdk 31
minSdk 16

**Comment by meenbeese** [comment]
Please either describe concretely what "sucks" about the new GUI so a fix can be potentially found or close the issue. Many people do benefit from the streamlined GUI so you can't completely dismiss it like that. @now0clock

**Comment by tkbstudios** [comment]
You suck the new UI is much better to the old one no one cares about your opinion and please don't open issues for that, if you want to open an issue about a UI that "sucks" please describe better what could be changed. Now close this issue as Not Planned/invalid

**Comment by meenbeese** [comment]
> Only thing I can see now that kinda sucks is not being able to slide to the left from the main screen to see the logs anymore.

Now, THAT'S a good point which I extracted into a separate issue in #1022. We can improve the app and solve problems easily when we emphasize logic over emotions. Thanks for clearly identifying your problem and you can open new issues if you think of any more in the future.
