### ISSUE TITLE
The confusing new icon

### ISSUE THREAD

**Issue by hax0rbana-adam** [guardianproject/orbot#958]
This ticket is a request to change the Orbot icon.

I'm really surprised there isn't already an open issue about this, but... the new icon looks so much like a penis and testicles, it was difficult to figure out what it was supposed to be. After I figured out that it's the top of the little mascot's head, the only thing I could think is: why does he have a dick on his head?

![Orbot-cock](https://github.com/guardianproject/orbot/assets/118935832/60a8d111-392e-49fd-9654-d2b342d5e3c5)

Just to sanity check me, I've asked several other people, of various genders, what they think of the icon and everyone has said it looks like male private parts.

Just changing the icon to have the whole mascot instead of just the top of his head would suffice. Also changing the mascot's antennae, or whatever they're supposed to be, so they don't look dirty would be even better.

**Comment by Orbie-is-super-cute** [comment]
I don’t see that thing in logo.

I think mascot is really cute and good looking.

**Comment by Sigma-One** [comment]
i didn't see anything dirty at first but can definitely see how one would when only this part is in focus

i do think the icon is just plain confusing though, and should be changed to something which identifies the app better while also being clearly *something*

i couldn't connect this with the mascot until someone mentioned it, and i do agree that a better icon would be fore example the whole mascot

**Comment by meenbeese** [comment]
> i couldn't connect this with the mascot until someone mentioned it, and i do agree that a better icon would be fore example the whole mascot

I think this is a much more mature and reasonable take on your part compared to the original one. It makes sense to shift the focus from the mascot's hair to make it more understandable.

Does anyone have a concrete idea or proposal for this?

**Comment by lbdroid** [comment]
It doesn't matter what the icon is *meant* to be, it matters what people actually think when they see it. EVERYONE I've spoken to about it has independently come up with the thought that it looks like a dick and balls.

The icon looks *ok* at this older revision;
https://github.com/guardianproject/orbot/blob/865c5c475c09354943b3486e026d7aeac1d2ac96/app/src/main/ic_launcher-playstore.png

But now that the stuff on the top of the little guy's head is associated with a dick, it really should be removed -- make the top curve smooth and uninterrupted. It doesn't make sense to have hair or anything there anyway, since the little guy is clearly wearing a helmeted space suit.

**Comment by hax0rbana-adam** [comment]
I made an updated version of Orbie based on @lbdroid's suggestion

![orbie-new](https://github.com/guardianproject/orbot/assets/118935832/0cf6e6ca-b3ac-44af-8de5-bf9accbbac5c)

**Comment by YourOwner-XD** [comment]
I’m not good at photoshop at all but I think something like this should be on logo:

![5EBBA759-66B8-4EC2-8796-272F215E3974](https://github.com/guardianproject/orbot/assets/142351204/5ab961e6-c18b-4237-9291-8f42dee5b6af)

Is is only sample.
https://github.com/guardianproject/orbot/issues/958#issuecomment-1679167938 this variant a little bit unfinished, something missing.


[This one](https://github.com/guardianproject/orbot/blob/865c5c475c09354943b3486e026d7aeac1d2ac96/app/src/main/ic_launcher-playstore.png) is good too, but [this](https://user-images.githubusercontent.com/118935832/260283175-60a8d111-392e-49fd-9654-d2b342d5e3c5.png) should be definitely changed.
——
**So my variant is:**
To set as app icon this pic: [CLICK](https://user-images.githubusercontent.com/118935832/260283175-60a8d111-392e-49fd-9654-d2b342d5e3c5.png)

**Comment by TinyBobcat** [comment]
https://github.com/guardianproject/orbot/issues/958#issuecomment-1679572091 I think this should be untouched. Balls and dicks is only in some users fantasy, so it is fine for me
![](https://user-images.githubusercontent.com/118935832/260283175-60a8d111-392e-49fd-9654-d2b342d5e3c5.png)

**Comment by hax0rbana-adam** [comment]
FYSA: every single one of these comments saying the logo should not change were made by the same person who has registered 18 brand new accounts, just to troll this issue (as can be seen by the accounts' join date/time). So if a moderator wants to step in and clean them up, that could help us make progress on this ticket.

**Comment by gentleAmateur** [comment]
That sounds like a conspiracy theory.

**Comment by brianSchanbacher** [comment]
The new proposed logo looks much better and actually makes sense. Regardless of the various interpretations of the original, it doesn't really look like a product logo and looks out of place imo.

**Comment by Hvtduhufyc** [comment]
I am totally against changing new icon for something else.

There is no mor perverts except of the hax0rbana-adam friends

**Comment by tkbstudios** [comment]
> It doesn't matter what the icon is _meant_ to be, it matters what people actually think when they see it. EVERYONE I've spoken to about it (all women) has independently come up with the thought that it looks like a dick and balls.
> 
> The icon looks _ok_ at this older revision; https://github.com/guardianproject/orbot/blob/865c5c475c09354943b3486e026d7aeac1d2ac96/app/src/main/ic_launcher-playstore.png
> 
> But now that the stuff on the top of the little guy's head is associated with a dick, it really should be removed -- make the top curve smooth and uninterrupted. It doesn't make sense to have hair or anything there anyway, since the little guy is clearly wearing a helmeted space suit.

Then all the people you spoke to really do have an issue with that body part because I don't see anything like that in the icon and I instantly did the link between it and the mascot I really don't understand how people today are so messed up :/ I bet @hax0rbana-adam 's friends are probably teenagers..

**Comment by Telegramer6** [comment]
I found the screenshot of this discussion on some telegram channel and I am here to comment it.

I think everyone already said that they are against, but… I have a question:

@hax0rbana-adam are you a kid? Or you have no relationship? Why balls? Personally I see only the cute haircut.

So please stop making ridiculous comments and issues. Make something really useful. It is not a psychological cabinet.

**Comment by tkbstudios** [comment]
Exactly that's what I said this is a ridiculous issue and it does waste time of the devs. I suggest you just go get some balls to see how balls look actually

**Comment by tkbstudios** [comment]
Now someone close this issue as Not Planned

**Comment by meenbeese** [comment]
> FYSA: every single one of these comments saying the logo should not change were made by the same person who has registered 18 brand new accounts, just to troll this issue (as can be seen by the accounts' join date/time). So if a moderator wants to step in and clean them up, that could help us make progress on this ticket.

Ahem... this problem is starting to get worse day by day. It doesn't take a genius to figure that something fishy is going on here. I will contact the mods now as this is getting out of control.

**Comment by tkbstudios** [comment]
yeah

**Comment by theAkito** [comment]
You and your friends probably browse 9GAG 27 hours a day or something similar. Even after you mentioned it, I cannot see what you describe.

I'm pretty sure, this issue says more about how broken some meme poisoned brains are, than about how this icon actually looks...

**Comment by Piker68** [comment]
Totally ridiculous issue. Just google what you think on the logo and compare to logo. Nothing in common.
