### ISSUE TITLE
Cute new icon disappeared

### ISSUE THREAD

**Issue by WeboR6** [guardianproject/orbot#959]
Hello!

After last update a new icon disappeared:
![IMG_9577](https://github.com/guardianproject/orbot/assets/142148761/8be5a6b2-44b2-4727-be82-068678c3dc42)

And it becomes like this:
![IMG_9578](https://github.com/guardianproject/orbot/assets/142148761/4bc0128b-a2a4-4055-8cde-c0b31ed221ee)

Please fix the issue! It is a little confusing :)

Fo now reverted for previous version

**Comment by errorgurumeditation** [comment]
looks like it was intentionally reverted in 9bc9cbe

**Comment by tkbstudios** [comment]
> looks like it was intentionally reverted in [9bc9cbe](https://github.com/guardianproject/orbot/commit/9bc9cbeee01821b9b920a5afe846abce5faafaa9)

As @errorgurumeditation mentioned, he is correct, please close this issue as Not Planned or invalid

**Comment by bitmold** [comment]
CLosing
