### ISSUE TITLE
Orbot on iPad iOS 16.6

### ISSUE THREAD

**Issue by fshinneman** [guardianproject/orbot#966]
1) After opening Orbot, the TOR page with search bar does not open. Orbot often repeatedly shows "Connecting" then stops then shows "Ready to Connect". "Start" repeats this loop.

2) After closing Orbot, Safari cannot open regularly used web sites (e.g. Axios, NYTimes, etc. "Cannot connect to server".  VPN is not connected in settings. Power-off/Power-on and ORBOT VPN automatically launches and Safari cannot connect to web sites.  Turn off VPN and Safari still cannot connect and Orbot VPN continues to launch. In Orbot settings I have auto restart on error and disable orbot for non-onion traffic. Only solution is to delete the Orbot app. to allow Safari to operate normally.

**Comment by meenbeese** [comment]
This repository is for Orbot Android. Since your issue is related to the Orbot iOS app, please close this issue and open a new one here: https://github.com/guardianproject/orbot-apple.
Thanks, @fshinneman
