### ISSUE TITLE
latest release not building : Issues with AAR Metadata and Duplicate Classes in Dependencies

### ISSUE THREAD

**Issue by monospare** [guardianproject/orbot#976]
I am facing several build failures while using the latest release tagged as 17.1.0-BETA-3-tor.0.4.7.14. I am working on a Windows 11 system and using Android Studio. The issues are as follows:

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app-tv:checkTeeveeDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > 4 issues were found when checking AAR metadata:
     
       1.  Dependency 'androidx.appcompat:appcompat-resources:1.5.0' requires libraries and applications that
           depend on it to compile against version 32 or later of the
           Android APIs.
     
           :app-tv is currently compiled against android-31.
     
           Recommended action: Update this project to use a newer compileSdkVersion
           of at least 32, for example 33.
     
           Note that updating a library or application's compileSdkVersion (which
           allows newer APIs to be used) can be done separately from updating
           targetSdkVersion (which opts the app in to new runtime behavior) and
           minSdkVersion (which determines which devices the app can be installed
           on).
     
       2.  Dependency 'androidx.appcompat:appcompat:1.5.0' requires libraries and applications that
           depend on it to compile against version 32 or later of the
           Android APIs.
     
           :app-tv is currently compiled against android-31.
     
           Recommended action: Update this project to use a newer compileSdkVersion
           of at least 32, for example 33.
     
           Note that updating a library or application's compileSdkVersion (which
           allows newer APIs to be used) can be done separately from updating
           targetSdkVersion (which opts the app in to new runtime behavior) and
           minSdkVersion (which determines which devices the app can be installed
           on).
     
       3.  Dependency 'androidx.emoji2:emoji2-views-helper:1.2.0' requires libraries and applications that
           depend on it to compile against version 32 or later of the
           Android APIs.
     
           :app-tv is currently compiled against android-31.
     
           Recommended action: Update this project to use a newer compileSdkVersion
           of at least 32, for example 33.
     
           Note that updating a library or application's compileSdkVersion (which
           allows newer APIs to be used) can be done separately from updating
           targetSdkVersion (which opts the app in to new runtime behavior) and
           minSdkVersion (which determines which devices the app can be installed
           on).
     
       4.  Dependency 'androidx.emoji2:emoji2:1.2.0' requires libraries and applications that
           depend on it to compile against version 32 or later of the
           Android APIs.
     
           :app-tv is currently compiled against android-31.
     
           Recommended action: Update this project to use a newer compileSdkVersion
           of at least 32, for example 33.
     
           Note that updating a library or application's compileSdkVersion (which
           allows newer APIs to be used) can be done separately from updating
           targetSdkVersion (which opts the app in to new runtime behavior) and
           minSdkVersion (which determines which devices the app can be installed
           on).

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app-tv:checkTeeveeDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class androidx.lifecycle.ViewModelLazy found in modules jetified-lifecycle-viewmodel-ktx-2.2.0-runtime (androidx.lifecycle:lifecycle-viewmodel-ktx:2.2.0) and lifecycle-viewmodel-2.5.0-runtime (androidx.lifecycle:lifecycle-viewmodel:2.5.0)
     
     Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

**Comment by syphyr** [comment]
https://github.com/guardianproject/orbot/pull/969

**Comment by TheTanmay1** [comment]
> #969

sorry? can you elaborate?

**Comment by syphyr** [comment]
The build should be fixed by cherry picking the commits in the link I posted.

**Comment by syphyr** [comment]
git fetch https://github.com/syphyr/orbot fix_teevee && git cherry-pick 7a65a7b ecdaeb6 075fe42 e04c8df

**Comment by syphyr** [comment]
BTW, when building master branch, you will also need to cherry pick the commit here as well: https://github.com/guardianproject/orbot/pull/868
