### ISSUE TITLE
String is too long, needs to wrap

### ISSUE THREAD

**Issue by emmapeel2** [guardianproject/orbot#992]
The string 'These are advanced settings that can reduce your anonymity' / pref_node_configuration_summary is too long and does not fix on certain screens. Needs to be wrapped.

Reported by translator @olavinto in weblate: https://hosted.weblate.org/translate/guardianproject/orbot/en/?checksum=380e3e562b43ee75

![resized005](https://github.com/guardianproject/orbot/assets/11485015/18c21d7a-75bd-4311-a4fa-20c6e2539754)

**Comment by Blank517** [comment]
On a screen with 409 DPI

![Screenshot_20231022-013814_1](https://github.com/guardianproject/orbot/assets/26778354/e264ba87-2ee0-4904-9ed0-fc4d163c2b8c)

**Comment by Crchbhvtxtv** [comment]
I can confirm this. @n8fr8 can you please try to line texts properly?

Like this:
![IMG_0996](https://github.com/guardianproject/orbot/assets/149334202/66caa8d4-b88a-43b5-8b94-908269f875be)

**Comment by bitmold** [comment]
Unfortunately to ghosts comment that is the "proper" way those preferences are supposed to appear within the android UI framework that Orbot uses ... 

The entire framework is really limited though, it's deprecated and we need to upgrade to androidx, but even if we do the @n8fr8 `PreferenceCategory` View that we use here won't support wrapping the summary (kind of ridiculous) 

I am about to introduce a kludge-y that will at least put all of that text onto the screen, however it will be slightly inconsistent with the rest of the UI...
